/*
 * chs_oracle_synth.c -- Chinese oracle synthesis for the VvTts app bridge.
 *
 * The openevv chs module's rules are unbuilt stubs (DeltaProc_* returning
 * "done" with no output), so the engine itself synthesizes nothing for
 * Chinese.  The oracle pipeline (oracle-fanout / assemble) captured the
 * real audio of the reference Apple engine per hanzi -- raw 16-bit mono
 * 11.025 kHz PCM -- and oracle/fitter.py baked it into oracle_chs.c keyed
 * by both the Unicode codepoint (probe/tests) and the raw GB18030 bytes
 * (what the app actually sends for zh).
 *
 * This file turns a GB18030 byte string (charsetId == CHARSET_GBK) into a
 * PCM buffer with zero engine calls.  It is shared verbatim by the JNI
 * bridge and the CI smoke test (oracle/chs_smoke.c), so the byte-walk and
 * lookup logic is exercised on a runner.
 */
#include "chs_oracle_synth.h"

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

/* Generated by oracle/fitter.py: raw GB18030 key -> oracle PCM lookup. */
extern int chs_oracle_pcm_for_gbk(uint32_t gbk, const uint8_t **data, uint32_t *len);

/* Advance one GB18030 character from s[i]; set *key; return consumed bytes.
 * 0 = malformed sequence (caller skips one byte).  ASCII (< 0x80) returns
 * size 1 with the byte itself as key (caller decides what ASCII means). */
static size_t gb_advance(const unsigned char *s, size_t n, size_t i, uint32_t *key) {
    unsigned char b1 = s[i];
    if (b1 < 0x80) { *key = b1; return 1; }
    if (b1 >= 0x81 && b1 <= 0xFE && i + 1 < n) {
        unsigned char b2 = s[i + 1];
        if (b2 >= 0x30 && b2 <= 0x39 && i + 3 < n) {
            /* GB18030 four-byte extension: 81-FE 30-39 81-FE 30-39 */
            *key = ((uint32_t)b1 << 24) | ((uint32_t)b2 << 16)
                 | ((uint32_t)s[i + 2] << 8) | (uint32_t)s[i + 3];
            return 4;
        }
        if (b2 >= 0x40 && b2 <= 0xFE && b2 != 0x7F) {
            *key = ((uint32_t)b1 << 8) | (uint32_t)b2;
            return 2;
        }
    }
    return 0;
}

size_t chs_build_pcm(const unsigned char *src, size_t n, short **out) {
    const uint8_t *d;
    uint32_t ln, key;
    size_t i, adv, total = 0, off = 0;
    short *pcm;
    *out = NULL;

    /* Pass 1: total byte length of every match. */
    for (i = 0; i < n;) {
        adv = gb_advance(src, n, i, &key);
        if (!adv) { i++; continue; }
        i += adv;
        if (key < 0x80) continue;
        if (chs_oracle_pcm_for_gbk(key, &d, &ln)) total += ln;
    }
    if (total == 0) return 0;

    pcm = (short *)malloc(total);
    if (!pcm) return 0;

    /* Pass 2: copy the PCM stretches out. */
    for (i = 0; i < n;) {
        adv = gb_advance(src, n, i, &key);
        if (!adv) { i++; continue; }
        i += adv;
        if (key < 0x80) continue;
        if (chs_oracle_pcm_for_gbk(key, &d, &ln)) {
            memcpy((unsigned char *)pcm + off, d, ln);
            off += ln;
        }
    }
    *out = pcm;
    return off / 2;  /* samples; off is always even (16-bit PCM) */
}