#!/bin/bash
# Eloquence TTS for Android build script
# Requirements:Linux + Android SDK(aapt/d8/zipalign/apksigner)+ JDK 11+
#
# Environment variables to set before use:
#   ANDROID_SDK   Android SDK root (default /usr/lib/android-sdk)
#   BUILD_TOOLS   build-tools version (default 35.0.0)
#   KEYSTORE      signing keystore path (default vvtts.jks)
#   KS_PASS       keystore password (default android123)
#   KEY_PASS      key password (defaultandroid123)

set -u
SDK="${ANDROID_SDK:-/usr/lib/android-sdk}"
BUILD_TOOLS="${BUILD_TOOLS:-35.0.0}"
AAPT="$SDK/build-tools/$BUILD_TOOLS/aapt"
D8="$SDK/build-tools/$BUILD_TOOLS/d8"
ZIPALIGN="$SDK/build-tools/$BUILD_TOOLS/zipalign"
APKSIGNER="$SDK/build-tools/$BUILD_TOOLS/apksigner"
ANDROID_JAR="$SDK/platforms/android-34/android.jar"
KEYSTORE="${KEYSTORE:-vvtts.jks}"
KS_PASS="${KS_PASS:-android123}"
KEY_PASS="${KEY_PASS:-android123}"

# Working directory ＝ the script's directory
cd "$(dirname "$0")"

LIBS_DIR="libs"

# ---- P3: single packed models.elqm + ASM-patched lingua-slim.jar ----
# Lossless pack (oracle-verified); the patched jar reads models.elqm with
# fallback to per-file JSON inside the bridge.  No classes.dex / build.gradle edits.
P3DIR="tools/p3_golden"
ASM_JAR="$P3DIR/asm.jar"
ELQM="language-models/models.elqm"

if [ ! -f "$ELQM" ] || find language-models -name '*.json' -newer "$ELQM" | grep -q .; then
  echo "[P3] packing $ELQM ..."
  python3 tools/model_pack.py pack --prune language-models "$ELQM" || exit 1
fi

if ! unzip -l libs/lingua-slim.jar | grep -q "ElqmBridge.class"; then
  echo "[P3] patching libs/lingua-slim.jar (bridge: packed models.elqm, fallback per-file) ..."
  rm -rf "$P3DIR/build"
  mkdir -p "$P3DIR/build"
  javac -source 11 -target 11 -d "$P3DIR/build" "$P3DIR/ElqmBridge.java" 2>&1 || exit 1
  javac -cp "$ASM_JAR" -d "$P3DIR/build" "$P3DIR/PatchLingua.java" 2>&1 || exit 1
cp libs/lingua-slim.jar /tmp/lingua-pristine.jar
  java -cp "$P3DIR/build:$ASM_JAR" PatchLingua /tmp/lingua-pristine.jar libs/lingua-slim.jar "$P3DIR/build/com/github/pemistahl/lingua/internal/ElqmBridge.class" || exit 1
  rm -f /tmp/lingua-pristine.jar
fi

# 0. Compile resources with aapt and generate R.java
rm -rf gen
mkdir -p gen
"$AAPT" package -f -m -J gen -M AndroidManifest.xml -S res -I "$ANDROID_JAR" 2>&1
if [ $? -ne 0 ]; then echo "AAPT GEN R FAILED"; exit 1; fi

# 1. Compile all Kotlin sources(Phase 1:Kotlin-only,,zero Java)
KOTLINC="${KOTLINC:-/opt/kotlinc/kotlinc/bin/kotlinc}"
# Alt:point KOTLINC_CP at the three jars "compiler:trove4j:stdlib" and launch K2JVMCompiler via Java directly(no unpacking)
KOTLINC_CP="${KOTLINC_CP:-}"
rm -rf out_classes
mkdir -p out_classes
find src gen -name '*.kt' > /tmp/kt_sources.txt
# the R.java generated by aapt is Java source;compile it into out_classes with javac first
find gen -name '*.java' > /tmp/r_sources.txt
if [ -s /tmp/r_sources.txt ]; then
  javac -source 11 -target 11 -classpath "$ANDROID_JAR" -d out_classes @/tmp/r_sources.txt 2>&1
  if [ $? -ne 0 ]; then echo "R COMPILE FAILED"; exit 1; fi
fi
KT_CLASSPATH="$ANDROID_JAR:out_classes:$LIBS_DIR/lingua-slim.jar:$LIBS_DIR/kotlin-stdlib-1.9.25.jar"
if [ -n "$KOTLINC_CP" ]; then
  java -cp "$KOTLINC_CP" org.jetbrains.kotlin.cli.jvm.K2JVMCompiler \
    -jvm-target 1.8 -classpath "$KT_CLASSPATH" -d out_classes @/tmp/kt_sources.txt 2>&1
else
  "$KOTLINC" -jvm-target 1.8 -classpath "$KT_CLASSPATH" -d out_classes @/tmp/kt_sources.txt 2>&1
fi
if [ $? -ne 0 ]; then echo "COMPILE FAILED"; exit 1; fi

# 2. D8 to dex
rm -rf out_dex
mkdir -p out_dex
find out_classes -name '*.class' > /tmp/class_files.txt
"$D8" --min-api "${MIN_API:-28}" --output out_dex @/tmp/class_files.txt \
  "$LIBS_DIR/lingua-slim.jar" \
  "$LIBS_DIR/kotlin-stdlib-1.9.25.jar" \
  "$LIBS_DIR/okio.jar" \
  "$LIBS_DIR/moshi.jar" \
  "$LIBS_DIR/moshi-kotlin.jar" \
  "$LIBS_DIR/fastutil.jar" \
  "$LIBS_DIR/kotlin-reflect.jar" 2>&1
if [ $? -ne 0 ]; then echo "D8 FAILED"; exit 1; fi

# 2.5. Build the native bridge first if missing (openevv + JNI core); no Apple code).
# CI runs build_native.sh as its own earlier step; this guard covers fresh clones
# where only build.sh was invoked.  ABI modes: universal = all present ABIs (arm64
# + arm32); or a single ABI (arm64-v8a / armeabi-v7a / x86_64) for slim builds;
# emulator-test workflow builds x86_64.
ABI="${ABI:-universal}"
case "$ABI" in
  universal) ABIS="arm64-v8a armeabi-v7a x86_64" ;;
  *)        ABIS="$ABI" ;;
esac
for need in $ABIS; do
  if [ ! -f "native-libs/$need/libvvtts_core.so" ]; then
    echo "libvvtts_core.so missing ($need) -- running build_native.sh first..."
    ABI="$need" bash build_native.sh || exit $?
  fi
done

# 3. Assemble the APK
rm -rf tmp_apk vvtts_base.apk vvtts_unsigned.apk vvtts_aligned.apk vvtts_signed.apk
mkdir -p tmp_apk/lib/arm64-v8a tmp_apk/lib/armeabi-v7a tmp_apk/lib/x86_64 tmp_apk/assets
[ -d assets ] && cp -r assets/. tmp_apk/assets/   # crash-code defender corpus (~48KB gz)

# Copy all dex files(multidex)
cp out_dex/classes*.dex tmp_apk/
# Copy native language libs(ABI=universal copies all,,otherwise single ABI)— single ABI yields athin APK
for abi in $ABIS; do
  if [ -d "native-libs/$abi" ]; then
    cp "native-libs/$abi"/*.so "tmp_apk/lib/$abi/"
  fi
done
# Copy Lingua language models(must go in the APK root)— P3 re-baseline:
# ship ONLY models.elqm(golden-compare verified,,byte-identical);JSON sources stay in
#the repo(authoritative input for packing/re-packing),but no longer ride along in the APK as fallback bytes.
cp -r language-models tmp_apk/
find tmp_apk/language-models -name '*.json' -delete

"$AAPT" package -f -M AndroidManifest.xml -S res -A tmp_apk/assets -I "$ANDROID_JAR" -F vvtts_base.apk 2>&1
if [ $? -ne 0 ]; then echo "AAPT FAILED"; exit 1; fi

cp vvtts_base.apk vvtts_unsigned.apk
cd tmp_apk && zip -9 -r ../vvtts_unsigned.apk classes*.dex language-models lib > /dev/null && cd ..

# 4. Sign
"$ZIPALIGN" -f 4 vvtts_unsigned.apk vvtts_aligned.apk
"$APKSIGNER" sign --ks "$KEYSTORE" --ks-pass "pass:$KS_PASS" --key-pass "pass:$KEY_PASS" --out vvtts_signed.apk vvtts_aligned.apk
"$APKSIGNER" verify vvtts_signed.apk 2>&1 | head -3

echo "=== BUILD DONE ==="

# ===== SIZE REPORT (Phase 0) =====
unzip -l vvtts_signed.apk | awk '
  /classes.*dex/ {dex+=$1} /lib\// {lib+=$1} /language-models/ {m+=$1}
  END {printf "dex=%d lib=%d models=%d total=%d\n", dex, lib, m, dex+lib+m}'
ls -l vvtts_signed.apk | awk '{printf "APK_ON_DISK=%d\n", $5}'
ls -lh vvtts_signed.apk