package com.xw.vvtts.utils

internal val EMOJI_ZHANS_07: Map<String, String> = mapOf(
                "\\uD83D\\uDE45\\uD83C\\uDFFF" to "禁止手势, 较深肤色",
                "\\uD83D\\uDE46\\uD83C\\uDFFB" to "OK手势, 较浅肤色",
                "\\uD83D\\uDE46\\uD83C\\uDFFC" to "OK手势, 中等-浅肤色",
                "\\uD83D\\uDE46\\uD83C\\uDFFD" to "OK手势, 中等肤色",
                "\\uD83D\\uDE46\\uD83C\\uDFFE" to "OK手势, 中等-深肤色",
                "\\uD83D\\uDE46\\uD83C\\uDFFF" to "OK手势, 较深肤色",
                "\\uD83D\\uDC81\\uD83C\\uDFFB" to "前台, 较浅肤色",
                "\\uD83D\\uDC81\\uD83C\\uDFFC" to "前台, 中等-浅肤色",
                "\\uD83D\\uDC81\\uD83C\\uDFFD" to "前台, 中等肤色",
                "\\uD83D\\uDC81\\uD83C\\uDFFE" to "前台, 中等-深肤色",
                "\\uD83D\\uDC81\\uD83C\\uDFFF" to "前台, 较深肤色",
                "\\uD83D\\uDE4B\\uD83C\\uDFFB" to "举手, 较浅肤色",
                "\\uD83D\\uDE4B\\uD83C\\uDFFC" to "举手, 中等-浅肤色",
                "\\uD83D\\uDE4B\\uD83C\\uDFFD" to "举手, 中等肤色",
                "\\uD83D\\uDE4B\\uD83C\\uDFFE" to "举手, 中等-深肤色",
                "\\uD83D\\uDE4B\\uD83C\\uDFFF" to "举手, 较深肤色",
                "\\uD83E\\uDDCF\\uD83C\\uDFFB" to "失聪者, 较浅肤色",
                "\\uD83E\\uDDCF\\uD83C\\uDFFC" to "失聪者, 中等-浅肤色",
                "\\uD83E\\uDDCF\\uD83C\\uDFFD" to "失聪者, 中等肤色",
                "\\uD83E\\uDDCF\\uD83C\\uDFFE" to "失聪者, 中等-深肤色",
                "\\uD83E\\uDDCF\\uD83C\\uDFFF" to "失聪者, 较深肤色",
                "\\uD83D\\uDE47\\uD83C\\uDFFB" to "鞠躬, 较浅肤色",
                "\\uD83D\\uDE47\\uD83C\\uDFFC" to "鞠躬, 中等-浅肤色",
                "\\uD83D\\uDE47\\uD83C\\uDFFD" to "鞠躬, 中等肤色",
                "\\uD83D\\uDE47\\uD83C\\uDFFE" to "鞠躬, 中等-深肤色",
                "\\uD83D\\uDE47\\uD83C\\uDFFF" to "鞠躬, 较深肤色",
                "\\uD83E\\uDD26\\uD83C\\uDFFB" to "捂脸, 较浅肤色",
                "\\uD83E\\uDD26\\uD83C\\uDFFC" to "捂脸, 中等-浅肤色",
                "\\uD83E\\uDD26\\uD83C\\uDFFD" to "捂脸, 中等肤色",
                "\\uD83E\\uDD26\\uD83C\\uDFFE" to "捂脸, 中等-深肤色",
                "\\uD83E\\uDD26\\uD83C\\uDFFF" to "捂脸, 较深肤色",
                "\\uD83E\\uDD37\\uD83C\\uDFFB" to "耸肩, 较浅肤色",
                "\\uD83E\\uDD37\\uD83C\\uDFFC" to "耸肩, 中等-浅肤色",
                "\\uD83E\\uDD37\\uD83C\\uDFFD" to "耸肩, 中等肤色",
                "\\uD83E\\uDD37\\uD83C\\uDFFE" to "耸肩, 中等-深肤色",
                "\\uD83E\\uDD37\\uD83C\\uDFFF" to "耸肩, 较深肤色",
                "\\uD83D\\uDC6E\\uD83C\\uDFFB" to "警察, 较浅肤色",
                "\\uD83D\\uDC6E\\uD83C\\uDFFC" to "警察, 中等-浅肤色",
                "\\uD83D\\uDC6E\\uD83C\\uDFFD" to "警察, 中等肤色",
                "\\uD83D\\uDC6E\\uD83C\\uDFFE" to "警察, 中等-深肤色",
                "\\uD83D\\uDC6E\\uD83C\\uDFFF" to "警察, 较深肤色",
                "\\uD83D\\uDD75\\uFE0F" to "侦探",
                "\\uD83D\\uDD75\\uD83C\\uDFFB" to "侦探, 较浅肤色",
                "\\uD83D\\uDD75\\uD83C\\uDFFC" to "侦探, 中等-浅肤色",
                "\\uD83D\\uDD75\\uD83C\\uDFFD" to "侦探, 中等肤色",
                "\\uD83D\\uDD75\\uD83C\\uDFFE" to "侦探, 中等-深肤色",
                "\\uD83D\\uDD75\\uD83C\\uDFFF" to "侦探, 较深肤色",
                "\\uD83D\\uDC82\\uD83C\\uDFFB" to "卫兵, 较浅肤色",
                "\\uD83D\\uDC82\\uD83C\\uDFFC" to "卫兵, 中等-浅肤色",
                "\\uD83D\\uDC82\\uD83C\\uDFFD" to "卫兵, 中等肤色",
                "\\uD83D\\uDC82\\uD83C\\uDFFE" to "卫兵, 中等-深肤色",
                "\\uD83D\\uDC82\\uD83C\\uDFFF" to "卫兵, 较深肤色",
                "\\uD83E\\uDD77\\uD83C\\uDFFB" to "忍者, 较浅肤色",
                "\\uD83E\\uDD77\\uD83C\\uDFFC" to "忍者, 中等-浅肤色",
                "\\uD83E\\uDD77\\uD83C\\uDFFD" to "忍者, 中等肤色",
                "\\uD83E\\uDD77\\uD83C\\uDFFE" to "忍者, 中等-深肤色",
                "\\uD83E\\uDD77\\uD83C\\uDFFF" to "忍者, 较深肤色",
                "\\uD83D\\uDC77\\uD83C\\uDFFB" to "建筑工人, 较浅肤色",
                "\\uD83D\\uDC77\\uD83C\\uDFFC" to "建筑工人, 中等-浅肤色",
                "\\uD83D\\uDC77\\uD83C\\uDFFD" to "建筑工人, 中等肤色",
                "\\uD83D\\uDC77\\uD83C\\uDFFE" to "建筑工人, 中等-深肤色",
                "\\uD83D\\uDC77\\uD83C\\uDFFF" to "建筑工人, 较深肤色",
                "\\uD83E\\uDEC5\\uD83C\\uDFFB" to "戴王冠的人, 较浅肤色",
                "\\uD83E\\uDEC5\\uD83C\\uDFFC" to "戴王冠的人, 中等-浅肤色",
                "\\uD83E\\uDEC5\\uD83C\\uDFFD" to "戴王冠的人, 中等肤色",
                "\\uD83E\\uDEC5\\uD83C\\uDFFE" to "戴王冠的人, 中等-深肤色",
                "\\uD83E\\uDEC5\\uD83C\\uDFFF" to "戴王冠的人, 较深肤色",
                "\\uD83E\\uDD34\\uD83C\\uDFFB" to "王子, 较浅肤色",
                "\\uD83E\\uDD34\\uD83C\\uDFFC" to "王子, 中等-浅肤色",
                "\\uD83E\\uDD34\\uD83C\\uDFFD" to "王子, 中等肤色",
                "\\uD83E\\uDD34\\uD83C\\uDFFE" to "王子, 中等-深肤色",
                "\\uD83E\\uDD34\\uD83C\\uDFFF" to "王子, 较深肤色",
                "\\uD83D\\uDC78\\uD83C\\uDFFB" to "公主, 较浅肤色",
                "\\uD83D\\uDC78\\uD83C\\uDFFC" to "公主, 中等-浅肤色",
                "\\uD83D\\uDC78\\uD83C\\uDFFD" to "公主, 中等肤色",
                "\\uD83D\\uDC78\\uD83C\\uDFFE" to "公主, 中等-深肤色",
                "\\uD83D\\uDC78\\uD83C\\uDFFF" to "公主, 较深肤色",
                "\\uD83D\\uDC73\\uD83C\\uDFFB" to "戴头巾的人, 较浅肤色",
                "\\uD83D\\uDC73\\uD83C\\uDFFC" to "戴头巾的人, 中等-浅肤色",
                "\\uD83D\\uDC73\\uD83C\\uDFFD" to "戴头巾的人, 中等肤色",
                "\\uD83D\\uDC73\\uD83C\\uDFFE" to "戴头巾的人, 中等-深肤色",
                "\\uD83D\\uDC73\\uD83C\\uDFFF" to "戴头巾的人, 较深肤色",
                "\\uD83D\\uDC72\\uD83C\\uDFFB" to "戴瓜皮帽的人, 较浅肤色",
                "\\uD83D\\uDC72\\uD83C\\uDFFC" to "戴瓜皮帽的人, 中等-浅肤色",
                "\\uD83D\\uDC72\\uD83C\\uDFFD" to "戴瓜皮帽的人, 中等肤色",
                "\\uD83D\\uDC72\\uD83C\\uDFFE" to "戴瓜皮帽的人, 中等-深肤色",
                "\\uD83D\\uDC72\\uD83C\\uDFFF" to "戴瓜皮帽的人, 较深肤色",
                "\\uD83E\\uDDD5\\uD83C\\uDFFB" to "带头饰的女人, 较浅肤色",
                "\\uD83E\\uDDD5\\uD83C\\uDFFC" to "带头饰的女人, 中等-浅肤色",
                "\\uD83E\\uDDD5\\uD83C\\uDFFD" to "带头饰的女人, 中等肤色",
                "\\uD83E\\uDDD5\\uD83C\\uDFFE" to "带头饰的女人, 中等-深肤色",
                "\\uD83E\\uDDD5\\uD83C\\uDFFF" to "带头饰的女人, 较深肤色",
                "\\uD83E\\uDD35\\uD83C\\uDFFB" to "穿燕尾服的人, 较浅肤色",
                "\\uD83E\\uDD35\\uD83C\\uDFFC" to "穿燕尾服的人, 中等-浅肤色",
                "\\uD83E\\uDD35\\uD83C\\uDFFD" to "穿燕尾服的人, 中等肤色",
                "\\uD83E\\uDD35\\uD83C\\uDFFE" to "穿燕尾服的人, 中等-深肤色",
                "\\uD83E\\uDD35\\uD83C\\uDFFF" to "穿燕尾服的人, 较深肤色",
                "\\uD83D\\uDC70\\uD83C\\uDFFB" to "戴头纱的人, 较浅肤色",
                "\\uD83D\\uDC70\\uD83C\\uDFFC" to "戴头纱的人, 中等-浅肤色",
                "\\uD83D\\uDC70\\uD83C\\uDFFD" to "戴头纱的人, 中等肤色",
                "\\uD83D\\uDC70\\uD83C\\uDFFE" to "戴头纱的人, 中等-深肤色",
                "\\uD83D\\uDC70\\uD83C\\uDFFF" to "戴头纱的人, 较深肤色",
                "\\uD83E\\uDD30\\uD83C\\uDFFB" to "孕妇, 较浅肤色",
                "\\uD83E\\uDD30\\uD83C\\uDFFC" to "孕妇, 中等-浅肤色",
                "\\uD83E\\uDD30\\uD83C\\uDFFD" to "孕妇, 中等肤色",
                "\\uD83E\\uDD30\\uD83C\\uDFFE" to "孕妇, 中等-深肤色",
                "\\uD83E\\uDD30\\uD83C\\uDFFF" to "孕妇, 较深肤色",
                "\\uD83E\\uDEC3\\uD83C\\uDFFB" to "怀孕的男人, 较浅肤色",
                "\\uD83E\\uDEC3\\uD83C\\uDFFC" to "怀孕的男人, 中等-浅肤色",
                "\\uD83E\\uDEC3\\uD83C\\uDFFD" to "怀孕的男人, 中等肤色",
                "\\uD83E\\uDEC3\\uD83C\\uDFFE" to "怀孕的男人, 中等-深肤色",
                "\\uD83E\\uDEC3\\uD83C\\uDFFF" to "怀孕的男人, 较深肤色",
                "\\uD83E\\uDEC4\\uD83C\\uDFFB" to "怀孕的人, 较浅肤色",
                "\\uD83E\\uDEC4\\uD83C\\uDFFC" to "怀孕的人, 中等-浅肤色",
                "\\uD83E\\uDEC4\\uD83C\\uDFFD" to "怀孕的人, 中等肤色",
                "\\uD83E\\uDEC4\\uD83C\\uDFFE" to "怀孕的人, 中等-深肤色",
                "\\uD83E\\uDEC4\\uD83C\\uDFFF" to "怀孕的人, 较深肤色",
                "\\uD83E\\uDD31\\uD83C\\uDFFB" to "母乳喂养, 较浅肤色",
                "\\uD83E\\uDD31\\uD83C\\uDFFC" to "母乳喂养, 中等-浅肤色",
                "\\uD83E\\uDD31\\uD83C\\uDFFD" to "母乳喂养, 中等肤色",
                "\\uD83E\\uDD31\\uD83C\\uDFFE" to "母乳喂养, 中等-深肤色",
                "\\uD83E\\uDD31\\uD83C\\uDFFF" to "母乳喂养, 较深肤色",
                "\\uD83D\\uDC7C\\uD83C\\uDFFB" to "小天使, 较浅肤色",
                "\\uD83D\\uDC7C\\uD83C\\uDFFC" to "小天使, 中等-浅肤色",
                "\\uD83D\\uDC7C\\uD83C\\uDFFD" to "小天使, 中等肤色",
                "\\uD83D\\uDC7C\\uD83C\\uDFFE" to "小天使, 中等-深肤色",
                "\\uD83D\\uDC7C\\uD83C\\uDFFF" to "小天使, 较深肤色",
                "\\uD83C\\uDF85\\uD83C\\uDFFB" to "圣诞老人, 较浅肤色",
                "\\uD83C\\uDF85\\uD83C\\uDFFC" to "圣诞老人, 中等-浅肤色",
                "\\uD83C\\uDF85\\uD83C\\uDFFD" to "圣诞老人, 中等肤色",
                "\\uD83C\\uDF85\\uD83C\\uDFFE" to "圣诞老人, 中等-深肤色",
                "\\uD83C\\uDF85\\uD83C\\uDFFF" to "圣诞老人, 较深肤色",
                "\\uD83E\\uDD36\\uD83C\\uDFFB" to "圣诞奶奶, 较浅肤色",
                "\\uD83E\\uDD36\\uD83C\\uDFFC" to "圣诞奶奶, 中等-浅肤色",
                "\\uD83E\\uDD36\\uD83C\\uDFFD" to "圣诞奶奶, 中等肤色",
                "\\uD83E\\uDD36\\uD83C\\uDFFE" to "圣诞奶奶, 中等-深肤色",
                "\\uD83E\\uDD36\\uD83C\\uDFFF" to "圣诞奶奶, 较深肤色",
                "\\uD83E\\uDDB8\\uD83C\\uDFFB" to "超级英雄, 较浅肤色",
                "\\uD83E\\uDDB8\\uD83C\\uDFFC" to "超级英雄, 中等-浅肤色",
                "\\uD83E\\uDDB8\\uD83C\\uDFFD" to "超级英雄, 中等肤色",
                "\\uD83E\\uDDB8\\uD83C\\uDFFE" to "超级英雄, 中等-深肤色",
                "\\uD83E\\uDDB8\\uD83C\\uDFFF" to "超级英雄, 较深肤色",
                "\\uD83E\\uDDB9\\uD83C\\uDFFB" to "超级大坏蛋, 较浅肤色",
                "\\uD83E\\uDDB9\\uD83C\\uDFFC" to "超级大坏蛋, 中等-浅肤色",
                "\\uD83E\\uDDB9\\uD83C\\uDFFD" to "超级大坏蛋, 中等肤色",
                "\\uD83E\\uDDB9\\uD83C\\uDFFE" to "超级大坏蛋, 中等-深肤色",
                "\\uD83E\\uDDB9\\uD83C\\uDFFF" to "超级大坏蛋, 较深肤色",
                "\\uD83E\\uDDD9\\uD83C\\uDFFB" to "法师, 较浅肤色",
                "\\uD83E\\uDDD9\\uD83C\\uDFFC" to "法师, 中等-浅肤色",
                "\\uD83E\\uDDD9\\uD83C\\uDFFD" to "法师, 中等肤色",
                "\\uD83E\\uDDD9\\uD83C\\uDFFE" to "法师, 中等-深肤色",
                "\\uD83E\\uDDD9\\uD83C\\uDFFF" to "法师, 较深肤色",
                "\\uD83E\\uDDDA\\uD83C\\uDFFB" to "精灵, 较浅肤色",
                "\\uD83E\\uDDDA\\uD83C\\uDFFC" to "精灵, 中等-浅肤色",
                "\\uD83E\\uDDDA\\uD83C\\uDFFD" to "精灵, 中等肤色",
                "\\uD83E\\uDDDA\\uD83C\\uDFFE" to "精灵, 中等-深肤色",
                "\\uD83E\\uDDDA\\uD83C\\uDFFF" to "精灵, 较深肤色",
                "\\uD83E\\uDDDB\\uD83C\\uDFFB" to "吸血鬼, 较浅肤色",
                "\\uD83E\\uDDDB\\uD83C\\uDFFC" to "吸血鬼, 中等-浅肤色",
                "\\uD83E\\uDDDB\\uD83C\\uDFFD" to "吸血鬼, 中等肤色",
                "\\uD83E\\uDDDB\\uD83C\\uDFFE" to "吸血鬼, 中等-深肤色",
                "\\uD83E\\uDDDB\\uD83C\\uDFFF" to "吸血鬼, 较深肤色",
                "\\uD83E\\uDDDC\\uD83C\\uDFFB" to "人鱼, 较浅肤色",
                "\\uD83E\\uDDDC\\uD83C\\uDFFC" to "人鱼, 中等-浅肤色",
                "\\uD83E\\uDDDC\\uD83C\\uDFFD" to "人鱼, 中等肤色",
                "\\uD83E\\uDDDC\\uD83C\\uDFFE" to "人鱼, 中等-深肤色",
                "\\uD83E\\uDDDC\\uD83C\\uDFFF" to "人鱼, 较深肤色",
                "\\uD83E\\uDDDD\\uD83C\\uDFFB" to "小精灵, 较浅肤色",
                "\\uD83E\\uDDDD\\uD83C\\uDFFC" to "小精灵, 中等-浅肤色",
                "\\uD83E\\uDDDD\\uD83C\\uDFFD" to "小精灵, 中等肤色",
                "\\uD83E\\uDDDD\\uD83C\\uDFFE" to "小精灵, 中等-深肤色",
                "\\uD83E\\uDDDD\\uD83C\\uDFFF" to "小精灵, 较深肤色",
                "\\uD83D\\uDC86\\uD83C\\uDFFB" to "按摩, 较浅肤色",
                "\\uD83D\\uDC86\\uD83C\\uDFFC" to "按摩, 中等-浅肤色",
                "\\uD83D\\uDC86\\uD83C\\uDFFD" to "按摩, 中等肤色",
                "\\uD83D\\uDC86\\uD83C\\uDFFE" to "按摩, 中等-深肤色",
                "\\uD83D\\uDC86\\uD83C\\uDFFF" to "按摩, 较深肤色",
                "\\uD83D\\uDC87\\uD83C\\uDFFB" to "理发, 较浅肤色",
                "\\uD83D\\uDC87\\uD83C\\uDFFC" to "理发, 中等-浅肤色",
                "\\uD83D\\uDC87\\uD83C\\uDFFD" to "理发, 中等肤色",
                "\\uD83D\\uDC87\\uD83C\\uDFFE" to "理发, 中等-深肤色",
                "\\uD83D\\uDC87\\uD83C\\uDFFF" to "理发, 较深肤色",
                "\\uD83D\\uDEB6\\uD83C\\uDFFB" to "行人, 较浅肤色",
                "\\uD83D\\uDEB6\\uD83C\\uDFFC" to "行人, 中等-浅肤色",
                "\\uD83D\\uDEB6\\uD83C\\uDFFD" to "行人, 中等肤色",
                "\\uD83D\\uDEB6\\uD83C\\uDFFE" to "行人, 中等-深肤色",
                "\\uD83D\\uDEB6\\uD83C\\uDFFF" to "行人, 较深肤色",
                "\\uD83E\\uDDCD\\uD83C\\uDFFB" to "站立者, 较浅肤色",
                "\\uD83E\\uDDCD\\uD83C\\uDFFC" to "站立者, 中等-浅肤色",
                "\\uD83E\\uDDCD\\uD83C\\uDFFD" to "站立者, 中等肤色",
                "\\uD83E\\uDDCD\\uD83C\\uDFFE" to "站立者, 中等-深肤色",
                "\\uD83E\\uDDCD\\uD83C\\uDFFF" to "站立者, 较深肤色",
                "\\uD83E\\uDDCE\\uD83C\\uDFFB" to "下跪者, 较浅肤色",
                "\\uD83E\\uDDCE\\uD83C\\uDFFC" to "下跪者, 中等-浅肤色",
                "\\uD83E\\uDDCE\\uD83C\\uDFFD" to "下跪者, 中等肤色",
                "\\uD83E\\uDDCE\\uD83C\\uDFFE" to "下跪者, 中等-深肤色",
                "\\uD83E\\uDDCE\\uD83C\\uDFFF" to "下跪者, 较深肤色",
                "\\uD83C\\uDFC3\\uD83C\\uDFFB" to "跑步者, 较浅肤色",
                "\\uD83C\\uDFC3\\uD83C\\uDFFC" to "跑步者, 中等-浅肤色",
                "\\uD83C\\uDFC3\\uD83C\\uDFFD" to "跑步者, 中等肤色",
                "\\uD83C\\uDFC3\\uD83C\\uDFFE" to "跑步者, 中等-深肤色",
                "\\uD83C\\uDFC3\\uD83C\\uDFFF" to "跑步者, 较深肤色",
                "\\uD83D\\uDC83\\uD83C\\uDFFB" to "跳舞的女人, 较浅肤色",
                "\\uD83D\\uDC83\\uD83C\\uDFFC" to "跳舞的女人, 中等-浅肤色",
                "\\uD83D\\uDC83\\uD83C\\uDFFD" to "跳舞的女人, 中等肤色",
                "\\uD83D\\uDC83\\uD83C\\uDFFE" to "跳舞的女人, 中等-深肤色",
                "\\uD83D\\uDC83\\uD83C\\uDFFF" to "跳舞的女人, 较深肤色",
                "\\uD83D\\uDD7A\\uD83C\\uDFFB" to "跳舞的男人, 较浅肤色",
                "\\uD83D\\uDD7A\\uD83C\\uDFFC" to "跳舞的男人, 中等-浅肤色",
                "\\uD83D\\uDD7A\\uD83C\\uDFFD" to "跳舞的男人, 中等肤色",
                "\\uD83D\\uDD7A\\uD83C\\uDFFE" to "跳舞的男人, 中等-深肤色",
                "\\uD83D\\uDD7A\\uD83C\\uDFFF" to "跳舞的男人, 较深肤色",
                "\\uD83D\\uDD74\\uFE0F" to "西装革履的人",
                "\\uD83D\\uDD74\\uD83C\\uDFFB" to "西装革履的人, 较浅肤色",
                "\\uD83D\\uDD74\\uD83C\\uDFFC" to "西装革履的人, 中等-浅肤色",
                "\\uD83D\\uDD74\\uD83C\\uDFFD" to "西装革履的人, 中等肤色",
                "\\uD83D\\uDD74\\uD83C\\uDFFE" to "西装革履的人, 中等-深肤色",
                "\\uD83D\\uDD74\\uD83C\\uDFFF" to "西装革履的人, 较深肤色",
                "\\uD83D\\uDC6F\\uD83C\\uDFFB" to "戴兔耳朵的人, 较浅肤色",
                "\\uD83D\\uDC6F\\uD83C\\uDFFC" to "戴兔耳朵的人, 中等-浅肤色",
                "\\uD83D\\uDC6F\\uD83C\\uDFFD" to "戴兔耳朵的人, 中等肤色",
                "\\uD83D\\uDC6F\\uD83C\\uDFFE" to "戴兔耳朵的人, 中等-深肤色",
                "\\uD83D\\uDC6F\\uD83C\\uDFFF" to "戴兔耳朵的人, 较深肤色",
                "\\uD83E\\uDDD6\\uD83C\\uDFFB" to "蒸房里的人, 较浅肤色",
                "\\uD83E\\uDDD6\\uD83C\\uDFFC" to "蒸房里的人, 中等-浅肤色",
                "\\uD83E\\uDDD6\\uD83C\\uDFFD" to "蒸房里的人, 中等肤色",
                "\\uD83E\\uDDD6\\uD83C\\uDFFE" to "蒸房里的人, 中等-深肤色",
                "\\uD83E\\uDDD6\\uD83C\\uDFFF" to "蒸房里的人, 较深肤色",
                "\\uD83E\\uDDD7\\uD83C\\uDFFB" to "攀爬的人, 较浅肤色",
                "\\uD83E\\uDDD7\\uD83C\\uDFFC" to "攀爬的人, 中等-浅肤色",
                "\\uD83E\\uDDD7\\uD83C\\uDFFD" to "攀爬的人, 中等肤色",
                "\\uD83E\\uDDD7\\uD83C\\uDFFE" to "攀爬的人, 中等-深肤色",
                "\\uD83E\\uDDD7\\uD83C\\uDFFF" to "攀爬的人, 较深肤色",
                "\\uD83C\\uDFC7\\uD83C\\uDFFB" to "赛马, 较浅肤色",
                "\\uD83C\\uDFC7\\uD83C\\uDFFC" to "赛马, 中等-浅肤色",
                "\\uD83C\\uDFC7\\uD83C\\uDFFD" to "赛马, 中等肤色",
                "\\uD83C\\uDFC7\\uD83C\\uDFFE" to "赛马, 中等-深肤色",
                "\\uD83C\\uDFC7\\uD83C\\uDFFF" to "赛马, 较深肤色",
                "\\u26F7\\uFE0F" to "滑雪的人",
                "\\uD83C\\uDFC2\\uD83C\\uDFFB" to "滑雪板, 较浅肤色",
                "\\uD83C\\uDFC2\\uD83C\\uDFFC" to "滑雪板, 中等-浅肤色",
                "\\uD83C\\uDFC2\\uD83C\\uDFFD" to "滑雪板, 中等肤色",
                "\\uD83C\\uDFC2\\uD83C\\uDFFE" to "滑雪板, 中等-深肤色",
                "\\uD83C\\uDFC2\\uD83C\\uDFFF" to "滑雪板, 较深肤色",
                "\\uD83C\\uDFCC\\uFE0F" to "打高尔夫的人",
                "\\uD83C\\uDFCC\\uD83C\\uDFFB" to "打高尔夫的人, 较浅肤色",
                "\\uD83C\\uDFCC\\uD83C\\uDFFC" to "打高尔夫的人, 中等-浅肤色",
                "\\uD83C\\uDFCC\\uD83C\\uDFFD" to "打高尔夫的人, 中等肤色",
                "\\uD83C\\uDFCC\\uD83C\\uDFFE" to "打高尔夫的人, 中等-深肤色",
                "\\uD83C\\uDFCC\\uD83C\\uDFFF" to "打高尔夫的人, 较深肤色",
                "\\uD83C\\uDFC4\\uD83C\\uDFFB" to "冲浪, 较浅肤色",
                "\\uD83C\\uDFC4\\uD83C\\uDFFC" to "冲浪, 中等-浅肤色",
                "\\uD83C\\uDFC4\\uD83C\\uDFFD" to "冲浪, 中等肤色",
                "\\uD83C\\uDFC4\\uD83C\\uDFFE" to "冲浪, 中等-深肤色",
                "\\uD83C\\uDFC4\\uD83C\\uDFFF" to "冲浪, 较深肤色",
                "\\uD83D\\uDEA3\\uD83C\\uDFFB" to "划艇, 较浅肤色",
                "\\uD83D\\uDEA3\\uD83C\\uDFFC" to "划艇, 中等-浅肤色",
                "\\uD83D\\uDEA3\\uD83C\\uDFFD" to "划艇, 中等肤色",
                "\\uD83D\\uDEA3\\uD83C\\uDFFE" to "划艇, 中等-深肤色",
                "\\uD83D\\uDEA3\\uD83C\\uDFFF" to "划艇, 较深肤色",
                "\\uD83C\\uDFCA\\uD83C\\uDFFB" to "游泳, 较浅肤色",
                "\\uD83C\\uDFCA\\uD83C\\uDFFC" to "游泳, 中等-浅肤色",
                "\\uD83C\\uDFCA\\uD83C\\uDFFD" to "游泳, 中等肤色",
                "\\uD83C\\uDFCA\\uD83C\\uDFFE" to "游泳, 中等-深肤色",
                "\\uD83C\\uDFCA\\uD83C\\uDFFF" to "游泳, 较深肤色",
                "\\u26F9\\uFE0F" to "玩球",
                "\\u26F9\\uD83C\\uDFFB" to "玩球, 较浅肤色",
                "\\u26F9\\uD83C\\uDFFC" to "玩球, 中等-浅肤色",
                "\\u26F9\\uD83C\\uDFFD" to "玩球, 中等肤色",
                "\\u26F9\\uD83C\\uDFFE" to "玩球, 中等-深肤色",
                "\\u26F9\\uD83C\\uDFFF" to "玩球, 较深肤色",
                "\\uD83C\\uDFCB\\uFE0F" to "举重",
                "\\uD83C\\uDFCB\\uD83C\\uDFFB" to "举重, 较浅肤色",
                "\\uD83C\\uDFCB\\uD83C\\uDFFC" to "举重, 中等-浅肤色",
                "\\uD83C\\uDFCB\\uD83C\\uDFFD" to "举重, 中等肤色",
                "\\uD83C\\uDFCB\\uD83C\\uDFFE" to "举重, 中等-深肤色",
                "\\uD83C\\uDFCB\\uD83C\\uDFFF" to "举重, 较深肤色",
                "\\uD83D\\uDEB4\\uD83C\\uDFFB" to "骑自行车, 较浅肤色",
                "\\uD83D\\uDEB4\\uD83C\\uDFFC" to "骑自行车, 中等-浅肤色",
                "\\uD83D\\uDEB4\\uD83C\\uDFFD" to "骑自行车, 中等肤色",
                "\\uD83D\\uDEB4\\uD83C\\uDFFE" to "骑自行车, 中等-深肤色",
                "\\uD83D\\uDEB4\\uD83C\\uDFFF" to "骑自行车, 较深肤色",
                "\\uD83D\\uDEB5\\uD83C\\uDFFB" to "骑山地车, 较浅肤色",
                "\\uD83D\\uDEB5\\uD83C\\uDFFC" to "骑山地车, 中等-浅肤色",
                "\\uD83D\\uDEB5\\uD83C\\uDFFD" to "骑山地车, 中等肤色",
                "\\uD83D\\uDEB5\\uD83C\\uDFFE" to "骑山地车, 中等-深肤色",
                "\\uD83D\\uDEB5\\uD83C\\uDFFF" to "骑山地车, 较深肤色",
                "\\uD83E\\uDD38\\uD83C\\uDFFB" to "侧手翻, 较浅肤色",
                "\\uD83E\\uDD38\\uD83C\\uDFFC" to "侧手翻, 中等-浅肤色",
                "\\uD83E\\uDD38\\uD83C\\uDFFD" to "侧手翻, 中等肤色",
                "\\uD83E\\uDD38\\uD83C\\uDFFE" to "侧手翻, 中等-深肤色",
                "\\uD83E\\uDD38\\uD83C\\uDFFF" to "侧手翻, 较深肤色",
                "\\uD83E\\uDD3C\\uD83C\\uDFFB" to "摔跤选手, 较浅肤色",
                "\\uD83E\\uDD3C\\uD83C\\uDFFC" to "摔跤选手, 中等-浅肤色",
                "\\uD83E\\uDD3C\\uD83C\\uDFFD" to "摔跤选手, 中等肤色",
                "\\uD83E\\uDD3C\\uD83C\\uDFFE" to "摔跤选手, 中等-深肤色",
                "\\uD83E\\uDD3C\\uD83C\\uDFFF" to "摔跤选手, 较深肤色",
                "\\uD83E\\uDD3D\\uD83C\\uDFFB" to "水球, 较浅肤色",
                "\\uD83E\\uDD3D\\uD83C\\uDFFC" to "水球, 中等-浅肤色",
                "\\uD83E\\uDD3D\\uD83C\\uDFFD" to "水球, 中等肤色",
                "\\uD83E\\uDD3D\\uD83C\\uDFFE" to "水球, 中等-深肤色",
                "\\uD83E\\uDD3D\\uD83C\\uDFFF" to "水球, 较深肤色",
                "\\uD83E\\uDD3E\\uD83C\\uDFFB" to "手球, 较浅肤色",
                "\\uD83E\\uDD3E\\uD83C\\uDFFC" to "手球, 中等-浅肤色",
                "\\uD83E\\uDD3E\\uD83C\\uDFFD" to "手球, 中等肤色",
                "\\uD83E\\uDD3E\\uD83C\\uDFFE" to "手球, 中等-深肤色",
                "\\uD83E\\uDD3E\\uD83C\\uDFFF" to "手球, 较深肤色",
                "\\uD83E\\uDD39\\uD83C\\uDFFB" to "抛接杂耍, 较浅肤色",
                "\\uD83E\\uDD39\\uD83C\\uDFFC" to "抛接杂耍, 中等-浅肤色",
                "\\uD83E\\uDD39\\uD83C\\uDFFD" to "抛接杂耍, 中等肤色",
                "\\uD83E\\uDD39\\uD83C\\uDFFE" to "抛接杂耍, 中等-深肤色",
                "\\uD83E\\uDD39\\uD83C\\uDFFF" to "抛接杂耍, 较深肤色",
                "\\uD83E\\uDDD8\\uD83C\\uDFFB" to "盘腿的人, 较浅肤色",
                "\\uD83E\\uDDD8\\uD83C\\uDFFC" to "盘腿的人, 中等-浅肤色",
                "\\uD83E\\uDDD8\\uD83C\\uDFFD" to "盘腿的人, 中等肤色",
                "\\uD83E\\uDDD8\\uD83C\\uDFFE" to "盘腿的人, 中等-深肤色",
                "\\uD83E\\uDDD8\\uD83C\\uDFFF" to "盘腿的人, 较深肤色",
                "\\uD83D\\uDEC0\\uD83C\\uDFFB" to "洗澡的人, 较浅肤色",
                "\\uD83D\\uDEC0\\uD83C\\uDFFC" to "洗澡的人, 中等-浅肤色",
                "\\uD83D\\uDEC0\\uD83C\\uDFFD" to "洗澡的人, 中等肤色",
                "\\uD83D\\uDEC0\\uD83C\\uDFFE" to "洗澡的人, 中等-深肤色",
                "\\uD83D\\uDEC0\\uD83C\\uDFFF" to "洗澡的人, 较深肤色",
                "\\uD83D\\uDECC\\uD83C\\uDFFB" to "躺在床上的人, 较浅肤色",
                "\\uD83D\\uDECC\\uD83C\\uDFFC" to "躺在床上的人, 中等-浅肤色",
                "\\uD83D\\uDECC\\uD83C\\uDFFD" to "躺在床上的人, 中等肤色",
                "\\uD83D\\uDECC\\uD83C\\uDFFE" to "躺在床上的人, 中等-深肤色",
                "\\uD83D\\uDECC\\uD83C\\uDFFF" to "躺在床上的人, 较深肤色",
                "\\uD83D\\uDC6D\\uD83C\\uDFFB" to "手拉手的两个女人, 较浅肤色",
                "\\uD83D\\uDC6D\\uD83C\\uDFFC" to "手拉手的两个女人, 中等-浅肤色",
                "\\uD83D\\uDC6D\\uD83C\\uDFFD" to "手拉手的两个女人, 中等肤色",
                "\\uD83D\\uDC6D\\uD83C\\uDFFE" to "手拉手的两个女人, 中等-深肤色",
                "\\uD83D\\uDC6D\\uD83C\\uDFFF" to "手拉手的两个女人, 较深肤色",
                "\\uD83D\\uDC6B\\uD83C\\uDFFB" to "手拉手的一男一女, 较浅肤色",
                "\\uD83D\\uDC6B\\uD83C\\uDFFC" to "手拉手的一男一女, 中等-浅肤色",
                "\\uD83D\\uDC6B\\uD83C\\uDFFD" to "手拉手的一男一女, 中等肤色",
                "\\uD83D\\uDC6B\\uD83C\\uDFFE" to "手拉手的一男一女, 中等-深肤色",
                "\\uD83D\\uDC6B\\uD83C\\uDFFF" to "手拉手的一男一女, 较深肤色",
                "\\uD83D\\uDC6C\\uD83C\\uDFFB" to "手拉手的两个男人, 较浅肤色",
                "\\uD83D\\uDC6C\\uD83C\\uDFFC" to "手拉手的两个男人, 中等-浅肤色",
                "\\uD83D\\uDC6C\\uD83C\\uDFFD" to "手拉手的两个男人, 中等肤色",
                "\\uD83D\\uDC6C\\uD83C\\uDFFE" to "手拉手的两个男人, 中等-深肤色",
                "\\uD83D\\uDC6C\\uD83C\\uDFFF" to "手拉手的两个男人, 较深肤色",
                "\\uD83D\\uDC8F\\uD83C\\uDFFB" to "亲吻, 较浅肤色",
                "\\uD83D\\uDC8F\\uD83C\\uDFFC" to "亲吻, 中等-浅肤色",
                "\\uD83D\\uDC8F\\uD83C\\uDFFD" to "亲吻, 中等肤色",
                "\\uD83D\\uDC8F\\uD83C\\uDFFE" to "亲吻, 中等-深肤色",
                "\\uD83D\\uDC8F\\uD83C\\uDFFF" to "亲吻, 较深肤色",
                "\\uD83D\\uDC91\\uD83C\\uDFFB" to "情侣, 较浅肤色",
                "\\uD83D\\uDC91\\uD83C\\uDFFC" to "情侣, 中等-浅肤色",
                "\\uD83D\\uDC91\\uD83C\\uDFFD" to "情侣, 中等肤色",
                "\\uD83D\\uDC91\\uD83C\\uDFFE" to "情侣, 中等-深肤色",
                "\\uD83D\\uDC91\\uD83C\\uDFFF" to "情侣, 较深肤色",
                "\\uD83D\\uDDE3\\uFE0F" to "说话",
                "\\uD83D\\uDC3F\\uFE0F" to "松鼠",
                "\\uD83D\\uDD4A\\uFE0F" to "鸽",
                "\\uD83D\\uDD77\\uFE0F" to "蜘蛛",
                "\\uD83D\\uDD78\\uFE0F" to "蜘蛛网",
                "\\uD83C\\uDFF5\\uFE0F" to "圆形花饰",
                "\\u2618\\uFE0F" to "三叶草",
                "\\uD83C\\uDF36\\uFE0F" to "红辣椒",
                "\\uD83C\\uDF7D\\uFE0F" to "餐具",
                "\\uD83D\\uDDFA\\uFE0F" to "世界地图",
                "\\uD83C\\uDFD4\\uFE0F" to "雪山",
                "\\u26F0\\uFE0F" to "山",
                "\\uD83C\\uDFD5\\uFE0F" to "露营",
                "\\uD83C\\uDFD6\\uFE0F" to "沙滩伞",
                "\\uD83C\\uDFDC\\uFE0F" to "沙漠",
                "\\uD83C\\uDFDD\\uFE0F" to "无人荒岛",
                "\\uD83C\\uDFDE\\uFE0F" to "国家公园",
                "\\uD83C\\uDFDF\\uFE0F" to "体育馆",
                "\\uD83C\\uDFDB\\uFE0F" to "古典建筑",
                "\\uD83C\\uDFD7\\uFE0F" to "建筑施工",
                "\\uD83C\\uDFD8\\uFE0F" to "房屋建筑",
                "\\uD83C\\uDFDA\\uFE0F" to "废墟",
                "\\u26E9\\uFE0F" to "神社",
                "\\uD83C\\uDFD9\\uFE0F" to "城市风光",
                "\\u2668\\uFE0F" to "温泉",
                "\\uD83C\\uDFCE\\uFE0F" to "赛车",
                "\\uD83C\\uDFCD\\uFE0F" to "摩托车",
                "\\uD83D\\uDEE3\\uFE0F" to "高速公路",
                "\\uD83D\\uDEE4\\uFE0F" to "铁轨",
                "\\uD83D\\uDEE2\\uFE0F" to "石油桶",
                "\\uD83D\\uDEF3\\uFE0F" to "客轮",
                "\\u26F4\\uFE0F" to "渡轮",
                "\\uD83D\\uDEE5\\uFE0F" to "摩托艇",
                "\\u2708\\uFE0F" to "飞机",
                "\\uD83D\\uDEE9\\uFE0F" to "小型飞机",
                "\\uD83D\\uDEF0\\uFE0F" to "卫星",
                "\\uD83D\\uDECE\\uFE0F" to "服务铃",
                "\\u23F1\\uFE0F" to "秒表",
                "\\u23F2\\uFE0F" to "定时器",
                "\\uD83D\\uDD70\\uFE0F" to "座钟",
                "\\uD83C\\uDF21\\uFE0F" to "温度计",
                "\\u2600\\uFE0F" to "太阳",
                "\\u2601\\uFE0F" to "云",
                "\\u26C8\\uFE0F" to "雷阵雨",
                "\\uD83C\\uDF24\\uFE0F" to "晴偶有云",
                "\\uD83C\\uDF25\\uFE0F" to "多云",
                "\\uD83C\\uDF26\\uFE0F" to "晴转雨",
                "\\uD83C\\uDF27\\uFE0F" to "下雨",
                "\\uD83C\\uDF28\\uFE0F" to "下雪",
                "\\uD83C\\uDF29\\uFE0F" to "打雷",
                "\\uD83C\\uDF2A\\uFE0F" to "龙卷风",
                "\\uD83C\\uDF2B\\uFE0F" to "雾",
                "\\uD83C\\uDF2C\\uFE0F" to "大风",
                "\\u2602\\uFE0F" to "伞",
                "\\u26F1\\uFE0F" to "阳伞",
                "\\u2744\\uFE0F" to "雪花",
                "\\u2603\\uFE0F" to "雪与雪人",
                "\\u2604\\uFE0F" to "彗星",
                "\\uD83C\\uDF97\\uFE0F" to "提示丝带",
                "\\uD83C\\uDF9F\\uFE0F" to "入场券",
                "\\uD83C\\uDF96\\uFE0F" to "军功章",
                "\\u26F8\\uFE0F" to "滑冰",
                "\\uD83D\\uDD79\\uFE0F" to "游戏操控杆",
                "\\u2660\\uFE0F" to "黑桃",
                "\\u2665\\uFE0F" to "红桃",
                "\\u2666\\uFE0F" to "方片",
                "\\u2663\\uFE0F" to "梅花",
                "\\u265F\\uFE0F" to "兵",
                "\\uD83D\\uDDBC\\uFE0F" to "带框的画",
                "\\uD83D\\uDD76\\uFE0F" to "墨镜",
                "\\uD83D\\uDECD\\uFE0F" to "购物袋",
                "\\u26D1\\uFE0F" to "白十字头盔",
                "\\uD83C\\uDF99\\uFE0F" to "录音室麦克风",
                "\\uD83C\\uDF9A\\uFE0F" to "电平滑块",
                "\\uD83C\\uDF9B\\uFE0F" to "控制旋钮",
                "\\u260E\\uFE0F" to "电话",
                "\\uD83D\\uDDA5\\uFE0F" to "台式电脑",
                "\\uD83D\\uDDA8\\uFE0F" to "打印机",
                "\\u2328\\uFE0F" to "键盘",
                "\\uD83D\\uDDB1\\uFE0F" to "电脑鼠标",
                "\\uD83D\\uDDB2\\uFE0F" to "轨迹球",
                "\\uD83C\\uDF9E\\uFE0F" to "影片帧",
                "\\uD83D\\uDCFD\\uFE0F" to "电影放映机",
                "\\uD83D\\uDD6F\\uFE0F" to "蜡烛",
                "\\uD83D\\uDDDE\\uFE0F" to "报纸卷",
                "\\uD83C\\uDFF7\\uFE0F" to "标签",
                "\\u2709\\uFE0F" to "信封",
                "\\uD83D\\uDDF3\\uFE0F" to "投票箱",
                "\\u270F\\uFE0F" to "铅笔",
                "\\u2712\\uFE0F" to "钢笔尖",
                "\\uD83D\\uDD8B\\uFE0F" to "钢笔",
                "\\uD83D\\uDD8A\\uFE0F" to "笔",
                "\\uD83D\\uDD8C\\uFE0F" to "画笔",
                "\\uD83D\\uDD8D\\uFE0F" to "蜡笔",
                "\\uD83D\\uDDC2\\uFE0F" to "索引分隔文件夹",
                "\\uD83D\\uDDD2\\uFE0F" to "线圈本",
                "\\uD83D\\uDDD3\\uFE0F" to "线圈日历",
                "\\uD83D\\uDD87\\uFE0F" to "连起来的两个回形针",
                "\\u2702\\uFE0F" to "剪刀",
                "\\uD83D\\uDDC3\\uFE0F" to "卡片盒",
                "\\uD83D\\uDDC4\\uFE0F" to "文件柜",
                "\\uD83D\\uDDD1\\uFE0F" to "垃圾桶",
                "\\uD83D\\uDDDD\\uFE0F" to "老式钥匙",
                "\\u26CF\\uFE0F" to "铁镐",
                "\\u2692\\uFE0F" to "锤子与镐",
                "\\uD83D\\uDEE0\\uFE0F" to "锤子与扳手",
                "\\uD83D\\uDDE1\\uFE0F" to "匕首",
                "\\u2694\\uFE0F" to "交叉放置的剑",
                "\\uD83D\\uDEE1\\uFE0F" to "盾牌",
                "\\u2699\\uFE0F" to "齿轮",
                "\\uD83D\\uDDDC\\uFE0F" to "夹钳",
                "\\u2696\\uFE0F" to "天平",
                "\\u26D3\\uFE0F" to "链条",
                "\\u2697\\uFE0F" to "蒸馏器",
                "\\uD83D\\uDECF\\uFE0F" to "床",
                "\\uD83D\\uDECB\\uFE0F" to "沙发和灯",
                "\\u26B0\\uFE0F" to "棺材",
                "\\u26B1\\uFE0F" to "骨灰缸",
                "\\u26A0\\uFE0F" to "警告",
                "\\u2622\\uFE0F" to "辐射",
                "\\u2623\\uFE0F" to "生物危害",
                "\\u2B06\\uFE0F" to "向上箭头",
                "\\u2197\\uFE0F" to "右上箭头",
                "\\u27A1\\uFE0F" to "向右箭头",
                "\\u2198\\uFE0F" to "右下箭头",
                "\\u2B07\\uFE0F" to "向下箭头",
                "\\u2199\\uFE0F" to "左下箭头",
                "\\u2B05\\uFE0F" to "向左箭头",
                "\\u2196\\uFE0F" to "左上箭头",
                "\\u2195\\uFE0F" to "上下箭头",
                "\\u2194\\uFE0F" to "左右箭头",
                "\\u21A9\\uFE0F" to "右转弯箭头",
                "\\u21AA\\uFE0F" to "左转弯箭头",
                "\\u2934\\uFE0F" to "右上弯箭头",
                "\\u2935\\uFE0F" to "右下弯箭头",
                "\\u269B\\uFE0F" to "原子符号",
                "\\uD83D\\uDD49\\uFE0F" to "奥姆",
                "\\u2721\\uFE0F" to "六芒星",
                "\\u2638\\uFE0F" to "法轮",
                "\\u262F\\uFE0F" to "阴阳",
                "\\u271D\\uFE0F" to "十字架",
                "\\u2626\\uFE0F" to "东正教十字架",
                "\\u262A\\uFE0F" to "星月",
                "\\u262E\\uFE0F" to "和平符号",
                "\\u25B6\\uFE0F" to "播放按钮",
                "\\u23ED\\uFE0F" to "下一个音轨按钮",
                "\\u23EF\\uFE0F" to "播放或暂停按钮",
                "\\u25C0\\uFE0F" to "倒退按钮",
)
