package com.xw.vvtts.utils

internal val EMOJI_07: Map<String, String> = mapOf(
                "\\uD83D\\uDE45\\uD83C\\uDFFF" to "person gesturing NO, dark skin tone",
                "\\uD83D\\uDE46\\uD83C\\uDFFB" to "person gesturing OK, light skin tone",
                "\\uD83D\\uDE46\\uD83C\\uDFFC" to "person gesturing OK, medium-light skin tone",
                "\\uD83D\\uDE46\\uD83C\\uDFFD" to "person gesturing OK, medium skin tone",
                "\\uD83D\\uDE46\\uD83C\\uDFFE" to "person gesturing OK, medium-dark skin tone",
                "\\uD83D\\uDE46\\uD83C\\uDFFF" to "person gesturing OK, dark skin tone",
                "\\uD83D\\uDC81\\uD83C\\uDFFB" to "person tipping hand, light skin tone",
                "\\uD83D\\uDC81\\uD83C\\uDFFC" to "person tipping hand, medium-light skin tone",
                "\\uD83D\\uDC81\\uD83C\\uDFFD" to "person tipping hand, medium skin tone",
                "\\uD83D\\uDC81\\uD83C\\uDFFE" to "person tipping hand, medium-dark skin tone",
                "\\uD83D\\uDC81\\uD83C\\uDFFF" to "person tipping hand, dark skin tone",
                "\\uD83D\\uDE4B\\uD83C\\uDFFB" to "person raising hand, light skin tone",
                "\\uD83D\\uDE4B\\uD83C\\uDFFC" to "person raising hand, medium-light skin tone",
                "\\uD83D\\uDE4B\\uD83C\\uDFFD" to "person raising hand, medium skin tone",
                "\\uD83D\\uDE4B\\uD83C\\uDFFE" to "person raising hand, medium-dark skin tone",
                "\\uD83D\\uDE4B\\uD83C\\uDFFF" to "person raising hand, dark skin tone",
                "\\uD83E\\uDDCF\\uD83C\\uDFFB" to "deaf person, light skin tone",
                "\\uD83E\\uDDCF\\uD83C\\uDFFC" to "deaf person, medium-light skin tone",
                "\\uD83E\\uDDCF\\uD83C\\uDFFD" to "deaf person, medium skin tone",
                "\\uD83E\\uDDCF\\uD83C\\uDFFE" to "deaf person, medium-dark skin tone",
                "\\uD83E\\uDDCF\\uD83C\\uDFFF" to "deaf person, dark skin tone",
                "\\uD83D\\uDE47\\uD83C\\uDFFB" to "person bowing, light skin tone",
                "\\uD83D\\uDE47\\uD83C\\uDFFC" to "person bowing, medium-light skin tone",
                "\\uD83D\\uDE47\\uD83C\\uDFFD" to "person bowing, medium skin tone",
                "\\uD83D\\uDE47\\uD83C\\uDFFE" to "person bowing, medium-dark skin tone",
                "\\uD83D\\uDE47\\uD83C\\uDFFF" to "person bowing, dark skin tone",
                "\\uD83E\\uDD26\\uD83C\\uDFFB" to "person facepalming, light skin tone",
                "\\uD83E\\uDD26\\uD83C\\uDFFC" to "person facepalming, medium-light skin tone",
                "\\uD83E\\uDD26\\uD83C\\uDFFD" to "person facepalming, medium skin tone",
                "\\uD83E\\uDD26\\uD83C\\uDFFE" to "person facepalming, medium-dark skin tone",
                "\\uD83E\\uDD26\\uD83C\\uDFFF" to "person facepalming, dark skin tone",
                "\\uD83E\\uDD37\\uD83C\\uDFFB" to "person shrugging, light skin tone",
                "\\uD83E\\uDD37\\uD83C\\uDFFC" to "person shrugging, medium-light skin tone",
                "\\uD83E\\uDD37\\uD83C\\uDFFD" to "person shrugging, medium skin tone",
                "\\uD83E\\uDD37\\uD83C\\uDFFE" to "person shrugging, medium-dark skin tone",
                "\\uD83E\\uDD37\\uD83C\\uDFFF" to "person shrugging, dark skin tone",
                "\\uD83D\\uDC6E\\uD83C\\uDFFB" to "police officer, light skin tone",
                "\\uD83D\\uDC6E\\uD83C\\uDFFC" to "police officer, medium-light skin tone",
                "\\uD83D\\uDC6E\\uD83C\\uDFFD" to "police officer, medium skin tone",
                "\\uD83D\\uDC6E\\uD83C\\uDFFE" to "police officer, medium-dark skin tone",
                "\\uD83D\\uDC6E\\uD83C\\uDFFF" to "police officer, dark skin tone",
                "\\uD83D\\uDD75\\uFE0F" to "detective",
                "\\uD83D\\uDD75\\uD83C\\uDFFB" to "detective, light skin tone",
                "\\uD83D\\uDD75\\uD83C\\uDFFC" to "detective, medium-light skin tone",
                "\\uD83D\\uDD75\\uD83C\\uDFFD" to "detective, medium skin tone",
                "\\uD83D\\uDD75\\uD83C\\uDFFE" to "detective, medium-dark skin tone",
                "\\uD83D\\uDD75\\uD83C\\uDFFF" to "detective, dark skin tone",
                "\\uD83D\\uDC82\\uD83C\\uDFFB" to "guard, light skin tone",
                "\\uD83D\\uDC82\\uD83C\\uDFFC" to "guard, medium-light skin tone",
                "\\uD83D\\uDC82\\uD83C\\uDFFD" to "guard, medium skin tone",
                "\\uD83D\\uDC82\\uD83C\\uDFFE" to "guard, medium-dark skin tone",
                "\\uD83D\\uDC82\\uD83C\\uDFFF" to "guard, dark skin tone",
                "\\uD83E\\uDD77\\uD83C\\uDFFB" to "ninja, light skin tone",
                "\\uD83E\\uDD77\\uD83C\\uDFFC" to "ninja, medium-light skin tone",
                "\\uD83E\\uDD77\\uD83C\\uDFFD" to "ninja, medium skin tone",
                "\\uD83E\\uDD77\\uD83C\\uDFFE" to "ninja, medium-dark skin tone",
                "\\uD83E\\uDD77\\uD83C\\uDFFF" to "ninja, dark skin tone",
                "\\uD83D\\uDC77\\uD83C\\uDFFB" to "construction worker, light skin tone",
                "\\uD83D\\uDC77\\uD83C\\uDFFC" to "construction worker, medium-light skin tone",
                "\\uD83D\\uDC77\\uD83C\\uDFFD" to "construction worker, medium skin tone",
                "\\uD83D\\uDC77\\uD83C\\uDFFE" to "construction worker, medium-dark skin tone",
                "\\uD83D\\uDC77\\uD83C\\uDFFF" to "construction worker, dark skin tone",
                "\\uD83E\\uDEC5\\uD83C\\uDFFB" to "person with crown, light skin tone",
                "\\uD83E\\uDEC5\\uD83C\\uDFFC" to "person with crown, medium-light skin tone",
                "\\uD83E\\uDEC5\\uD83C\\uDFFD" to "person with crown, medium skin tone",
                "\\uD83E\\uDEC5\\uD83C\\uDFFE" to "person with crown, medium-dark skin tone",
                "\\uD83E\\uDEC5\\uD83C\\uDFFF" to "person with crown, dark skin tone",
                "\\uD83E\\uDD34\\uD83C\\uDFFB" to "prince, light skin tone",
                "\\uD83E\\uDD34\\uD83C\\uDFFC" to "prince, medium-light skin tone",
                "\\uD83E\\uDD34\\uD83C\\uDFFD" to "prince, medium skin tone",
                "\\uD83E\\uDD34\\uD83C\\uDFFE" to "prince, medium-dark skin tone",
                "\\uD83E\\uDD34\\uD83C\\uDFFF" to "prince, dark skin tone",
                "\\uD83D\\uDC78\\uD83C\\uDFFB" to "princess, light skin tone",
                "\\uD83D\\uDC78\\uD83C\\uDFFC" to "princess, medium-light skin tone",
                "\\uD83D\\uDC78\\uD83C\\uDFFD" to "princess, medium skin tone",
                "\\uD83D\\uDC78\\uD83C\\uDFFE" to "princess, medium-dark skin tone",
                "\\uD83D\\uDC78\\uD83C\\uDFFF" to "princess, dark skin tone",
                "\\uD83D\\uDC73\\uD83C\\uDFFB" to "person wearing turban, light skin tone",
                "\\uD83D\\uDC73\\uD83C\\uDFFC" to "person wearing turban, medium-light skin tone",
                "\\uD83D\\uDC73\\uD83C\\uDFFD" to "person wearing turban, medium skin tone",
                "\\uD83D\\uDC73\\uD83C\\uDFFE" to "person wearing turban, medium-dark skin tone",
                "\\uD83D\\uDC73\\uD83C\\uDFFF" to "person wearing turban, dark skin tone",
                "\\uD83D\\uDC72\\uD83C\\uDFFB" to "person with skullcap, light skin tone",
                "\\uD83D\\uDC72\\uD83C\\uDFFC" to "person with skullcap, medium-light skin tone",
                "\\uD83D\\uDC72\\uD83C\\uDFFD" to "person with skullcap, medium skin tone",
                "\\uD83D\\uDC72\\uD83C\\uDFFE" to "person with skullcap, medium-dark skin tone",
                "\\uD83D\\uDC72\\uD83C\\uDFFF" to "person with skullcap, dark skin tone",
                "\\uD83E\\uDDD5\\uD83C\\uDFFB" to "woman with headscarf, light skin tone",
                "\\uD83E\\uDDD5\\uD83C\\uDFFC" to "woman with headscarf, medium-light skin tone",
                "\\uD83E\\uDDD5\\uD83C\\uDFFD" to "woman with headscarf, medium skin tone",
                "\\uD83E\\uDDD5\\uD83C\\uDFFE" to "woman with headscarf, medium-dark skin tone",
                "\\uD83E\\uDDD5\\uD83C\\uDFFF" to "woman with headscarf, dark skin tone",
                "\\uD83E\\uDD35\\uD83C\\uDFFB" to "person in tuxedo, light skin tone",
                "\\uD83E\\uDD35\\uD83C\\uDFFC" to "person in tuxedo, medium-light skin tone",
                "\\uD83E\\uDD35\\uD83C\\uDFFD" to "person in tuxedo, medium skin tone",
                "\\uD83E\\uDD35\\uD83C\\uDFFE" to "person in tuxedo, medium-dark skin tone",
                "\\uD83E\\uDD35\\uD83C\\uDFFF" to "person in tuxedo, dark skin tone",
                "\\uD83D\\uDC70\\uD83C\\uDFFB" to "person with veil, light skin tone",
                "\\uD83D\\uDC70\\uD83C\\uDFFC" to "person with veil, medium-light skin tone",
                "\\uD83D\\uDC70\\uD83C\\uDFFD" to "person with veil, medium skin tone",
                "\\uD83D\\uDC70\\uD83C\\uDFFE" to "person with veil, medium-dark skin tone",
                "\\uD83D\\uDC70\\uD83C\\uDFFF" to "person with veil, dark skin tone",
                "\\uD83E\\uDD30\\uD83C\\uDFFB" to "pregnant woman, light skin tone",
                "\\uD83E\\uDD30\\uD83C\\uDFFC" to "pregnant woman, medium-light skin tone",
                "\\uD83E\\uDD30\\uD83C\\uDFFD" to "pregnant woman, medium skin tone",
                "\\uD83E\\uDD30\\uD83C\\uDFFE" to "pregnant woman, medium-dark skin tone",
                "\\uD83E\\uDD30\\uD83C\\uDFFF" to "pregnant woman, dark skin tone",
                "\\uD83E\\uDEC3\\uD83C\\uDFFB" to "pregnant man, light skin tone",
                "\\uD83E\\uDEC3\\uD83C\\uDFFC" to "pregnant man, medium-light skin tone",
                "\\uD83E\\uDEC3\\uD83C\\uDFFD" to "pregnant man, medium skin tone",
                "\\uD83E\\uDEC3\\uD83C\\uDFFE" to "pregnant man, medium-dark skin tone",
                "\\uD83E\\uDEC3\\uD83C\\uDFFF" to "pregnant man, dark skin tone",
                "\\uD83E\\uDEC4\\uD83C\\uDFFB" to "pregnant person, light skin tone",
                "\\uD83E\\uDEC4\\uD83C\\uDFFC" to "pregnant person, medium-light skin tone",
                "\\uD83E\\uDEC4\\uD83C\\uDFFD" to "pregnant person, medium skin tone",
                "\\uD83E\\uDEC4\\uD83C\\uDFFE" to "pregnant person, medium-dark skin tone",
                "\\uD83E\\uDEC4\\uD83C\\uDFFF" to "pregnant person, dark skin tone",
                "\\uD83E\\uDD31\\uD83C\\uDFFB" to "breast-feeding, light skin tone",
                "\\uD83E\\uDD31\\uD83C\\uDFFC" to "breast-feeding, medium-light skin tone",
                "\\uD83E\\uDD31\\uD83C\\uDFFD" to "breast-feeding, medium skin tone",
                "\\uD83E\\uDD31\\uD83C\\uDFFE" to "breast-feeding, medium-dark skin tone",
                "\\uD83E\\uDD31\\uD83C\\uDFFF" to "breast-feeding, dark skin tone",
                "\\uD83D\\uDC7C\\uD83C\\uDFFB" to "baby angel, light skin tone",
                "\\uD83D\\uDC7C\\uD83C\\uDFFC" to "baby angel, medium-light skin tone",
                "\\uD83D\\uDC7C\\uD83C\\uDFFD" to "baby angel, medium skin tone",
                "\\uD83D\\uDC7C\\uD83C\\uDFFE" to "baby angel, medium-dark skin tone",
                "\\uD83D\\uDC7C\\uD83C\\uDFFF" to "baby angel, dark skin tone",
                "\\uD83C\\uDF85\\uD83C\\uDFFB" to "Santa Claus, light skin tone",
                "\\uD83C\\uDF85\\uD83C\\uDFFC" to "Santa Claus, medium-light skin tone",
                "\\uD83C\\uDF85\\uD83C\\uDFFD" to "Santa Claus, medium skin tone",
                "\\uD83C\\uDF85\\uD83C\\uDFFE" to "Santa Claus, medium-dark skin tone",
                "\\uD83C\\uDF85\\uD83C\\uDFFF" to "Santa Claus, dark skin tone",
                "\\uD83E\\uDD36\\uD83C\\uDFFB" to "Mrs. Claus, light skin tone",
                "\\uD83E\\uDD36\\uD83C\\uDFFC" to "Mrs. Claus, medium-light skin tone",
                "\\uD83E\\uDD36\\uD83C\\uDFFD" to "Mrs. Claus, medium skin tone",
                "\\uD83E\\uDD36\\uD83C\\uDFFE" to "Mrs. Claus, medium-dark skin tone",
                "\\uD83E\\uDD36\\uD83C\\uDFFF" to "Mrs. Claus, dark skin tone",
                "\\uD83E\\uDDB8\\uD83C\\uDFFB" to "superhero, light skin tone",
                "\\uD83E\\uDDB8\\uD83C\\uDFFC" to "superhero, medium-light skin tone",
                "\\uD83E\\uDDB8\\uD83C\\uDFFD" to "superhero, medium skin tone",
                "\\uD83E\\uDDB8\\uD83C\\uDFFE" to "superhero, medium-dark skin tone",
                "\\uD83E\\uDDB8\\uD83C\\uDFFF" to "superhero, dark skin tone",
                "\\uD83E\\uDDB9\\uD83C\\uDFFB" to "supervillain, light skin tone",
                "\\uD83E\\uDDB9\\uD83C\\uDFFC" to "supervillain, medium-light skin tone",
                "\\uD83E\\uDDB9\\uD83C\\uDFFD" to "supervillain, medium skin tone",
                "\\uD83E\\uDDB9\\uD83C\\uDFFE" to "supervillain, medium-dark skin tone",
                "\\uD83E\\uDDB9\\uD83C\\uDFFF" to "supervillain, dark skin tone",
                "\\uD83E\\uDDD9\\uD83C\\uDFFB" to "mage, light skin tone",
                "\\uD83E\\uDDD9\\uD83C\\uDFFC" to "mage, medium-light skin tone",
                "\\uD83E\\uDDD9\\uD83C\\uDFFD" to "mage, medium skin tone",
                "\\uD83E\\uDDD9\\uD83C\\uDFFE" to "mage, medium-dark skin tone",
                "\\uD83E\\uDDD9\\uD83C\\uDFFF" to "mage, dark skin tone",
                "\\uD83E\\uDDDA\\uD83C\\uDFFB" to "fairy, light skin tone",
                "\\uD83E\\uDDDA\\uD83C\\uDFFC" to "fairy, medium-light skin tone",
                "\\uD83E\\uDDDA\\uD83C\\uDFFD" to "fairy, medium skin tone",
                "\\uD83E\\uDDDA\\uD83C\\uDFFE" to "fairy, medium-dark skin tone",
                "\\uD83E\\uDDDA\\uD83C\\uDFFF" to "fairy, dark skin tone",
                "\\uD83E\\uDDDB\\uD83C\\uDFFB" to "vampire, light skin tone",
                "\\uD83E\\uDDDB\\uD83C\\uDFFC" to "vampire, medium-light skin tone",
                "\\uD83E\\uDDDB\\uD83C\\uDFFD" to "vampire, medium skin tone",
                "\\uD83E\\uDDDB\\uD83C\\uDFFE" to "vampire, medium-dark skin tone",
                "\\uD83E\\uDDDB\\uD83C\\uDFFF" to "vampire, dark skin tone",
                "\\uD83E\\uDDDC\\uD83C\\uDFFB" to "merperson, light skin tone",
                "\\uD83E\\uDDDC\\uD83C\\uDFFC" to "merperson, medium-light skin tone",
                "\\uD83E\\uDDDC\\uD83C\\uDFFD" to "merperson, medium skin tone",
                "\\uD83E\\uDDDC\\uD83C\\uDFFE" to "merperson, medium-dark skin tone",
                "\\uD83E\\uDDDC\\uD83C\\uDFFF" to "merperson, dark skin tone",
                "\\uD83E\\uDDDD\\uD83C\\uDFFB" to "elf, light skin tone",
                "\\uD83E\\uDDDD\\uD83C\\uDFFC" to "elf, medium-light skin tone",
                "\\uD83E\\uDDDD\\uD83C\\uDFFD" to "elf, medium skin tone",
                "\\uD83E\\uDDDD\\uD83C\\uDFFE" to "elf, medium-dark skin tone",
                "\\uD83E\\uDDDD\\uD83C\\uDFFF" to "elf, dark skin tone",
                "\\uD83D\\uDC86\\uD83C\\uDFFB" to "person getting massage, light skin tone",
                "\\uD83D\\uDC86\\uD83C\\uDFFC" to "person getting massage, medium-light skin tone",
                "\\uD83D\\uDC86\\uD83C\\uDFFD" to "person getting massage, medium skin tone",
                "\\uD83D\\uDC86\\uD83C\\uDFFE" to "person getting massage, medium-dark skin tone",
                "\\uD83D\\uDC86\\uD83C\\uDFFF" to "person getting massage, dark skin tone",
                "\\uD83D\\uDC87\\uD83C\\uDFFB" to "person getting haircut, light skin tone",
                "\\uD83D\\uDC87\\uD83C\\uDFFC" to "person getting haircut, medium-light skin tone",
                "\\uD83D\\uDC87\\uD83C\\uDFFD" to "person getting haircut, medium skin tone",
                "\\uD83D\\uDC87\\uD83C\\uDFFE" to "person getting haircut, medium-dark skin tone",
                "\\uD83D\\uDC87\\uD83C\\uDFFF" to "person getting haircut, dark skin tone",
                "\\uD83D\\uDEB6\\uD83C\\uDFFB" to "person walking, light skin tone",
                "\\uD83D\\uDEB6\\uD83C\\uDFFC" to "person walking, medium-light skin tone",
                "\\uD83D\\uDEB6\\uD83C\\uDFFD" to "person walking, medium skin tone",
                "\\uD83D\\uDEB6\\uD83C\\uDFFE" to "person walking, medium-dark skin tone",
                "\\uD83D\\uDEB6\\uD83C\\uDFFF" to "person walking, dark skin tone",
                "\\uD83E\\uDDCD\\uD83C\\uDFFB" to "person standing, light skin tone",
                "\\uD83E\\uDDCD\\uD83C\\uDFFC" to "person standing, medium-light skin tone",
                "\\uD83E\\uDDCD\\uD83C\\uDFFD" to "person standing, medium skin tone",
                "\\uD83E\\uDDCD\\uD83C\\uDFFE" to "person standing, medium-dark skin tone",
                "\\uD83E\\uDDCD\\uD83C\\uDFFF" to "person standing, dark skin tone",
                "\\uD83E\\uDDCE\\uD83C\\uDFFB" to "person kneeling, light skin tone",
                "\\uD83E\\uDDCE\\uD83C\\uDFFC" to "person kneeling, medium-light skin tone",
                "\\uD83E\\uDDCE\\uD83C\\uDFFD" to "person kneeling, medium skin tone",
                "\\uD83E\\uDDCE\\uD83C\\uDFFE" to "person kneeling, medium-dark skin tone",
                "\\uD83E\\uDDCE\\uD83C\\uDFFF" to "person kneeling, dark skin tone",
                "\\uD83C\\uDFC3\\uD83C\\uDFFB" to "person running, light skin tone",
                "\\uD83C\\uDFC3\\uD83C\\uDFFC" to "person running, medium-light skin tone",
                "\\uD83C\\uDFC3\\uD83C\\uDFFD" to "person running, medium skin tone",
                "\\uD83C\\uDFC3\\uD83C\\uDFFE" to "person running, medium-dark skin tone",
                "\\uD83C\\uDFC3\\uD83C\\uDFFF" to "person running, dark skin tone",
                "\\uD83D\\uDC83\\uD83C\\uDFFB" to "woman dancing, light skin tone",
                "\\uD83D\\uDC83\\uD83C\\uDFFC" to "woman dancing, medium-light skin tone",
                "\\uD83D\\uDC83\\uD83C\\uDFFD" to "woman dancing, medium skin tone",
                "\\uD83D\\uDC83\\uD83C\\uDFFE" to "woman dancing, medium-dark skin tone",
                "\\uD83D\\uDC83\\uD83C\\uDFFF" to "woman dancing, dark skin tone",
                "\\uD83D\\uDD7A\\uD83C\\uDFFB" to "man dancing, light skin tone",
                "\\uD83D\\uDD7A\\uD83C\\uDFFC" to "man dancing, medium-light skin tone",
                "\\uD83D\\uDD7A\\uD83C\\uDFFD" to "man dancing, medium skin tone",
                "\\uD83D\\uDD7A\\uD83C\\uDFFE" to "man dancing, medium-dark skin tone",
                "\\uD83D\\uDD7A\\uD83C\\uDFFF" to "man dancing, dark skin tone",
                "\\uD83D\\uDD74\\uFE0F" to "person in suit levitating",
                "\\uD83D\\uDD74\\uD83C\\uDFFB" to "person in suit levitating, light skin tone",
                "\\uD83D\\uDD74\\uD83C\\uDFFC" to "person in suit levitating, medium-light skin tone",
                "\\uD83D\\uDD74\\uD83C\\uDFFD" to "person in suit levitating, medium skin tone",
                "\\uD83D\\uDD74\\uD83C\\uDFFE" to "person in suit levitating, medium-dark skin tone",
                "\\uD83D\\uDD74\\uD83C\\uDFFF" to "person in suit levitating, dark skin tone",
                "\\uD83D\\uDC6F\\uD83C\\uDFFB" to "people with bunny ears, light skin tone",
                "\\uD83D\\uDC6F\\uD83C\\uDFFC" to "people with bunny ears, medium-light skin tone",
                "\\uD83D\\uDC6F\\uD83C\\uDFFD" to "people with bunny ears, medium skin tone",
                "\\uD83D\\uDC6F\\uD83C\\uDFFE" to "people with bunny ears, medium-dark skin tone",
                "\\uD83D\\uDC6F\\uD83C\\uDFFF" to "people with bunny ears, dark skin tone",
                "\\uD83E\\uDDD6\\uD83C\\uDFFB" to "person in steamy room, light skin tone",
                "\\uD83E\\uDDD6\\uD83C\\uDFFC" to "person in steamy room, medium-light skin tone",
                "\\uD83E\\uDDD6\\uD83C\\uDFFD" to "person in steamy room, medium skin tone",
                "\\uD83E\\uDDD6\\uD83C\\uDFFE" to "person in steamy room, medium-dark skin tone",
                "\\uD83E\\uDDD6\\uD83C\\uDFFF" to "person in steamy room, dark skin tone",
                "\\uD83E\\uDDD7\\uD83C\\uDFFB" to "person climbing, light skin tone",
                "\\uD83E\\uDDD7\\uD83C\\uDFFC" to "person climbing, medium-light skin tone",
                "\\uD83E\\uDDD7\\uD83C\\uDFFD" to "person climbing, medium skin tone",
                "\\uD83E\\uDDD7\\uD83C\\uDFFE" to "person climbing, medium-dark skin tone",
                "\\uD83E\\uDDD7\\uD83C\\uDFFF" to "person climbing, dark skin tone",
                "\\uD83C\\uDFC7\\uD83C\\uDFFB" to "horse racing, light skin tone",
                "\\uD83C\\uDFC7\\uD83C\\uDFFC" to "horse racing, medium-light skin tone",
                "\\uD83C\\uDFC7\\uD83C\\uDFFD" to "horse racing, medium skin tone",
                "\\uD83C\\uDFC7\\uD83C\\uDFFE" to "horse racing, medium-dark skin tone",
                "\\uD83C\\uDFC7\\uD83C\\uDFFF" to "horse racing, dark skin tone",
                "\\u26F7\\uFE0F" to "skier",
                "\\uD83C\\uDFC2\\uD83C\\uDFFB" to "snowboarder, light skin tone",
                "\\uD83C\\uDFC2\\uD83C\\uDFFC" to "snowboarder, medium-light skin tone",
                "\\uD83C\\uDFC2\\uD83C\\uDFFD" to "snowboarder, medium skin tone",
                "\\uD83C\\uDFC2\\uD83C\\uDFFE" to "snowboarder, medium-dark skin tone",
                "\\uD83C\\uDFC2\\uD83C\\uDFFF" to "snowboarder, dark skin tone",
                "\\uD83C\\uDFCC\\uFE0F" to "person golfing",
                "\\uD83C\\uDFCC\\uD83C\\uDFFB" to "person golfing, light skin tone",
                "\\uD83C\\uDFCC\\uD83C\\uDFFC" to "person golfing, medium-light skin tone",
                "\\uD83C\\uDFCC\\uD83C\\uDFFD" to "person golfing, medium skin tone",
                "\\uD83C\\uDFCC\\uD83C\\uDFFE" to "person golfing, medium-dark skin tone",
                "\\uD83C\\uDFCC\\uD83C\\uDFFF" to "person golfing, dark skin tone",
                "\\uD83C\\uDFC4\\uD83C\\uDFFB" to "person surfing, light skin tone",
                "\\uD83C\\uDFC4\\uD83C\\uDFFC" to "person surfing, medium-light skin tone",
                "\\uD83C\\uDFC4\\uD83C\\uDFFD" to "person surfing, medium skin tone",
                "\\uD83C\\uDFC4\\uD83C\\uDFFE" to "person surfing, medium-dark skin tone",
                "\\uD83C\\uDFC4\\uD83C\\uDFFF" to "person surfing, dark skin tone",
                "\\uD83D\\uDEA3\\uD83C\\uDFFB" to "person rowing boat, light skin tone",
                "\\uD83D\\uDEA3\\uD83C\\uDFFC" to "person rowing boat, medium-light skin tone",
                "\\uD83D\\uDEA3\\uD83C\\uDFFD" to "person rowing boat, medium skin tone",
                "\\uD83D\\uDEA3\\uD83C\\uDFFE" to "person rowing boat, medium-dark skin tone",
                "\\uD83D\\uDEA3\\uD83C\\uDFFF" to "person rowing boat, dark skin tone",
                "\\uD83C\\uDFCA\\uD83C\\uDFFB" to "person swimming, light skin tone",
                "\\uD83C\\uDFCA\\uD83C\\uDFFC" to "person swimming, medium-light skin tone",
                "\\uD83C\\uDFCA\\uD83C\\uDFFD" to "person swimming, medium skin tone",
                "\\uD83C\\uDFCA\\uD83C\\uDFFE" to "person swimming, medium-dark skin tone",
                "\\uD83C\\uDFCA\\uD83C\\uDFFF" to "person swimming, dark skin tone",
                "\\u26F9\\uFE0F" to "person bouncing ball",
                "\\u26F9\\uD83C\\uDFFB" to "person bouncing ball, light skin tone",
                "\\u26F9\\uD83C\\uDFFC" to "person bouncing ball, medium-light skin tone",
                "\\u26F9\\uD83C\\uDFFD" to "person bouncing ball, medium skin tone",
                "\\u26F9\\uD83C\\uDFFE" to "person bouncing ball, medium-dark skin tone",
                "\\u26F9\\uD83C\\uDFFF" to "person bouncing ball, dark skin tone",
                "\\uD83C\\uDFCB\\uFE0F" to "person lifting weights",
                "\\uD83C\\uDFCB\\uD83C\\uDFFB" to "person lifting weights, light skin tone",
                "\\uD83C\\uDFCB\\uD83C\\uDFFC" to "person lifting weights, medium-light skin tone",
                "\\uD83C\\uDFCB\\uD83C\\uDFFD" to "person lifting weights, medium skin tone",
                "\\uD83C\\uDFCB\\uD83C\\uDFFE" to "person lifting weights, medium-dark skin tone",
                "\\uD83C\\uDFCB\\uD83C\\uDFFF" to "person lifting weights, dark skin tone",
                "\\uD83D\\uDEB4\\uD83C\\uDFFB" to "person biking, light skin tone",
                "\\uD83D\\uDEB4\\uD83C\\uDFFC" to "person biking, medium-light skin tone",
                "\\uD83D\\uDEB4\\uD83C\\uDFFD" to "person biking, medium skin tone",
                "\\uD83D\\uDEB4\\uD83C\\uDFFE" to "person biking, medium-dark skin tone",
                "\\uD83D\\uDEB4\\uD83C\\uDFFF" to "person biking, dark skin tone",
                "\\uD83D\\uDEB5\\uD83C\\uDFFB" to "person mountain biking, light skin tone",
                "\\uD83D\\uDEB5\\uD83C\\uDFFC" to "person mountain biking, medium-light skin tone",
                "\\uD83D\\uDEB5\\uD83C\\uDFFD" to "person mountain biking, medium skin tone",
                "\\uD83D\\uDEB5\\uD83C\\uDFFE" to "person mountain biking, medium-dark skin tone",
                "\\uD83D\\uDEB5\\uD83C\\uDFFF" to "person mountain biking, dark skin tone",
                "\\uD83E\\uDD38\\uD83C\\uDFFB" to "person cartwheeling, light skin tone",
                "\\uD83E\\uDD38\\uD83C\\uDFFC" to "person cartwheeling, medium-light skin tone",
                "\\uD83E\\uDD38\\uD83C\\uDFFD" to "person cartwheeling, medium skin tone",
                "\\uD83E\\uDD38\\uD83C\\uDFFE" to "person cartwheeling, medium-dark skin tone",
                "\\uD83E\\uDD38\\uD83C\\uDFFF" to "person cartwheeling, dark skin tone",
                "\\uD83E\\uDD3C\\uD83C\\uDFFB" to "people wrestling, light skin tone",
                "\\uD83E\\uDD3C\\uD83C\\uDFFC" to "people wrestling, medium-light skin tone",
                "\\uD83E\\uDD3C\\uD83C\\uDFFD" to "people wrestling, medium skin tone",
                "\\uD83E\\uDD3C\\uD83C\\uDFFE" to "people wrestling, medium-dark skin tone",
                "\\uD83E\\uDD3C\\uD83C\\uDFFF" to "people wrestling, dark skin tone",
                "\\uD83E\\uDD3D\\uD83C\\uDFFB" to "person playing water polo, light skin tone",
                "\\uD83E\\uDD3D\\uD83C\\uDFFC" to "person playing water polo, medium-light skin tone",
                "\\uD83E\\uDD3D\\uD83C\\uDFFD" to "person playing water polo, medium skin tone",
                "\\uD83E\\uDD3D\\uD83C\\uDFFE" to "person playing water polo, medium-dark skin tone",
                "\\uD83E\\uDD3D\\uD83C\\uDFFF" to "person playing water polo, dark skin tone",
                "\\uD83E\\uDD3E\\uD83C\\uDFFB" to "person playing handball, light skin tone",
                "\\uD83E\\uDD3E\\uD83C\\uDFFC" to "person playing handball, medium-light skin tone",
                "\\uD83E\\uDD3E\\uD83C\\uDFFD" to "person playing handball, medium skin tone",
                "\\uD83E\\uDD3E\\uD83C\\uDFFE" to "person playing handball, medium-dark skin tone",
                "\\uD83E\\uDD3E\\uD83C\\uDFFF" to "person playing handball, dark skin tone",
                "\\uD83E\\uDD39\\uD83C\\uDFFB" to "person juggling, light skin tone",
                "\\uD83E\\uDD39\\uD83C\\uDFFC" to "person juggling, medium-light skin tone",
                "\\uD83E\\uDD39\\uD83C\\uDFFD" to "person juggling, medium skin tone",
                "\\uD83E\\uDD39\\uD83C\\uDFFE" to "person juggling, medium-dark skin tone",
                "\\uD83E\\uDD39\\uD83C\\uDFFF" to "person juggling, dark skin tone",
                "\\uD83E\\uDDD8\\uD83C\\uDFFB" to "person in lotus position, light skin tone",
                "\\uD83E\\uDDD8\\uD83C\\uDFFC" to "person in lotus position, medium-light skin tone",
                "\\uD83E\\uDDD8\\uD83C\\uDFFD" to "person in lotus position, medium skin tone",
                "\\uD83E\\uDDD8\\uD83C\\uDFFE" to "person in lotus position, medium-dark skin tone",
                "\\uD83E\\uDDD8\\uD83C\\uDFFF" to "person in lotus position, dark skin tone",
                "\\uD83D\\uDEC0\\uD83C\\uDFFB" to "person taking bath, light skin tone",
                "\\uD83D\\uDEC0\\uD83C\\uDFFC" to "person taking bath, medium-light skin tone",
                "\\uD83D\\uDEC0\\uD83C\\uDFFD" to "person taking bath, medium skin tone",
                "\\uD83D\\uDEC0\\uD83C\\uDFFE" to "person taking bath, medium-dark skin tone",
                "\\uD83D\\uDEC0\\uD83C\\uDFFF" to "person taking bath, dark skin tone",
                "\\uD83D\\uDECC\\uD83C\\uDFFB" to "person in bed, light skin tone",
                "\\uD83D\\uDECC\\uD83C\\uDFFC" to "person in bed, medium-light skin tone",
                "\\uD83D\\uDECC\\uD83C\\uDFFD" to "person in bed, medium skin tone",
                "\\uD83D\\uDECC\\uD83C\\uDFFE" to "person in bed, medium-dark skin tone",
                "\\uD83D\\uDECC\\uD83C\\uDFFF" to "person in bed, dark skin tone",
                "\\uD83D\\uDC6D\\uD83C\\uDFFB" to "women holding hands, light skin tone",
                "\\uD83D\\uDC6D\\uD83C\\uDFFC" to "women holding hands, medium-light skin tone",
                "\\uD83D\\uDC6D\\uD83C\\uDFFD" to "women holding hands, medium skin tone",
                "\\uD83D\\uDC6D\\uD83C\\uDFFE" to "women holding hands, medium-dark skin tone",
                "\\uD83D\\uDC6D\\uD83C\\uDFFF" to "women holding hands, dark skin tone",
                "\\uD83D\\uDC6B\\uD83C\\uDFFB" to "woman and man holding hands, light skin tone",
                "\\uD83D\\uDC6B\\uD83C\\uDFFC" to "woman and man holding hands, medium-light skin tone",
                "\\uD83D\\uDC6B\\uD83C\\uDFFD" to "woman and man holding hands, medium skin tone",
                "\\uD83D\\uDC6B\\uD83C\\uDFFE" to "woman and man holding hands, medium-dark skin tone",
                "\\uD83D\\uDC6B\\uD83C\\uDFFF" to "woman and man holding hands, dark skin tone",
                "\\uD83D\\uDC6C\\uD83C\\uDFFB" to "men holding hands, light skin tone",
                "\\uD83D\\uDC6C\\uD83C\\uDFFC" to "men holding hands, medium-light skin tone",
                "\\uD83D\\uDC6C\\uD83C\\uDFFD" to "men holding hands, medium skin tone",
                "\\uD83D\\uDC6C\\uD83C\\uDFFE" to "men holding hands, medium-dark skin tone",
                "\\uD83D\\uDC6C\\uD83C\\uDFFF" to "men holding hands, dark skin tone",
                "\\uD83D\\uDC8F\\uD83C\\uDFFB" to "kiss, light skin tone",
                "\\uD83D\\uDC8F\\uD83C\\uDFFC" to "kiss, medium-light skin tone",
                "\\uD83D\\uDC8F\\uD83C\\uDFFD" to "kiss, medium skin tone",
                "\\uD83D\\uDC8F\\uD83C\\uDFFE" to "kiss, medium-dark skin tone",
                "\\uD83D\\uDC8F\\uD83C\\uDFFF" to "kiss, dark skin tone",
                "\\uD83D\\uDC91\\uD83C\\uDFFB" to "couple with heart, light skin tone",
                "\\uD83D\\uDC91\\uD83C\\uDFFC" to "couple with heart, medium-light skin tone",
                "\\uD83D\\uDC91\\uD83C\\uDFFD" to "couple with heart, medium skin tone",
                "\\uD83D\\uDC91\\uD83C\\uDFFE" to "couple with heart, medium-dark skin tone",
                "\\uD83D\\uDC91\\uD83C\\uDFFF" to "couple with heart, dark skin tone",
                "\\uD83D\\uDDE3\\uFE0F" to "speaking head",
                "\\uD83D\\uDC3F\\uFE0F" to "chipmunk",
                "\\uD83D\\uDD4A\\uFE0F" to "dove",
                "\\uD83D\\uDD77\\uFE0F" to "spider",
                "\\uD83D\\uDD78\\uFE0F" to "spider web",
                "\\uD83C\\uDFF5\\uFE0F" to "rosette",
                "\\u2618\\uFE0F" to "shamrock",
                "\\uD83C\\uDF36\\uFE0F" to "hot pepper",
                "\\uD83C\\uDF7D\\uFE0F" to "fork and knife with plate",
                "\\uD83D\\uDDFA\\uFE0F" to "world map",
                "\\uD83C\\uDFD4\\uFE0F" to "snow-capped mountain",
                "\\u26F0\\uFE0F" to "mountain",
                "\\uD83C\\uDFD5\\uFE0F" to "camping",
                "\\uD83C\\uDFD6\\uFE0F" to "beach with umbrella",
                "\\uD83C\\uDFDC\\uFE0F" to "desert",
                "\\uD83C\\uDFDD\\uFE0F" to "desert island",
                "\\uD83C\\uDFDE\\uFE0F" to "national park",
                "\\uD83C\\uDFDF\\uFE0F" to "stadium",
                "\\uD83C\\uDFDB\\uFE0F" to "classical building",
                "\\uD83C\\uDFD7\\uFE0F" to "building construction",
                "\\uD83C\\uDFD8\\uFE0F" to "houses",
                "\\uD83C\\uDFDA\\uFE0F" to "derelict house",
                "\\u26E9\\uFE0F" to "shinto shrine",
                "\\uD83C\\uDFD9\\uFE0F" to "cityscape",
                "\\u2668\\uFE0F" to "hot springs",
                "\\uD83C\\uDFCE\\uFE0F" to "racing car",
                "\\uD83C\\uDFCD\\uFE0F" to "motorcycle",
                "\\uD83D\\uDEE3\\uFE0F" to "motorway",
                "\\uD83D\\uDEE4\\uFE0F" to "railway track",
                "\\uD83D\\uDEE2\\uFE0F" to "oil drum",
                "\\uD83D\\uDEF3\\uFE0F" to "passenger ship",
                "\\u26F4\\uFE0F" to "ferry",
                "\\uD83D\\uDEE5\\uFE0F" to "motor boat",
                "\\u2708\\uFE0F" to "airplane",
                "\\uD83D\\uDEE9\\uFE0F" to "small airplane",
                "\\uD83D\\uDEF0\\uFE0F" to "satellite",
                "\\uD83D\\uDECE\\uFE0F" to "bellhop bell",
                "\\u23F1\\uFE0F" to "stopwatch",
                "\\u23F2\\uFE0F" to "timer clock",
                "\\uD83D\\uDD70\\uFE0F" to "mantelpiece clock",
                "\\uD83C\\uDF21\\uFE0F" to "thermometer",
                "\\u2600\\uFE0F" to "sun",
                "\\u2601\\uFE0F" to "cloud",
                "\\u26C8\\uFE0F" to "cloud with lightning and rain",
                "\\uD83C\\uDF24\\uFE0F" to "sun behind small cloud",
                "\\uD83C\\uDF25\\uFE0F" to "sun behind large cloud",
                "\\uD83C\\uDF26\\uFE0F" to "sun behind rain cloud",
                "\\uD83C\\uDF27\\uFE0F" to "cloud with rain",
                "\\uD83C\\uDF28\\uFE0F" to "cloud with snow",
                "\\uD83C\\uDF29\\uFE0F" to "cloud with lightning",
                "\\uD83C\\uDF2A\\uFE0F" to "tornado",
                "\\uD83C\\uDF2B\\uFE0F" to "fog",
                "\\uD83C\\uDF2C\\uFE0F" to "wind face",
                "\\u2602\\uFE0F" to "umbrella",
                "\\u26F1\\uFE0F" to "umbrella on ground",
                "\\u2744\\uFE0F" to "snowflake",
                "\\u2603\\uFE0F" to "snowman",
                "\\u2604\\uFE0F" to "comet",
                "\\uD83C\\uDF97\\uFE0F" to "reminder ribbon",
                "\\uD83C\\uDF9F\\uFE0F" to "admission tickets",
                "\\uD83C\\uDF96\\uFE0F" to "military medal",
                "\\u26F8\\uFE0F" to "ice skate",
                "\\uD83D\\uDD79\\uFE0F" to "joystick",
                "\\u2660\\uFE0F" to "spade suit",
                "\\u2665\\uFE0F" to "heart suit",
                "\\u2666\\uFE0F" to "diamond suit",
                "\\u2663\\uFE0F" to "club suit",
                "\\u265F\\uFE0F" to "chess pawn",
                "\\uD83D\\uDDBC\\uFE0F" to "framed picture",
                "\\uD83D\\uDD76\\uFE0F" to "sunglasses",
                "\\uD83D\\uDECD\\uFE0F" to "shopping bags",
                "\\u26D1\\uFE0F" to "rescue worker’s helmet",
                "\\uD83C\\uDF99\\uFE0F" to "studio microphone",
                "\\uD83C\\uDF9A\\uFE0F" to "level slider",
                "\\uD83C\\uDF9B\\uFE0F" to "control knobs",
                "\\u260E\\uFE0F" to "telephone",
                "\\uD83D\\uDDA5\\uFE0F" to "desktop computer",
                "\\uD83D\\uDDA8\\uFE0F" to "printer",
                "\\u2328\\uFE0F" to "keyboard",
                "\\uD83D\\uDDB1\\uFE0F" to "computer mouse",
                "\\uD83D\\uDDB2\\uFE0F" to "trackball",
                "\\uD83C\\uDF9E\\uFE0F" to "film frames",
                "\\uD83D\\uDCFD\\uFE0F" to "film projector",
                "\\uD83D\\uDD6F\\uFE0F" to "candle",
                "\\uD83D\\uDDDE\\uFE0F" to "rolled-up newspaper",
                "\\uD83C\\uDFF7\\uFE0F" to "label",
                "\\u2709\\uFE0F" to "envelope",
                "\\uD83D\\uDDF3\\uFE0F" to "ballot box with ballot",
                "\\u270F\\uFE0F" to "pencil",
                "\\u2712\\uFE0F" to "black nib",
                "\\uD83D\\uDD8B\\uFE0F" to "fountain pen",
                "\\uD83D\\uDD8A\\uFE0F" to "pen",
                "\\uD83D\\uDD8C\\uFE0F" to "paintbrush",
                "\\uD83D\\uDD8D\\uFE0F" to "crayon",
                "\\uD83D\\uDDC2\\uFE0F" to "card index dividers",
                "\\uD83D\\uDDD2\\uFE0F" to "spiral notepad",
                "\\uD83D\\uDDD3\\uFE0F" to "spiral calendar",
                "\\uD83D\\uDD87\\uFE0F" to "linked paperclips",
                "\\u2702\\uFE0F" to "scissors",
                "\\uD83D\\uDDC3\\uFE0F" to "card file box",
                "\\uD83D\\uDDC4\\uFE0F" to "file cabinet",
                "\\uD83D\\uDDD1\\uFE0F" to "wastebasket",
                "\\uD83D\\uDDDD\\uFE0F" to "old key",
                "\\u26CF\\uFE0F" to "pick",
                "\\u2692\\uFE0F" to "hammer and pick",
                "\\uD83D\\uDEE0\\uFE0F" to "hammer and wrench",
                "\\uD83D\\uDDE1\\uFE0F" to "dagger",
                "\\u2694\\uFE0F" to "crossed swords",
                "\\uD83D\\uDEE1\\uFE0F" to "shield",
                "\\u2699\\uFE0F" to "gear",
                "\\uD83D\\uDDDC\\uFE0F" to "clamp",
                "\\u2696\\uFE0F" to "balance scale",
                "\\u26D3\\uFE0F" to "chains",
                "\\u2697\\uFE0F" to "alembic",
                "\\uD83D\\uDECF\\uFE0F" to "bed",
                "\\uD83D\\uDECB\\uFE0F" to "couch and lamp",
                "\\u26B0\\uFE0F" to "coffin",
                "\\u26B1\\uFE0F" to "funeral urn",
                "\\u26A0\\uFE0F" to "warning",
                "\\u2622\\uFE0F" to "radioactive",
                "\\u2623\\uFE0F" to "biohazard",
                "\\u2B06\\uFE0F" to "up arrow",
                "\\u2197\\uFE0F" to "up-right arrow",
                "\\u27A1\\uFE0F" to "right arrow",
                "\\u2198\\uFE0F" to "down-right arrow",
                "\\u2B07\\uFE0F" to "down arrow",
                "\\u2199\\uFE0F" to "down-left arrow",
                "\\u2B05\\uFE0F" to "left arrow",
                "\\u2196\\uFE0F" to "up-left arrow",
                "\\u2195\\uFE0F" to "up-down arrow",
                "\\u2194\\uFE0F" to "left-right arrow",
                "\\u21A9\\uFE0F" to "right arrow curving left",
                "\\u21AA\\uFE0F" to "left arrow curving right",
                "\\u2934\\uFE0F" to "right arrow curving up",
                "\\u2935\\uFE0F" to "right arrow curving down",
                "\\u269B\\uFE0F" to "atom symbol",
                "\\uD83D\\uDD49\\uFE0F" to "om",
                "\\u2721\\uFE0F" to "star of David",
                "\\u2638\\uFE0F" to "wheel of dharma",
                "\\u262F\\uFE0F" to "yin yang",
                "\\u271D\\uFE0F" to "latin cross",
                "\\u2626\\uFE0F" to "orthodox cross",
                "\\u262A\\uFE0F" to "star and crescent",
                "\\u262E\\uFE0F" to "peace symbol",
                "\\u25B6\\uFE0F" to "play button",
                "\\u23ED\\uFE0F" to "next track button",
                "\\u23EF\\uFE0F" to "play or pause button",
                "\\u25C0\\uFE0F" to "reverse button",
)
