package com.xw.vvtts.utils

internal val EMOJI_08: Map<String, String> = mapOf(
                "\\u23EE\\uFE0F" to "last track button",
                "\\u23F8\\uFE0F" to "pause button",
                "\\u23F9\\uFE0F" to "stop button",
                "\\u23FA\\uFE0F" to "record button",
                "\\u23CF\\uFE0F" to "eject button",
                "\\u2640\\uFE0F" to "female sign",
                "\\u2642\\uFE0F" to "male sign",
                "\\u26A7\\uFE0F" to "transgender symbol",
                "\\u2716\\uFE0F" to "multiply",
                "\\u267E\\uFE0F" to "infinity",
                "\\u203C\\uFE0F" to "double exclamation mark",
                "\\u2049\\uFE0F" to "exclamation question mark",
                "\\u3030\\uFE0F" to "wavy dash",
                "\\u2695\\uFE0F" to "medical symbol",
                "\\u267B\\uFE0F" to "recycling symbol",
                "\\u269C\\uFE0F" to "fleur-de-lis",
                "\\u2611\\uFE0F" to "check box with check",
                "\\u2714\\uFE0F" to "check mark",
                "\\u303D\\uFE0F" to "part alternation mark",
                "\\u2733\\uFE0F" to "eight-spoked asterisk",
                "\\u2734\\uFE0F" to "eight-pointed star",
                "\\u2747\\uFE0F" to "sparkle",
                "\\u00A9\\uFE0F" to "copyright",
                "\\u00AE\\uFE0F" to "registered",
                "\\u2122\\uFE0F" to "trade mark",
                "\\uD83C\\uDD70\\uFE0F" to "A button (blood type)",
                "\\uD83C\\uDD71\\uFE0F" to "B button (blood type)",
                "\\u2139\\uFE0F" to "information",
                "\\u24C2\\uFE0F" to "circled M",
                "\\uD83C\\uDD7E\\uFE0F" to "O button (blood type)",
                "\\uD83C\\uDD7F\\uFE0F" to "P button",
                "\\uD83C\\uDE02\\uFE0F" to "Japanese “service charge” button",
                "\\uD83C\\uDE37\\uFE0F" to "Japanese “monthly amount” button",
                "\\u3297\\uFE0F" to "Japanese “congratulations” button",
                "\\u3299\\uFE0F" to "Japanese “secret” button",
                "\\u25FC\\uFE0F" to "black medium square",
                "\\u25FB\\uFE0F" to "white medium square",
                "\\u25AA\\uFE0F" to "black small square",
                "\\u25AB\\uFE0F" to "white small square",
                "\\uD83C\\uDFF3\\uFE0F" to "white flag",
                "\\uD83C\\uDDE6\\uD83C\\uDDE8" to "emoji",
                "\\uD83C\\uDDE6\\uD83C\\uDDE9" to "emoji",
                "\\uD83C\\uDDE6\\uD83C\\uDDEA" to "emoji",
                "\\uD83C\\uDDE6\\uD83C\\uDDEB" to "emoji",
                "\\uD83C\\uDDE6\\uD83C\\uDDEC" to "emoji",
                "\\uD83C\\uDDE6\\uD83C\\uDDEE" to "emoji",
                "\\uD83C\\uDDE6\\uD83C\\uDDF1" to "emoji",
                "\\uD83C\\uDDE6\\uD83C\\uDDF2" to "emoji",
                "\\uD83C\\uDDE6\\uD83C\\uDDF4" to "emoji",
                "\\uD83C\\uDDE6\\uD83C\\uDDF6" to "emoji",
                "\\uD83C\\uDDE6\\uD83C\\uDDF7" to "emoji",
                "\\uD83C\\uDDE6\\uD83C\\uDDF8" to "emoji",
                "\\uD83C\\uDDE6\\uD83C\\uDDF9" to "emoji",
                "\\uD83C\\uDDE6\\uD83C\\uDDFA" to "emoji",
                "\\uD83C\\uDDE6\\uD83C\\uDDFC" to "emoji",
                "\\uD83C\\uDDE6\\uD83C\\uDDFD" to "emoji",
                "\\uD83C\\uDDE6\\uD83C\\uDDFF" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDE6" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDE7" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDE9" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDEA" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDEB" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDEC" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDED" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDEE" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDEF" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDF1" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDF2" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDF3" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDF4" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDF6" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDF7" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDF8" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDF9" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDFB" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDFC" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDFE" to "emoji",
                "\\uD83C\\uDDE7\\uD83C\\uDDFF" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDE6" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDE8" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDE9" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDEB" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDEC" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDED" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDEE" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDF0" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDF1" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDF2" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDF3" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDF4" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDF5" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDF6" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDF7" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDFA" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDFB" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDFC" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDFD" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDFE" to "emoji",
                "\\uD83C\\uDDE8\\uD83C\\uDDFF" to "emoji",
                "\\uD83C\\uDDE9\\uD83C\\uDDEA" to "emoji",
                "\\uD83C\\uDDE9\\uD83C\\uDDEC" to "emoji",
                "\\uD83C\\uDDE9\\uD83C\\uDDEF" to "emoji",
                "\\uD83C\\uDDE9\\uD83C\\uDDF0" to "emoji",
                "\\uD83C\\uDDE9\\uD83C\\uDDF2" to "emoji",
                "\\uD83C\\uDDE9\\uD83C\\uDDF4" to "emoji",
                "\\uD83C\\uDDE9\\uD83C\\uDDFF" to "emoji",
                "\\uD83C\\uDDEA\\uD83C\\uDDE6" to "emoji",
                "\\uD83C\\uDDEA\\uD83C\\uDDE8" to "emoji",
                "\\uD83C\\uDDEA\\uD83C\\uDDEA" to "emoji",
                "\\uD83C\\uDDEA\\uD83C\\uDDEC" to "emoji",
                "\\uD83C\\uDDEA\\uD83C\\uDDED" to "emoji",
                "\\uD83C\\uDDEA\\uD83C\\uDDF7" to "emoji",
                "\\uD83C\\uDDEA\\uD83C\\uDDF8" to "emoji",
                "\\uD83C\\uDDEA\\uD83C\\uDDF9" to "emoji",
                "\\uD83C\\uDDEA\\uD83C\\uDDFA" to "emoji",
                "\\uD83C\\uDDEB\\uD83C\\uDDEE" to "emoji",
                "\\uD83C\\uDDEB\\uD83C\\uDDEF" to "emoji",
                "\\uD83C\\uDDEB\\uD83C\\uDDF0" to "emoji",
                "\\uD83C\\uDDEB\\uD83C\\uDDF2" to "emoji",
                "\\uD83C\\uDDEB\\uD83C\\uDDF4" to "emoji",
                "\\uD83C\\uDDEB\\uD83C\\uDDF7" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDE6" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDE7" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDE9" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDEA" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDEB" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDEC" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDED" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDEE" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDF1" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDF2" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDF3" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDF5" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDF6" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDF7" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDF8" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDF9" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDFA" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDFC" to "emoji",
                "\\uD83C\\uDDEC\\uD83C\\uDDFE" to "emoji",
                "\\uD83C\\uDDED\\uD83C\\uDDF0" to "emoji",
                "\\uD83C\\uDDED\\uD83C\\uDDF2" to "emoji",
                "\\uD83C\\uDDED\\uD83C\\uDDF3" to "emoji",
                "\\uD83C\\uDDED\\uD83C\\uDDF7" to "emoji",
                "\\uD83C\\uDDED\\uD83C\\uDDF9" to "emoji",
                "\\uD83C\\uDDED\\uD83C\\uDDFA" to "emoji",
                "\\uD83C\\uDDEE\\uD83C\\uDDE8" to "emoji",
                "\\uD83C\\uDDEE\\uD83C\\uDDE9" to "emoji",
                "\\uD83C\\uDDEE\\uD83C\\uDDEA" to "emoji",
                "\\uD83C\\uDDEE\\uD83C\\uDDF1" to "emoji",
                "\\uD83C\\uDDEE\\uD83C\\uDDF2" to "emoji",
                "\\uD83C\\uDDEE\\uD83C\\uDDF3" to "emoji",
                "\\uD83C\\uDDEE\\uD83C\\uDDF4" to "emoji",
                "\\uD83C\\uDDEE\\uD83C\\uDDF6" to "emoji",
                "\\uD83C\\uDDEE\\uD83C\\uDDF7" to "emoji",
                "\\uD83C\\uDDEE\\uD83C\\uDDF8" to "emoji",
                "\\uD83C\\uDDEE\\uD83C\\uDDF9" to "emoji",
                "\\uD83C\\uDDEF\\uD83C\\uDDEA" to "emoji",
                "\\uD83C\\uDDEF\\uD83C\\uDDF2" to "emoji",
                "\\uD83C\\uDDEF\\uD83C\\uDDF4" to "emoji",
                "\\uD83C\\uDDEF\\uD83C\\uDDF5" to "emoji",
                "\\uD83C\\uDDF0\\uD83C\\uDDEA" to "emoji",
                "\\uD83C\\uDDF0\\uD83C\\uDDEC" to "emoji",
                "\\uD83C\\uDDF0\\uD83C\\uDDED" to "emoji",
                "\\uD83C\\uDDF0\\uD83C\\uDDEE" to "emoji",
                "\\uD83C\\uDDF0\\uD83C\\uDDF2" to "emoji",
                "\\uD83C\\uDDF0\\uD83C\\uDDF3" to "emoji",
                "\\uD83C\\uDDF0\\uD83C\\uDDF5" to "emoji",
                "\\uD83C\\uDDF0\\uD83C\\uDDF7" to "emoji",
                "\\uD83C\\uDDF0\\uD83C\\uDDFC" to "emoji",
                "\\uD83C\\uDDF0\\uD83C\\uDDFE" to "emoji",
                "\\uD83C\\uDDF0\\uD83C\\uDDFF" to "emoji",
                "\\uD83C\\uDDF1\\uD83C\\uDDE6" to "emoji",
                "\\uD83C\\uDDF1\\uD83C\\uDDE7" to "emoji",
                "\\uD83C\\uDDF1\\uD83C\\uDDE8" to "emoji",
                "\\uD83C\\uDDF1\\uD83C\\uDDEE" to "emoji",
                "\\uD83C\\uDDF1\\uD83C\\uDDF0" to "emoji",
                "\\uD83C\\uDDF1\\uD83C\\uDDF7" to "emoji",
                "\\uD83C\\uDDF1\\uD83C\\uDDF8" to "emoji",
                "\\uD83C\\uDDF1\\uD83C\\uDDF9" to "emoji",
                "\\uD83C\\uDDF1\\uD83C\\uDDFA" to "emoji",
                "\\uD83C\\uDDF1\\uD83C\\uDDFB" to "emoji",
                "\\uD83C\\uDDF1\\uD83C\\uDDFE" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDE6" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDE8" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDE9" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDEA" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDEB" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDEC" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDED" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDF0" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDF1" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDF2" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDF3" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDF4" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDF5" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDF6" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDF7" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDF8" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDF9" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDFA" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDFB" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDFC" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDFD" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDFE" to "emoji",
                "\\uD83C\\uDDF2\\uD83C\\uDDFF" to "emoji",
                "\\uD83C\\uDDF3\\uD83C\\uDDE6" to "emoji",
                "\\uD83C\\uDDF3\\uD83C\\uDDE8" to "emoji",
                "\\uD83C\\uDDF3\\uD83C\\uDDEA" to "emoji",
                "\\uD83C\\uDDF3\\uD83C\\uDDEB" to "emoji",
                "\\uD83C\\uDDF3\\uD83C\\uDDEC" to "emoji",
                "\\uD83C\\uDDF3\\uD83C\\uDDEE" to "emoji",
                "\\uD83C\\uDDF3\\uD83C\\uDDF1" to "emoji",
                "\\uD83C\\uDDF3\\uD83C\\uDDF4" to "emoji",
                "\\uD83C\\uDDF3\\uD83C\\uDDF5" to "emoji",
                "\\uD83C\\uDDF3\\uD83C\\uDDF7" to "emoji",
                "\\uD83C\\uDDF3\\uD83C\\uDDFA" to "emoji",
                "\\uD83C\\uDDF3\\uD83C\\uDDFF" to "emoji",
                "\\uD83C\\uDDF4\\uD83C\\uDDF2" to "emoji",
                "\\uD83C\\uDDF5\\uD83C\\uDDE6" to "emoji",
                "\\uD83C\\uDDF5\\uD83C\\uDDEA" to "emoji",
                "\\uD83C\\uDDF5\\uD83C\\uDDEB" to "emoji",
                "\\uD83C\\uDDF5\\uD83C\\uDDEC" to "emoji",
                "\\uD83C\\uDDF5\\uD83C\\uDDED" to "emoji",
                "\\uD83C\\uDDF5\\uD83C\\uDDF0" to "emoji",
                "\\uD83C\\uDDF5\\uD83C\\uDDF1" to "emoji",
                "\\uD83C\\uDDF5\\uD83C\\uDDF2" to "emoji",
                "\\uD83C\\uDDF5\\uD83C\\uDDF3" to "emoji",
                "\\uD83C\\uDDF5\\uD83C\\uDDF7" to "emoji",
                "\\uD83C\\uDDF5\\uD83C\\uDDF8" to "emoji",
                "\\uD83C\\uDDF5\\uD83C\\uDDF9" to "emoji",
                "\\uD83C\\uDDF5\\uD83C\\uDDFC" to "emoji",
                "\\uD83C\\uDDF5\\uD83C\\uDDFE" to "emoji",
                "\\uD83C\\uDDF6\\uD83C\\uDDE6" to "emoji",
                "\\uD83C\\uDDF7\\uD83C\\uDDEA" to "emoji",
                "\\uD83C\\uDDF7\\uD83C\\uDDF4" to "emoji",
                "\\uD83C\\uDDF7\\uD83C\\uDDF8" to "emoji",
                "\\uD83C\\uDDF7\\uD83C\\uDDFA" to "emoji",
                "\\uD83C\\uDDF7\\uD83C\\uDDFC" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDE6" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDE7" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDE8" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDE9" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDEA" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDEC" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDED" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDEE" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDEF" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDF0" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDF1" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDF2" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDF3" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDF4" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDF7" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDF8" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDF9" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDFB" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDFD" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDFE" to "emoji",
                "\\uD83C\\uDDF8\\uD83C\\uDDFF" to "emoji",
                "\\uD83C\\uDDF9\\uD83C\\uDDE6" to "emoji",
                "\\uD83C\\uDDF9\\uD83C\\uDDE8" to "emoji",
                "\\uD83C\\uDDF9\\uD83C\\uDDE9" to "emoji",
                "\\uD83C\\uDDF9\\uD83C\\uDDEB" to "emoji",
                "\\uD83C\\uDDF9\\uD83C\\uDDEC" to "emoji",
                "\\uD83C\\uDDF9\\uD83C\\uDDED" to "emoji",
                "\\uD83C\\uDDF9\\uD83C\\uDDEF" to "emoji",
                "\\uD83C\\uDDF9\\uD83C\\uDDF0" to "emoji",
                "\\uD83C\\uDDF9\\uD83C\\uDDF1" to "emoji",
                "\\uD83C\\uDDF9\\uD83C\\uDDF2" to "emoji",
                "\\uD83C\\uDDF9\\uD83C\\uDDF3" to "emoji",
                "\\uD83C\\uDDF9\\uD83C\\uDDF4" to "emoji",
                "\\uD83C\\uDDF9\\uD83C\\uDDF7" to "emoji",
                "\\uD83C\\uDDF9\\uD83C\\uDDF9" to "emoji",
                "\\uD83C\\uDDF9\\uD83C\\uDDFB" to "emoji",
                "\\uD83C\\uDDF9\\uD83C\\uDDFC" to "emoji",
                "\\uD83C\\uDDF9\\uD83C\\uDDFF" to "emoji",
                "\\uD83C\\uDDFA\\uD83C\\uDDE6" to "emoji",
                "\\uD83C\\uDDFA\\uD83C\\uDDEC" to "emoji",
                "\\uD83C\\uDDFA\\uD83C\\uDDF2" to "emoji",
                "\\uD83C\\uDDFA\\uD83C\\uDDF3" to "emoji",
                "\\uD83C\\uDDFA\\uD83C\\uDDF8" to "emoji",
                "\\uD83C\\uDDFA\\uD83C\\uDDFE" to "emoji",
                "\\uD83C\\uDDFA\\uD83C\\uDDFF" to "emoji",
                "\\uD83C\\uDDFB\\uD83C\\uDDE6" to "emoji",
                "\\uD83C\\uDDFB\\uD83C\\uDDE8" to "emoji",
                "\\uD83C\\uDDFB\\uD83C\\uDDEA" to "emoji",
                "\\uD83C\\uDDFB\\uD83C\\uDDEC" to "emoji",
                "\\uD83C\\uDDFB\\uD83C\\uDDEE" to "emoji",
                "\\uD83C\\uDDFB\\uD83C\\uDDF3" to "emoji",
                "\\uD83C\\uDDFB\\uD83C\\uDDFA" to "emoji",
                "\\uD83C\\uDDFC\\uD83C\\uDDEB" to "emoji",
                "\\uD83C\\uDDFC\\uD83C\\uDDF8" to "emoji",
                "\\uD83C\\uDDFD\\uD83C\\uDDF0" to "emoji",
                "\\uD83C\\uDDFE\\uD83C\\uDDEA" to "emoji",
                "\\uD83C\\uDDFE\\uD83C\\uDDF9" to "emoji",
                "\\uD83C\\uDDFF\\uD83C\\uDDE6" to "emoji",
                "\\uD83C\\uDDFF\\uD83C\\uDDF2" to "emoji",
                "\\uD83C\\uDDFF\\uD83C\\uDDFC" to "emoji",
                "\\uD83D\\uDE00" to "grinning face",
                "\\uD83D\\uDE03" to "grinning face with big eyes",
                "\\uD83D\\uDE04" to "grinning face with smiling eyes",
                "\\uD83D\\uDE01" to "beaming face with smiling eyes",
                "\\uD83D\\uDE06" to "grinning squinting face",
                "\\uD83D\\uDE05" to "grinning face with sweat",
                "\\uD83E\\uDD23" to "rolling on the floor laughing",
                "\\uD83D\\uDE02" to "face with tears of joy",
                "\\uD83D\\uDE42" to "slightly smiling face",
                "\\uD83D\\uDE43" to "upside-down face",
                "\\uD83E\\uDEE0" to "melting face",
                "\\uD83E\\uDEEB" to "cracking face",
                "\\uD83D\\uDE09" to "winking face",
                "\\uD83D\\uDE0A" to "smiling face with smiling eyes",
                "\\uD83D\\uDE07" to "smiling face with halo",
                "\\uD83E\\uDD70" to "smiling face with hearts",
                "\\uD83D\\uDE0D" to "smiling face with heart-eyes",
                "\\uD83E\\uDD29" to "star-struck",
                "\\uD83D\\uDE18" to "face blowing a kiss",
                "\\uD83D\\uDE17" to "kissing face",
                "\\uD83D\\uDE1A" to "kissing face with closed eyes",
                "\\uD83D\\uDE19" to "kissing face with smiling eyes",
                "\\uD83E\\uDD72" to "smiling face with tear",
                "\\uD83D\\uDE0B" to "face savoring food",
                "\\uD83D\\uDE1B" to "face with tongue",
                "\\uD83D\\uDE1C" to "winking face with tongue",
                "\\uD83E\\uDD2A" to "zany face",
                "\\uD83D\\uDE1D" to "squinting face with tongue",
                "\\uD83E\\uDD11" to "money-mouth face",
                "\\uD83E\\uDD17" to "smiling face with open hands",
                "\\uD83E\\uDD2D" to "face with hand over mouth",
                "\\uD83E\\uDEE2" to "face with open eyes and hand over mouth",
                "\\uD83E\\uDEE3" to "face with peeking eye",
                "\\uD83E\\uDD2B" to "shushing face",
                "\\uD83E\\uDD14" to "thinking face",
                "\\uD83E\\uDEE1" to "saluting face",
                "\\uD83E\\uDD10" to "zipper-mouth face",
                "\\uD83E\\uDD28" to "face with raised eyebrow",
                "\\uD83D\\uDE10" to "neutral face",
                "\\uD83D\\uDE11" to "expressionless face",
                "\\uD83D\\uDE36" to "face without mouth",
                "\\uD83E\\uDEE5" to "dotted line face",
                "\\uD83D\\uDE0F" to "smirking face",
                "\\uD83D\\uDE12" to "unamused face",
                "\\uD83D\\uDE44" to "face with rolling eyes",
                "\\uD83D\\uDE2C" to "grimacing face",
                "\\uD83E\\uDD25" to "lying face",
                "\\uD83E\\uDEE8" to "shaking face",
                "\\uD83D\\uDE0C" to "relieved face",
                "\\uD83D\\uDE14" to "pensive face",
                "\\uD83D\\uDE2A" to "sleepy face",
                "\\uD83E\\uDD24" to "drooling face",
                "\\uD83D\\uDE34" to "sleeping face",
                "\\uD83E\\uDEE9" to "face with bags under eyes",
                "\\uD83D\\uDE37" to "face with medical mask",
                "\\uD83E\\uDD12" to "face with thermometer",
                "\\uD83E\\uDD15" to "face with head-bandage",
                "\\uD83E\\uDD22" to "nauseated face",
                "\\uD83E\\uDD2E" to "face vomiting",
                "\\uD83E\\uDD27" to "sneezing face",
                "\\uD83E\\uDD75" to "hot face",
                "\\uD83E\\uDD76" to "cold face",
                "\\uD83E\\uDD74" to "woozy face",
                "\\uD83D\\uDE35" to "face with crossed-out eyes",
                "\\uD83E\\uDD2F" to "exploding head",
                "\\uD83E\\uDD20" to "cowboy hat face",
                "\\uD83E\\uDD73" to "partying face",
                "\\uD83E\\uDD78" to "disguised face",
                "\\uD83D\\uDE0E" to "smiling face with sunglasses",
                "\\uD83E\\uDD13" to "nerd face",
                "\\uD83E\\uDDD0" to "face with monocle",
                "\\uD83D\\uDE15" to "confused face",
                "\\uD83E\\uDEE4" to "face with diagonal mouth",
                "\\uD83D\\uDE1F" to "worried face",
                "\\uD83D\\uDE41" to "slightly frowning face",
                "\\uD83D\\uDE2E" to "face with open mouth",
                "\\uD83D\\uDE2F" to "hushed face",
                "\\uD83D\\uDE32" to "astonished face",
                "\\uD83D\\uDE33" to "flushed face",
                "\\uD83E\\uDEEA" to "distorted face",
                "\\uD83E\\uDD7A" to "pleading face",
                "\\uD83E\\uDD79" to "face holding back tears",
                "\\uD83D\\uDE26" to "frowning face with open mouth",
                "\\uD83D\\uDE27" to "anguished face",
                "\\uD83D\\uDE28" to "fearful face",
                "\\uD83D\\uDE30" to "anxious face with sweat",
                "\\uD83D\\uDE25" to "sad but relieved face",
                "\\uD83D\\uDE22" to "crying face",
                "\\uD83D\\uDE2D" to "loudly crying face",
                "\\uD83D\\uDE31" to "face screaming in fear",
                "\\uD83D\\uDE16" to "confounded face",
                "\\uD83D\\uDE23" to "persevering face",
                "\\uD83D\\uDE1E" to "disappointed face",
                "\\uD83D\\uDE13" to "downcast face with sweat",
                "\\uD83D\\uDE29" to "weary face",
                "\\uD83D\\uDE2B" to "tired face",
                "\\uD83E\\uDD71" to "yawning face",
                "\\uD83D\\uDE24" to "face with steam from nose",
                "\\uD83D\\uDE21" to "enraged face",
                "\\uD83D\\uDE20" to "angry face",
                "\\uD83E\\uDD2C" to "face with symbols on mouth",
                "\\uD83D\\uDE08" to "smiling face with horns",
                "\\uD83D\\uDC7F" to "angry face with horns",
                "\\uD83D\\uDC80" to "skull",
                "\\uD83D\\uDCA9" to "pile of poo",
                "\\uD83E\\uDD21" to "clown face",
                "\\uD83D\\uDC79" to "ogre",
                "\\uD83D\\uDC7A" to "goblin",
                "\\uD83D\\uDC7B" to "ghost",
                "\\uD83D\\uDC7D" to "alien",
                "\\uD83D\\uDC7E" to "alien monster",
                "\\uD83E\\uDD16" to "robot",
                "\\uD83D\\uDE3A" to "grinning cat",
                "\\uD83D\\uDE38" to "grinning cat with smiling eyes",
                "\\uD83D\\uDE39" to "cat with tears of joy",
                "\\uD83D\\uDE3B" to "smiling cat with heart-eyes",
                "\\uD83D\\uDE3C" to "cat with wry smile",
                "\\uD83D\\uDE3D" to "kissing cat",
                "\\uD83D\\uDE40" to "weary cat",
                "\\uD83D\\uDE3F" to "crying cat",
                "\\uD83D\\uDE3E" to "pouting cat",
                "\\uD83D\\uDE48" to "see-no-evil monkey",
                "\\uD83D\\uDE49" to "hear-no-evil monkey",
                "\\uD83D\\uDE4A" to "speak-no-evil monkey",
                "\\uD83D\\uDC8C" to "love letter",
                "\\uD83D\\uDC98" to "heart with arrow",
                "\\uD83D\\uDC9D" to "heart with ribbon",
                "\\uD83D\\uDC96" to "sparkling heart",
                "\\uD83D\\uDC97" to "growing heart",
                "\\uD83D\\uDC93" to "beating heart",
                "\\uD83D\\uDC9E" to "revolving hearts",
                "\\uD83D\\uDC95" to "two hearts",
                "\\uD83D\\uDC9F" to "heart decoration",
                "\\uD83D\\uDC94" to "broken heart",
                "\\uD83E\\uDE77" to "pink heart",
                "\\uD83E\\uDDE1" to "orange heart",
                "\\uD83D\\uDC9B" to "yellow heart",
                "\\uD83D\\uDC9A" to "green heart",
                "\\uD83D\\uDC99" to "blue heart",
                "\\uD83E\\uDE75" to "light blue heart",
                "\\uD83D\\uDC9C" to "purple heart",
                "\\uD83E\\uDD0E" to "brown heart",
                "\\uD83D\\uDDA4" to "black heart",
                "\\uD83E\\uDE76" to "grey heart",
                "\\uD83E\\uDD0D" to "white heart",
                "\\uD83D\\uDC8B" to "kiss mark",
                "\\uD83D\\uDCAF" to "hundred points",
                "\\uD83D\\uDCA2" to "anger symbol",
                "\\uD83E\\uDEEF" to "fight cloud",
                "\\uD83D\\uDCA5" to "collision",
                "\\uD83D\\uDCAB" to "dizzy",
                "\\uD83D\\uDCA6" to "sweat droplets",
                "\\uD83D\\uDCA8" to "dashing away",
                "\\uD83D\\uDCAC" to "speech balloon",
                "\\uD83D\\uDCAD" to "thought balloon",
                "\\uD83D\\uDCA4" to "ZZZ",
                "\\uD83D\\uDC4B" to "waving hand",
                "\\uD83E\\uDD1A" to "raised back of hand",
                "\\u270B" to "raised hand",
                "\\uD83D\\uDD96" to "vulcan salute",
                "\\uD83E\\uDEF1" to "rightwards hand",
                "\\uD83E\\uDEF2" to "leftwards hand",
                "\\uD83E\\uDEF3" to "palm down hand",
                "\\uD83E\\uDEF4" to "palm up hand",
                "\\uD83E\\uDEF7" to "leftwards pushing hand",
                "\\uD83E\\uDEF8" to "rightwards pushing hand",
                "\\uD83D\\uDC4C" to "OK hand",
                "\\uD83E\\uDD0C" to "pinched fingers",
                "\\uD83E\\uDD0F" to "pinching hand",
                "\\uD83E\\uDD1E" to "crossed fingers",
                "\\uD83E\\uDEF0" to "hand with index finger and thumb crossed",
                "\\uD83E\\uDD1F" to "love-you gesture",
                "\\uD83E\\uDD18" to "sign of the horns",
                "\\uD83E\\uDD19" to "call me hand",
                "\\uD83D\\uDC48" to "backhand index pointing left",
                "\\uD83D\\uDC49" to "backhand index pointing right",
                "\\uD83D\\uDC46" to "backhand index pointing up",
                "\\uD83D\\uDD95" to "middle finger",
                "\\uD83D\\uDC47" to "backhand index pointing down",
                "\\uD83E\\uDEF5" to "index pointing at the viewer",
                "\\uD83D\\uDC4D" to "thumbs up",
                "\\uD83D\\uDC4E" to "thumbs down",
                "\\uD83E\\uDEF9" to "leftwards thumb sign",
                "\\uD83E\\uDEFA" to "rightwards thumb sign",
                "\\u270A" to "raised fist",
                "\\uD83D\\uDC4A" to "oncoming fist",
                "\\uD83E\\uDD1B" to "left-facing fist",
                "\\uD83E\\uDD1C" to "right-facing fist",
                "\\uD83D\\uDC4F" to "clapping hands",
                "\\uD83D\\uDE4C" to "raising hands",
                "\\uD83E\\uDEF6" to "heart hands",
                "\\uD83D\\uDC50" to "open hands",
                "\\uD83E\\uDD32" to "palms up together",
                "\\uD83E\\uDD1D" to "handshake",
                "\\uD83D\\uDE4F" to "folded hands",
                "\\uD83D\\uDC85" to "nail polish",
                "\\uD83E\\uDD33" to "selfie",
                "\\uD83D\\uDCAA" to "flexed biceps",
                "\\uD83E\\uDDBE" to "mechanical arm",
                "\\uD83E\\uDDBF" to "mechanical leg",
                "\\uD83E\\uDDB5" to "leg",
)
