package com.xw.vvtts.utils

internal val EMOJI_ZHANT_07: Map<String, String> = mapOf(
                "\\uD83D\\uDE45\\uD83C\\uDFFF" to "不行, 黑皮膚",
                "\\uD83D\\uDE46\\uD83C\\uDFFB" to "可以, 白皮膚",
                "\\uD83D\\uDE46\\uD83C\\uDFFC" to "可以, 黃皮膚",
                "\\uD83D\\uDE46\\uD83C\\uDFFD" to "可以, 淺褐皮膚",
                "\\uD83D\\uDE46\\uD83C\\uDFFE" to "可以, 褐皮膚",
                "\\uD83D\\uDE46\\uD83C\\uDFFF" to "可以, 黑皮膚",
                "\\uD83D\\uDC81\\uD83C\\uDFFB" to "服務台人員, 白皮膚",
                "\\uD83D\\uDC81\\uD83C\\uDFFC" to "服務台人員, 黃皮膚",
                "\\uD83D\\uDC81\\uD83C\\uDFFD" to "服務台人員, 淺褐皮膚",
                "\\uD83D\\uDC81\\uD83C\\uDFFE" to "服務台人員, 褐皮膚",
                "\\uD83D\\uDC81\\uD83C\\uDFFF" to "服務台人員, 黑皮膚",
                "\\uD83D\\uDE4B\\uD83C\\uDFFB" to "嗨, 白皮膚",
                "\\uD83D\\uDE4B\\uD83C\\uDFFC" to "嗨, 黃皮膚",
                "\\uD83D\\uDE4B\\uD83C\\uDFFD" to "嗨, 淺褐皮膚",
                "\\uD83D\\uDE4B\\uD83C\\uDFFE" to "嗨, 褐皮膚",
                "\\uD83D\\uDE4B\\uD83C\\uDFFF" to "嗨, 黑皮膚",
                "\\uD83E\\uDDCF\\uD83C\\uDFFB" to "聽障人士, 白皮膚",
                "\\uD83E\\uDDCF\\uD83C\\uDFFC" to "聽障人士, 黃皮膚",
                "\\uD83E\\uDDCF\\uD83C\\uDFFD" to "聽障人士, 淺褐皮膚",
                "\\uD83E\\uDDCF\\uD83C\\uDFFE" to "聽障人士, 褐皮膚",
                "\\uD83E\\uDDCF\\uD83C\\uDFFF" to "聽障人士, 黑皮膚",
                "\\uD83D\\uDE47\\uD83C\\uDFFB" to "鞠躬, 白皮膚",
                "\\uD83D\\uDE47\\uD83C\\uDFFC" to "鞠躬, 黃皮膚",
                "\\uD83D\\uDE47\\uD83C\\uDFFD" to "鞠躬, 淺褐皮膚",
                "\\uD83D\\uDE47\\uD83C\\uDFFE" to "鞠躬, 褐皮膚",
                "\\uD83D\\uDE47\\uD83C\\uDFFF" to "鞠躬, 黑皮膚",
                "\\uD83E\\uDD26\\uD83C\\uDFFB" to "哦不, 白皮膚",
                "\\uD83E\\uDD26\\uD83C\\uDFFC" to "哦不, 黃皮膚",
                "\\uD83E\\uDD26\\uD83C\\uDFFD" to "哦不, 淺褐皮膚",
                "\\uD83E\\uDD26\\uD83C\\uDFFE" to "哦不, 褐皮膚",
                "\\uD83E\\uDD26\\uD83C\\uDFFF" to "哦不, 黑皮膚",
                "\\uD83E\\uDD37\\uD83C\\uDFFB" to "聳肩, 白皮膚",
                "\\uD83E\\uDD37\\uD83C\\uDFFC" to "聳肩, 黃皮膚",
                "\\uD83E\\uDD37\\uD83C\\uDFFD" to "聳肩, 淺褐皮膚",
                "\\uD83E\\uDD37\\uD83C\\uDFFE" to "聳肩, 褐皮膚",
                "\\uD83E\\uDD37\\uD83C\\uDFFF" to "聳肩, 黑皮膚",
                "\\uD83D\\uDC6E\\uD83C\\uDFFB" to "警察, 白皮膚",
                "\\uD83D\\uDC6E\\uD83C\\uDFFC" to "警察, 黃皮膚",
                "\\uD83D\\uDC6E\\uD83C\\uDFFD" to "警察, 淺褐皮膚",
                "\\uD83D\\uDC6E\\uD83C\\uDFFE" to "警察, 褐皮膚",
                "\\uD83D\\uDC6E\\uD83C\\uDFFF" to "警察, 黑皮膚",
                "\\uD83D\\uDD75\\uFE0F" to "偵探",
                "\\uD83D\\uDD75\\uD83C\\uDFFB" to "偵探, 白皮膚",
                "\\uD83D\\uDD75\\uD83C\\uDFFC" to "偵探, 黃皮膚",
                "\\uD83D\\uDD75\\uD83C\\uDFFD" to "偵探, 淺褐皮膚",
                "\\uD83D\\uDD75\\uD83C\\uDFFE" to "偵探, 褐皮膚",
                "\\uD83D\\uDD75\\uD83C\\uDFFF" to "偵探, 黑皮膚",
                "\\uD83D\\uDC82\\uD83C\\uDFFB" to "衛兵, 白皮膚",
                "\\uD83D\\uDC82\\uD83C\\uDFFC" to "衛兵, 黃皮膚",
                "\\uD83D\\uDC82\\uD83C\\uDFFD" to "衛兵, 淺褐皮膚",
                "\\uD83D\\uDC82\\uD83C\\uDFFE" to "衛兵, 褐皮膚",
                "\\uD83D\\uDC82\\uD83C\\uDFFF" to "衛兵, 黑皮膚",
                "\\uD83E\\uDD77\\uD83C\\uDFFB" to "忍者, 白皮膚",
                "\\uD83E\\uDD77\\uD83C\\uDFFC" to "忍者, 黃皮膚",
                "\\uD83E\\uDD77\\uD83C\\uDFFD" to "忍者, 淺褐皮膚",
                "\\uD83E\\uDD77\\uD83C\\uDFFE" to "忍者, 褐皮膚",
                "\\uD83E\\uDD77\\uD83C\\uDFFF" to "忍者, 黑皮膚",
                "\\uD83D\\uDC77\\uD83C\\uDFFB" to "建築工人, 白皮膚",
                "\\uD83D\\uDC77\\uD83C\\uDFFC" to "建築工人, 黃皮膚",
                "\\uD83D\\uDC77\\uD83C\\uDFFD" to "建築工人, 淺褐皮膚",
                "\\uD83D\\uDC77\\uD83C\\uDFFE" to "建築工人, 褐皮膚",
                "\\uD83D\\uDC77\\uD83C\\uDFFF" to "建築工人, 黑皮膚",
                "\\uD83E\\uDEC5\\uD83C\\uDFFB" to "戴皇冠的人, 白皮膚",
                "\\uD83E\\uDEC5\\uD83C\\uDFFC" to "戴皇冠的人, 黃皮膚",
                "\\uD83E\\uDEC5\\uD83C\\uDFFD" to "戴皇冠的人, 淺褐皮膚",
                "\\uD83E\\uDEC5\\uD83C\\uDFFE" to "戴皇冠的人, 褐皮膚",
                "\\uD83E\\uDEC5\\uD83C\\uDFFF" to "戴皇冠的人, 黑皮膚",
                "\\uD83E\\uDD34\\uD83C\\uDFFB" to "王子, 白皮膚",
                "\\uD83E\\uDD34\\uD83C\\uDFFC" to "王子, 黃皮膚",
                "\\uD83E\\uDD34\\uD83C\\uDFFD" to "王子, 淺褐皮膚",
                "\\uD83E\\uDD34\\uD83C\\uDFFE" to "王子, 褐皮膚",
                "\\uD83E\\uDD34\\uD83C\\uDFFF" to "王子, 黑皮膚",
                "\\uD83D\\uDC78\\uD83C\\uDFFB" to "公主, 白皮膚",
                "\\uD83D\\uDC78\\uD83C\\uDFFC" to "公主, 黃皮膚",
                "\\uD83D\\uDC78\\uD83C\\uDFFD" to "公主, 淺褐皮膚",
                "\\uD83D\\uDC78\\uD83C\\uDFFE" to "公主, 褐皮膚",
                "\\uD83D\\uDC78\\uD83C\\uDFFF" to "公主, 黑皮膚",
                "\\uD83D\\uDC73\\uD83C\\uDFFB" to "戴頭巾的人, 白皮膚",
                "\\uD83D\\uDC73\\uD83C\\uDFFC" to "戴頭巾的人, 黃皮膚",
                "\\uD83D\\uDC73\\uD83C\\uDFFD" to "戴頭巾的人, 淺褐皮膚",
                "\\uD83D\\uDC73\\uD83C\\uDFFE" to "戴頭巾的人, 褐皮膚",
                "\\uD83D\\uDC73\\uD83C\\uDFFF" to "戴頭巾的人, 黑皮膚",
                "\\uD83D\\uDC72\\uD83C\\uDFFB" to "戴瓜皮帽的人, 白皮膚",
                "\\uD83D\\uDC72\\uD83C\\uDFFC" to "戴瓜皮帽的人, 黃皮膚",
                "\\uD83D\\uDC72\\uD83C\\uDFFD" to "戴瓜皮帽的人, 淺褐皮膚",
                "\\uD83D\\uDC72\\uD83C\\uDFFE" to "戴瓜皮帽的人, 褐皮膚",
                "\\uD83D\\uDC72\\uD83C\\uDFFF" to "戴瓜皮帽的人, 黑皮膚",
                "\\uD83E\\uDDD5\\uD83C\\uDFFB" to "包頭巾的女子, 白皮膚",
                "\\uD83E\\uDDD5\\uD83C\\uDFFC" to "包頭巾的女子, 黃皮膚",
                "\\uD83E\\uDDD5\\uD83C\\uDFFD" to "包頭巾的女子, 淺褐皮膚",
                "\\uD83E\\uDDD5\\uD83C\\uDFFE" to "包頭巾的女子, 褐皮膚",
                "\\uD83E\\uDDD5\\uD83C\\uDFFF" to "包頭巾的女子, 黑皮膚",
                "\\uD83E\\uDD35\\uD83C\\uDFFB" to "穿燕尾服的人, 白皮膚",
                "\\uD83E\\uDD35\\uD83C\\uDFFC" to "穿燕尾服的人, 黃皮膚",
                "\\uD83E\\uDD35\\uD83C\\uDFFD" to "穿燕尾服的人, 淺褐皮膚",
                "\\uD83E\\uDD35\\uD83C\\uDFFE" to "穿燕尾服的人, 褐皮膚",
                "\\uD83E\\uDD35\\uD83C\\uDFFF" to "穿燕尾服的人, 黑皮膚",
                "\\uD83D\\uDC70\\uD83C\\uDFFB" to "披著頭紗的人, 白皮膚",
                "\\uD83D\\uDC70\\uD83C\\uDFFC" to "披著頭紗的人, 黃皮膚",
                "\\uD83D\\uDC70\\uD83C\\uDFFD" to "披著頭紗的人, 淺褐皮膚",
                "\\uD83D\\uDC70\\uD83C\\uDFFE" to "披著頭紗的人, 褐皮膚",
                "\\uD83D\\uDC70\\uD83C\\uDFFF" to "披著頭紗的人, 黑皮膚",
                "\\uD83E\\uDD30\\uD83C\\uDFFB" to "孕婦, 白皮膚",
                "\\uD83E\\uDD30\\uD83C\\uDFFC" to "孕婦, 黃皮膚",
                "\\uD83E\\uDD30\\uD83C\\uDFFD" to "孕婦, 淺褐皮膚",
                "\\uD83E\\uDD30\\uD83C\\uDFFE" to "孕婦, 褐皮膚",
                "\\uD83E\\uDD30\\uD83C\\uDFFF" to "孕婦, 黑皮膚",
                "\\uD83E\\uDEC3\\uD83C\\uDFFB" to "懷孕的男人, 白皮膚",
                "\\uD83E\\uDEC3\\uD83C\\uDFFC" to "懷孕的男人, 黃皮膚",
                "\\uD83E\\uDEC3\\uD83C\\uDFFD" to "懷孕的男人, 淺褐皮膚",
                "\\uD83E\\uDEC3\\uD83C\\uDFFE" to "懷孕的男人, 褐皮膚",
                "\\uD83E\\uDEC3\\uD83C\\uDFFF" to "懷孕的男人, 黑皮膚",
                "\\uD83E\\uDEC4\\uD83C\\uDFFB" to "懷孕的人, 白皮膚",
                "\\uD83E\\uDEC4\\uD83C\\uDFFC" to "懷孕的人, 黃皮膚",
                "\\uD83E\\uDEC4\\uD83C\\uDFFD" to "懷孕的人, 淺褐皮膚",
                "\\uD83E\\uDEC4\\uD83C\\uDFFE" to "懷孕的人, 褐皮膚",
                "\\uD83E\\uDEC4\\uD83C\\uDFFF" to "懷孕的人, 黑皮膚",
                "\\uD83E\\uDD31\\uD83C\\uDFFB" to "哺乳, 白皮膚",
                "\\uD83E\\uDD31\\uD83C\\uDFFC" to "哺乳, 黃皮膚",
                "\\uD83E\\uDD31\\uD83C\\uDFFD" to "哺乳, 淺褐皮膚",
                "\\uD83E\\uDD31\\uD83C\\uDFFE" to "哺乳, 褐皮膚",
                "\\uD83E\\uDD31\\uD83C\\uDFFF" to "哺乳, 黑皮膚",
                "\\uD83D\\uDC7C\\uD83C\\uDFFB" to "天使, 白皮膚",
                "\\uD83D\\uDC7C\\uD83C\\uDFFC" to "天使, 黃皮膚",
                "\\uD83D\\uDC7C\\uD83C\\uDFFD" to "天使, 淺褐皮膚",
                "\\uD83D\\uDC7C\\uD83C\\uDFFE" to "天使, 褐皮膚",
                "\\uD83D\\uDC7C\\uD83C\\uDFFF" to "天使, 黑皮膚",
                "\\uD83C\\uDF85\\uD83C\\uDFFB" to "聖誕老人, 白皮膚",
                "\\uD83C\\uDF85\\uD83C\\uDFFC" to "聖誕老人, 黃皮膚",
                "\\uD83C\\uDF85\\uD83C\\uDFFD" to "聖誕老人, 淺褐皮膚",
                "\\uD83C\\uDF85\\uD83C\\uDFFE" to "聖誕老人, 褐皮膚",
                "\\uD83C\\uDF85\\uD83C\\uDFFF" to "聖誕老人, 黑皮膚",
                "\\uD83E\\uDD36\\uD83C\\uDFFB" to "聖誕老奶奶, 白皮膚",
                "\\uD83E\\uDD36\\uD83C\\uDFFC" to "聖誕老奶奶, 黃皮膚",
                "\\uD83E\\uDD36\\uD83C\\uDFFD" to "聖誕老奶奶, 淺褐皮膚",
                "\\uD83E\\uDD36\\uD83C\\uDFFE" to "聖誕老奶奶, 褐皮膚",
                "\\uD83E\\uDD36\\uD83C\\uDFFF" to "聖誕老奶奶, 黑皮膚",
                "\\uD83E\\uDDB8\\uD83C\\uDFFB" to "超級英雄, 白皮膚",
                "\\uD83E\\uDDB8\\uD83C\\uDFFC" to "超級英雄, 黃皮膚",
                "\\uD83E\\uDDB8\\uD83C\\uDFFD" to "超級英雄, 淺褐皮膚",
                "\\uD83E\\uDDB8\\uD83C\\uDFFE" to "超級英雄, 褐皮膚",
                "\\uD83E\\uDDB8\\uD83C\\uDFFF" to "超級英雄, 黑皮膚",
                "\\uD83E\\uDDB9\\uD83C\\uDFFB" to "超級反派, 白皮膚",
                "\\uD83E\\uDDB9\\uD83C\\uDFFC" to "超級反派, 黃皮膚",
                "\\uD83E\\uDDB9\\uD83C\\uDFFD" to "超級反派, 淺褐皮膚",
                "\\uD83E\\uDDB9\\uD83C\\uDFFE" to "超級反派, 褐皮膚",
                "\\uD83E\\uDDB9\\uD83C\\uDFFF" to "超級反派, 黑皮膚",
                "\\uD83E\\uDDD9\\uD83C\\uDFFB" to "魔術師, 白皮膚",
                "\\uD83E\\uDDD9\\uD83C\\uDFFC" to "魔術師, 黃皮膚",
                "\\uD83E\\uDDD9\\uD83C\\uDFFD" to "魔術師, 淺褐皮膚",
                "\\uD83E\\uDDD9\\uD83C\\uDFFE" to "魔術師, 褐皮膚",
                "\\uD83E\\uDDD9\\uD83C\\uDFFF" to "魔術師, 黑皮膚",
                "\\uD83E\\uDDDA\\uD83C\\uDFFB" to "仙女, 白皮膚",
                "\\uD83E\\uDDDA\\uD83C\\uDFFC" to "仙女, 黃皮膚",
                "\\uD83E\\uDDDA\\uD83C\\uDFFD" to "仙女, 淺褐皮膚",
                "\\uD83E\\uDDDA\\uD83C\\uDFFE" to "仙女, 褐皮膚",
                "\\uD83E\\uDDDA\\uD83C\\uDFFF" to "仙女, 黑皮膚",
                "\\uD83E\\uDDDB\\uD83C\\uDFFB" to "吸血鬼, 白皮膚",
                "\\uD83E\\uDDDB\\uD83C\\uDFFC" to "吸血鬼, 黃皮膚",
                "\\uD83E\\uDDDB\\uD83C\\uDFFD" to "吸血鬼, 淺褐皮膚",
                "\\uD83E\\uDDDB\\uD83C\\uDFFE" to "吸血鬼, 褐皮膚",
                "\\uD83E\\uDDDB\\uD83C\\uDFFF" to "吸血鬼, 黑皮膚",
                "\\uD83E\\uDDDC\\uD83C\\uDFFB" to "人魚, 白皮膚",
                "\\uD83E\\uDDDC\\uD83C\\uDFFC" to "人魚, 黃皮膚",
                "\\uD83E\\uDDDC\\uD83C\\uDFFD" to "人魚, 淺褐皮膚",
                "\\uD83E\\uDDDC\\uD83C\\uDFFE" to "人魚, 褐皮膚",
                "\\uD83E\\uDDDC\\uD83C\\uDFFF" to "人魚, 黑皮膚",
                "\\uD83E\\uDDDD\\uD83C\\uDFFB" to "小精靈, 白皮膚",
                "\\uD83E\\uDDDD\\uD83C\\uDFFC" to "小精靈, 黃皮膚",
                "\\uD83E\\uDDDD\\uD83C\\uDFFD" to "小精靈, 淺褐皮膚",
                "\\uD83E\\uDDDD\\uD83C\\uDFFE" to "小精靈, 褐皮膚",
                "\\uD83E\\uDDDD\\uD83C\\uDFFF" to "小精靈, 黑皮膚",
                "\\uD83D\\uDC86\\uD83C\\uDFFB" to "按摩, 白皮膚",
                "\\uD83D\\uDC86\\uD83C\\uDFFC" to "按摩, 黃皮膚",
                "\\uD83D\\uDC86\\uD83C\\uDFFD" to "按摩, 淺褐皮膚",
                "\\uD83D\\uDC86\\uD83C\\uDFFE" to "按摩, 褐皮膚",
                "\\uD83D\\uDC86\\uD83C\\uDFFF" to "按摩, 黑皮膚",
                "\\uD83D\\uDC87\\uD83C\\uDFFB" to "理髮, 白皮膚",
                "\\uD83D\\uDC87\\uD83C\\uDFFC" to "理髮, 黃皮膚",
                "\\uD83D\\uDC87\\uD83C\\uDFFD" to "理髮, 淺褐皮膚",
                "\\uD83D\\uDC87\\uD83C\\uDFFE" to "理髮, 褐皮膚",
                "\\uD83D\\uDC87\\uD83C\\uDFFF" to "理髮, 黑皮膚",
                "\\uD83D\\uDEB6\\uD83C\\uDFFB" to "行人, 白皮膚",
                "\\uD83D\\uDEB6\\uD83C\\uDFFC" to "行人, 黃皮膚",
                "\\uD83D\\uDEB6\\uD83C\\uDFFD" to "行人, 淺褐皮膚",
                "\\uD83D\\uDEB6\\uD83C\\uDFFE" to "行人, 褐皮膚",
                "\\uD83D\\uDEB6\\uD83C\\uDFFF" to "行人, 黑皮膚",
                "\\uD83E\\uDDCD\\uD83C\\uDFFB" to "站著的人, 白皮膚",
                "\\uD83E\\uDDCD\\uD83C\\uDFFC" to "站著的人, 黃皮膚",
                "\\uD83E\\uDDCD\\uD83C\\uDFFD" to "站著的人, 淺褐皮膚",
                "\\uD83E\\uDDCD\\uD83C\\uDFFE" to "站著的人, 褐皮膚",
                "\\uD83E\\uDDCD\\uD83C\\uDFFF" to "站著的人, 黑皮膚",
                "\\uD83E\\uDDCE\\uD83C\\uDFFB" to "跪著的人, 白皮膚",
                "\\uD83E\\uDDCE\\uD83C\\uDFFC" to "跪著的人, 黃皮膚",
                "\\uD83E\\uDDCE\\uD83C\\uDFFD" to "跪著的人, 淺褐皮膚",
                "\\uD83E\\uDDCE\\uD83C\\uDFFE" to "跪著的人, 褐皮膚",
                "\\uD83E\\uDDCE\\uD83C\\uDFFF" to "跪著的人, 黑皮膚",
                "\\uD83C\\uDFC3\\uD83C\\uDFFB" to "跑者, 白皮膚",
                "\\uD83C\\uDFC3\\uD83C\\uDFFC" to "跑者, 黃皮膚",
                "\\uD83C\\uDFC3\\uD83C\\uDFFD" to "跑者, 淺褐皮膚",
                "\\uD83C\\uDFC3\\uD83C\\uDFFE" to "跑者, 褐皮膚",
                "\\uD83C\\uDFC3\\uD83C\\uDFFF" to "跑者, 黑皮膚",
                "\\uD83D\\uDC83\\uD83C\\uDFFB" to "舞者, 白皮膚",
                "\\uD83D\\uDC83\\uD83C\\uDFFC" to "舞者, 黃皮膚",
                "\\uD83D\\uDC83\\uD83C\\uDFFD" to "舞者, 淺褐皮膚",
                "\\uD83D\\uDC83\\uD83C\\uDFFE" to "舞者, 褐皮膚",
                "\\uD83D\\uDC83\\uD83C\\uDFFF" to "舞者, 黑皮膚",
                "\\uD83D\\uDD7A\\uD83C\\uDFFB" to "男人跳著舞, 白皮膚",
                "\\uD83D\\uDD7A\\uD83C\\uDFFC" to "男人跳著舞, 黃皮膚",
                "\\uD83D\\uDD7A\\uD83C\\uDFFD" to "男人跳著舞, 淺褐皮膚",
                "\\uD83D\\uDD7A\\uD83C\\uDFFE" to "男人跳著舞, 褐皮膚",
                "\\uD83D\\uDD7A\\uD83C\\uDFFF" to "男人跳著舞, 黑皮膚",
                "\\uD83D\\uDD74\\uFE0F" to "穿西裝的人",
                "\\uD83D\\uDD74\\uD83C\\uDFFB" to "穿西裝的人, 白皮膚",
                "\\uD83D\\uDD74\\uD83C\\uDFFC" to "穿西裝的人, 黃皮膚",
                "\\uD83D\\uDD74\\uD83C\\uDFFD" to "穿西裝的人, 淺褐皮膚",
                "\\uD83D\\uDD74\\uD83C\\uDFFE" to "穿西裝的人, 褐皮膚",
                "\\uD83D\\uDD74\\uD83C\\uDFFF" to "穿西裝的人, 黑皮膚",
                "\\uD83D\\uDC6F\\uD83C\\uDFFB" to "兔女郎, 白皮膚",
                "\\uD83D\\uDC6F\\uD83C\\uDFFC" to "兔女郎, 黃皮膚",
                "\\uD83D\\uDC6F\\uD83C\\uDFFD" to "兔女郎, 淺褐皮膚",
                "\\uD83D\\uDC6F\\uD83C\\uDFFE" to "兔女郎, 褐皮膚",
                "\\uD83D\\uDC6F\\uD83C\\uDFFF" to "兔女郎, 黑皮膚",
                "\\uD83E\\uDDD6\\uD83C\\uDFFB" to "做蒸氣浴的人, 白皮膚",
                "\\uD83E\\uDDD6\\uD83C\\uDFFC" to "做蒸氣浴的人, 黃皮膚",
                "\\uD83E\\uDDD6\\uD83C\\uDFFD" to "做蒸氣浴的人, 淺褐皮膚",
                "\\uD83E\\uDDD6\\uD83C\\uDFFE" to "做蒸氣浴的人, 褐皮膚",
                "\\uD83E\\uDDD6\\uD83C\\uDFFF" to "做蒸氣浴的人, 黑皮膚",
                "\\uD83E\\uDDD7\\uD83C\\uDFFB" to "攀岩的人, 白皮膚",
                "\\uD83E\\uDDD7\\uD83C\\uDFFC" to "攀岩的人, 黃皮膚",
                "\\uD83E\\uDDD7\\uD83C\\uDFFD" to "攀岩的人, 淺褐皮膚",
                "\\uD83E\\uDDD7\\uD83C\\uDFFE" to "攀岩的人, 褐皮膚",
                "\\uD83E\\uDDD7\\uD83C\\uDFFF" to "攀岩的人, 黑皮膚",
                "\\uD83C\\uDFC7\\uD83C\\uDFFB" to "賽馬, 白皮膚",
                "\\uD83C\\uDFC7\\uD83C\\uDFFC" to "賽馬, 黃皮膚",
                "\\uD83C\\uDFC7\\uD83C\\uDFFD" to "賽馬, 淺褐皮膚",
                "\\uD83C\\uDFC7\\uD83C\\uDFFE" to "賽馬, 褐皮膚",
                "\\uD83C\\uDFC7\\uD83C\\uDFFF" to "賽馬, 黑皮膚",
                "\\u26F7\\uFE0F" to "滑雪者",
                "\\uD83C\\uDFC2\\uD83C\\uDFFB" to "滑雪板, 白皮膚",
                "\\uD83C\\uDFC2\\uD83C\\uDFFC" to "滑雪板, 黃皮膚",
                "\\uD83C\\uDFC2\\uD83C\\uDFFD" to "滑雪板, 淺褐皮膚",
                "\\uD83C\\uDFC2\\uD83C\\uDFFE" to "滑雪板, 褐皮膚",
                "\\uD83C\\uDFC2\\uD83C\\uDFFF" to "滑雪板, 黑皮膚",
                "\\uD83C\\uDFCC\\uFE0F" to "打高爾夫",
                "\\uD83C\\uDFCC\\uD83C\\uDFFB" to "打高爾夫, 白皮膚",
                "\\uD83C\\uDFCC\\uD83C\\uDFFC" to "打高爾夫, 黃皮膚",
                "\\uD83C\\uDFCC\\uD83C\\uDFFD" to "打高爾夫, 淺褐皮膚",
                "\\uD83C\\uDFCC\\uD83C\\uDFFE" to "打高爾夫, 褐皮膚",
                "\\uD83C\\uDFCC\\uD83C\\uDFFF" to "打高爾夫, 黑皮膚",
                "\\uD83C\\uDFC4\\uD83C\\uDFFB" to "衝浪, 白皮膚",
                "\\uD83C\\uDFC4\\uD83C\\uDFFC" to "衝浪, 黃皮膚",
                "\\uD83C\\uDFC4\\uD83C\\uDFFD" to "衝浪, 淺褐皮膚",
                "\\uD83C\\uDFC4\\uD83C\\uDFFE" to "衝浪, 褐皮膚",
                "\\uD83C\\uDFC4\\uD83C\\uDFFF" to "衝浪, 黑皮膚",
                "\\uD83D\\uDEA3\\uD83C\\uDFFB" to "划艇, 白皮膚",
                "\\uD83D\\uDEA3\\uD83C\\uDFFC" to "划艇, 黃皮膚",
                "\\uD83D\\uDEA3\\uD83C\\uDFFD" to "划艇, 淺褐皮膚",
                "\\uD83D\\uDEA3\\uD83C\\uDFFE" to "划艇, 褐皮膚",
                "\\uD83D\\uDEA3\\uD83C\\uDFFF" to "划艇, 黑皮膚",
                "\\uD83C\\uDFCA\\uD83C\\uDFFB" to "游泳, 白皮膚",
                "\\uD83C\\uDFCA\\uD83C\\uDFFC" to "游泳, 黃皮膚",
                "\\uD83C\\uDFCA\\uD83C\\uDFFD" to "游泳, 淺褐皮膚",
                "\\uD83C\\uDFCA\\uD83C\\uDFFE" to "游泳, 褐皮膚",
                "\\uD83C\\uDFCA\\uD83C\\uDFFF" to "游泳, 黑皮膚",
                "\\u26F9\\uFE0F" to "打球",
                "\\u26F9\\uD83C\\uDFFB" to "打球, 白皮膚",
                "\\u26F9\\uD83C\\uDFFC" to "打球, 黃皮膚",
                "\\u26F9\\uD83C\\uDFFD" to "打球, 淺褐皮膚",
                "\\u26F9\\uD83C\\uDFFE" to "打球, 褐皮膚",
                "\\u26F9\\uD83C\\uDFFF" to "打球, 黑皮膚",
                "\\uD83C\\uDFCB\\uFE0F" to "舉重",
                "\\uD83C\\uDFCB\\uD83C\\uDFFB" to "舉重, 白皮膚",
                "\\uD83C\\uDFCB\\uD83C\\uDFFC" to "舉重, 黃皮膚",
                "\\uD83C\\uDFCB\\uD83C\\uDFFD" to "舉重, 淺褐皮膚",
                "\\uD83C\\uDFCB\\uD83C\\uDFFE" to "舉重, 褐皮膚",
                "\\uD83C\\uDFCB\\uD83C\\uDFFF" to "舉重, 黑皮膚",
                "\\uD83D\\uDEB4\\uD83C\\uDFFB" to "騎自行車, 白皮膚",
                "\\uD83D\\uDEB4\\uD83C\\uDFFC" to "騎自行車, 黃皮膚",
                "\\uD83D\\uDEB4\\uD83C\\uDFFD" to "騎自行車, 淺褐皮膚",
                "\\uD83D\\uDEB4\\uD83C\\uDFFE" to "騎自行車, 褐皮膚",
                "\\uD83D\\uDEB4\\uD83C\\uDFFF" to "騎自行車, 黑皮膚",
                "\\uD83D\\uDEB5\\uD83C\\uDFFB" to "騎登山車, 白皮膚",
                "\\uD83D\\uDEB5\\uD83C\\uDFFC" to "騎登山車, 黃皮膚",
                "\\uD83D\\uDEB5\\uD83C\\uDFFD" to "騎登山車, 淺褐皮膚",
                "\\uD83D\\uDEB5\\uD83C\\uDFFE" to "騎登山車, 褐皮膚",
                "\\uD83D\\uDEB5\\uD83C\\uDFFF" to "騎登山車, 黑皮膚",
                "\\uD83E\\uDD38\\uD83C\\uDFFB" to "側翻, 白皮膚",
                "\\uD83E\\uDD38\\uD83C\\uDFFC" to "側翻, 黃皮膚",
                "\\uD83E\\uDD38\\uD83C\\uDFFD" to "側翻, 淺褐皮膚",
                "\\uD83E\\uDD38\\uD83C\\uDFFE" to "側翻, 褐皮膚",
                "\\uD83E\\uDD38\\uD83C\\uDFFF" to "側翻, 黑皮膚",
                "\\uD83E\\uDD3C\\uD83C\\uDFFB" to "摔角手, 白皮膚",
                "\\uD83E\\uDD3C\\uD83C\\uDFFC" to "摔角手, 黃皮膚",
                "\\uD83E\\uDD3C\\uD83C\\uDFFD" to "摔角手, 淺褐皮膚",
                "\\uD83E\\uDD3C\\uD83C\\uDFFE" to "摔角手, 褐皮膚",
                "\\uD83E\\uDD3C\\uD83C\\uDFFF" to "摔角手, 黑皮膚",
                "\\uD83E\\uDD3D\\uD83C\\uDFFB" to "水球運動, 白皮膚",
                "\\uD83E\\uDD3D\\uD83C\\uDFFC" to "水球運動, 黃皮膚",
                "\\uD83E\\uDD3D\\uD83C\\uDFFD" to "水球運動, 淺褐皮膚",
                "\\uD83E\\uDD3D\\uD83C\\uDFFE" to "水球運動, 褐皮膚",
                "\\uD83E\\uDD3D\\uD83C\\uDFFF" to "水球運動, 黑皮膚",
                "\\uD83E\\uDD3E\\uD83C\\uDFFB" to "手球, 白皮膚",
                "\\uD83E\\uDD3E\\uD83C\\uDFFC" to "手球, 黃皮膚",
                "\\uD83E\\uDD3E\\uD83C\\uDFFD" to "手球, 淺褐皮膚",
                "\\uD83E\\uDD3E\\uD83C\\uDFFE" to "手球, 褐皮膚",
                "\\uD83E\\uDD3E\\uD83C\\uDFFF" to "手球, 黑皮膚",
                "\\uD83E\\uDD39\\uD83C\\uDFFB" to "雜耍, 白皮膚",
                "\\uD83E\\uDD39\\uD83C\\uDFFC" to "雜耍, 黃皮膚",
                "\\uD83E\\uDD39\\uD83C\\uDFFD" to "雜耍, 淺褐皮膚",
                "\\uD83E\\uDD39\\uD83C\\uDFFE" to "雜耍, 褐皮膚",
                "\\uD83E\\uDD39\\uD83C\\uDFFF" to "雜耍, 黑皮膚",
                "\\uD83E\\uDDD8\\uD83C\\uDFFB" to "盤坐, 白皮膚",
                "\\uD83E\\uDDD8\\uD83C\\uDFFC" to "盤坐, 黃皮膚",
                "\\uD83E\\uDDD8\\uD83C\\uDFFD" to "盤坐, 淺褐皮膚",
                "\\uD83E\\uDDD8\\uD83C\\uDFFE" to "盤坐, 褐皮膚",
                "\\uD83E\\uDDD8\\uD83C\\uDFFF" to "盤坐, 黑皮膚",
                "\\uD83D\\uDEC0\\uD83C\\uDFFB" to "盆浴, 白皮膚",
                "\\uD83D\\uDEC0\\uD83C\\uDFFC" to "盆浴, 黃皮膚",
                "\\uD83D\\uDEC0\\uD83C\\uDFFD" to "盆浴, 淺褐皮膚",
                "\\uD83D\\uDEC0\\uD83C\\uDFFE" to "盆浴, 褐皮膚",
                "\\uD83D\\uDEC0\\uD83C\\uDFFF" to "盆浴, 黑皮膚",
                "\\uD83D\\uDECC\\uD83C\\uDFFB" to "睡覺, 白皮膚",
                "\\uD83D\\uDECC\\uD83C\\uDFFC" to "睡覺, 黃皮膚",
                "\\uD83D\\uDECC\\uD83C\\uDFFD" to "睡覺, 淺褐皮膚",
                "\\uD83D\\uDECC\\uD83C\\uDFFE" to "睡覺, 褐皮膚",
                "\\uD83D\\uDECC\\uD83C\\uDFFF" to "睡覺, 黑皮膚",
                "\\uD83D\\uDC6D\\uD83C\\uDFFB" to "兩個女人, 白皮膚",
                "\\uD83D\\uDC6D\\uD83C\\uDFFC" to "兩個女人, 黃皮膚",
                "\\uD83D\\uDC6D\\uD83C\\uDFFD" to "兩個女人, 淺褐皮膚",
                "\\uD83D\\uDC6D\\uD83C\\uDFFE" to "兩個女人, 褐皮膚",
                "\\uD83D\\uDC6D\\uD83C\\uDFFF" to "兩個女人, 黑皮膚",
                "\\uD83D\\uDC6B\\uD83C\\uDFFB" to "一男一女, 白皮膚",
                "\\uD83D\\uDC6B\\uD83C\\uDFFC" to "一男一女, 黃皮膚",
                "\\uD83D\\uDC6B\\uD83C\\uDFFD" to "一男一女, 淺褐皮膚",
                "\\uD83D\\uDC6B\\uD83C\\uDFFE" to "一男一女, 褐皮膚",
                "\\uD83D\\uDC6B\\uD83C\\uDFFF" to "一男一女, 黑皮膚",
                "\\uD83D\\uDC6C\\uD83C\\uDFFB" to "兩個男人, 白皮膚",
                "\\uD83D\\uDC6C\\uD83C\\uDFFC" to "兩個男人, 黃皮膚",
                "\\uD83D\\uDC6C\\uD83C\\uDFFD" to "兩個男人, 淺褐皮膚",
                "\\uD83D\\uDC6C\\uD83C\\uDFFE" to "兩個男人, 褐皮膚",
                "\\uD83D\\uDC6C\\uD83C\\uDFFF" to "兩個男人, 黑皮膚",
                "\\uD83D\\uDC8F\\uD83C\\uDFFB" to "親, 白皮膚",
                "\\uD83D\\uDC8F\\uD83C\\uDFFC" to "親, 黃皮膚",
                "\\uD83D\\uDC8F\\uD83C\\uDFFD" to "親, 淺褐皮膚",
                "\\uD83D\\uDC8F\\uD83C\\uDFFE" to "親, 褐皮膚",
                "\\uD83D\\uDC8F\\uD83C\\uDFFF" to "親, 黑皮膚",
                "\\uD83D\\uDC91\\uD83C\\uDFFB" to "相愛, 白皮膚",
                "\\uD83D\\uDC91\\uD83C\\uDFFC" to "相愛, 黃皮膚",
                "\\uD83D\\uDC91\\uD83C\\uDFFD" to "相愛, 淺褐皮膚",
                "\\uD83D\\uDC91\\uD83C\\uDFFE" to "相愛, 褐皮膚",
                "\\uD83D\\uDC91\\uD83C\\uDFFF" to "相愛, 黑皮膚",
                "\\uD83D\\uDDE3\\uFE0F" to "說話的人影",
                "\\uD83D\\uDC3F\\uFE0F" to "松鼠",
                "\\uD83D\\uDD4A\\uFE0F" to "飛鳥",
                "\\uD83D\\uDD77\\uFE0F" to "蜘蛛",
                "\\uD83D\\uDD78\\uFE0F" to "蜘蛛網",
                "\\uD83C\\uDFF5\\uFE0F" to "花朵",
                "\\u2618\\uFE0F" to "三葉草",
                "\\uD83C\\uDF36\\uFE0F" to "辣椒",
                "\\uD83C\\uDF7D\\uFE0F" to "餐具",
                "\\uD83D\\uDDFA\\uFE0F" to "世界地圖",
                "\\uD83C\\uDFD4\\uFE0F" to "雪山",
                "\\u26F0\\uFE0F" to "山",
                "\\uD83C\\uDFD5\\uFE0F" to "露營",
                "\\uD83C\\uDFD6\\uFE0F" to "海灘陽傘",
                "\\uD83C\\uDFDC\\uFE0F" to "沙漠",
                "\\uD83C\\uDFDD\\uFE0F" to "熱帶小島",
                "\\uD83C\\uDFDE\\uFE0F" to "國家公園",
                "\\uD83C\\uDFDF\\uFE0F" to "競技場",
                "\\uD83C\\uDFDB\\uFE0F" to "古典建築",
                "\\uD83C\\uDFD7\\uFE0F" to "施工中",
                "\\uD83C\\uDFD8\\uFE0F" to "房屋建築",
                "\\uD83C\\uDFDA\\uFE0F" to "廢墟",
                "\\u26E9\\uFE0F" to "神社",
                "\\uD83C\\uDFD9\\uFE0F" to "都市風景",
                "\\u2668\\uFE0F" to "溫泉",
                "\\uD83C\\uDFCE\\uFE0F" to "賽車",
                "\\uD83C\\uDFCD\\uFE0F" to "機車",
                "\\uD83D\\uDEE3\\uFE0F" to "高速公路",
                "\\uD83D\\uDEE4\\uFE0F" to "鐵軌",
                "\\uD83D\\uDEE2\\uFE0F" to "油桶",
                "\\uD83D\\uDEF3\\uFE0F" to "客船",
                "\\u26F4\\uFE0F" to "渡輪",
                "\\uD83D\\uDEE5\\uFE0F" to "汽艇",
                "\\u2708\\uFE0F" to "飛機",
                "\\uD83D\\uDEE9\\uFE0F" to "小飛機",
                "\\uD83D\\uDEF0\\uFE0F" to "衛星",
                "\\uD83D\\uDECE\\uFE0F" to "服務鈴",
                "\\u23F1\\uFE0F" to "碼錶",
                "\\u23F2\\uFE0F" to "計時器",
                "\\uD83D\\uDD70\\uFE0F" to "座鐘",
                "\\uD83C\\uDF21\\uFE0F" to "溫度計",
                "\\u2600\\uFE0F" to "太陽",
                "\\u2601\\uFE0F" to "雲",
                "\\u26C8\\uFE0F" to "雷雨",
                "\\uD83C\\uDF24\\uFE0F" to "晴偶有雲",
                "\\uD83C\\uDF25\\uFE0F" to "晴時多雲",
                "\\uD83C\\uDF26\\uFE0F" to "晴時有雨",
                "\\uD83C\\uDF27\\uFE0F" to "雨天",
                "\\uD83C\\uDF28\\uFE0F" to "下雪",
                "\\uD83C\\uDF29\\uFE0F" to "閃電",
                "\\uD83C\\uDF2A\\uFE0F" to "龍捲風",
                "\\uD83C\\uDF2B\\uFE0F" to "有霧",
                "\\uD83C\\uDF2C\\uFE0F" to "刮風",
                "\\u2602\\uFE0F" to "雨傘",
                "\\u26F1\\uFE0F" to "遮陽傘",
                "\\u2744\\uFE0F" to "雪花",
                "\\u2603\\uFE0F" to "雪中的雪人",
                "\\u2604\\uFE0F" to "慧星",
                "\\uD83C\\uDF97\\uFE0F" to "黃絲帶",
                "\\uD83C\\uDF9F\\uFE0F" to "入場券",
                "\\uD83C\\uDF96\\uFE0F" to "軍事獎章",
                "\\u26F8\\uFE0F" to "溜冰鞋",
                "\\uD83D\\uDD79\\uFE0F" to "搖桿",
                "\\u2660\\uFE0F" to "黑桃",
                "\\u2665\\uFE0F" to "紅心",
                "\\u2666\\uFE0F" to "方塊",
                "\\u2663\\uFE0F" to "梅花",
                "\\u265F\\uFE0F" to "卒",
                "\\uD83D\\uDDBC\\uFE0F" to "裱框畫",
                "\\uD83D\\uDD76\\uFE0F" to "太陽眼鏡",
                "\\uD83D\\uDECD\\uFE0F" to "紙袋",
                "\\u26D1\\uFE0F" to "工程安全帽",
                "\\uD83C\\uDF99\\uFE0F" to "錄音室麥克風",
                "\\uD83C\\uDF9A\\uFE0F" to "調整桿",
                "\\uD83C\\uDF9B\\uFE0F" to "控制旋鈕",
                "\\u260E\\uFE0F" to "電話",
                "\\uD83D\\uDDA5\\uFE0F" to "電腦",
                "\\uD83D\\uDDA8\\uFE0F" to "印表機",
                "\\u2328\\uFE0F" to "鍵盤",
                "\\uD83D\\uDDB1\\uFE0F" to "滑鼠",
                "\\uD83D\\uDDB2\\uFE0F" to "軌跡球",
                "\\uD83C\\uDF9E\\uFE0F" to "電影膠卷",
                "\\uD83D\\uDCFD\\uFE0F" to "電影放映機",
                "\\uD83D\\uDD6F\\uFE0F" to "蠟燭",
                "\\uD83D\\uDDDE\\uFE0F" to "捲好的報紙",
                "\\uD83C\\uDFF7\\uFE0F" to "吊牌",
                "\\u2709\\uFE0F" to "郵件",
                "\\uD83D\\uDDF3\\uFE0F" to "投票箱",
                "\\u270F\\uFE0F" to "鉛筆",
                "\\u2712\\uFE0F" to "鋼筆頭",
                "\\uD83D\\uDD8B\\uFE0F" to "鋼筆",
                "\\uD83D\\uDD8A\\uFE0F" to "筆",
                "\\uD83D\\uDD8C\\uFE0F" to "畫筆",
                "\\uD83D\\uDD8D\\uFE0F" to "蠟筆",
                "\\uD83D\\uDDC2\\uFE0F" to "索引隔板",
                "\\uD83D\\uDDD2\\uFE0F" to "線圈筆記本",
                "\\uD83D\\uDDD3\\uFE0F" to "線圈日曆",
                "\\uD83D\\uDD87\\uFE0F" to "相連的回紋針",
                "\\u2702\\uFE0F" to "剪刀",
                "\\uD83D\\uDDC3\\uFE0F" to "卡片目錄盒",
                "\\uD83D\\uDDC4\\uFE0F" to "檔案櫃",
                "\\uD83D\\uDDD1\\uFE0F" to "廢紙簍",
                "\\uD83D\\uDDDD\\uFE0F" to "老鑰匙",
                "\\u26CF\\uFE0F" to "十字鎬",
                "\\u2692\\uFE0F" to "鎚子和十字鎬",
                "\\uD83D\\uDEE0\\uFE0F" to "鎚子和扳手",
                "\\uD83D\\uDDE1\\uFE0F" to "匕首",
                "\\u2694\\uFE0F" to "劍",
                "\\uD83D\\uDEE1\\uFE0F" to "盾牌",
                "\\u2699\\uFE0F" to "齒輪",
                "\\uD83D\\uDDDC\\uFE0F" to "壓縮機",
                "\\u2696\\uFE0F" to "天平",
                "\\u26D3\\uFE0F" to "鍊條",
                "\\u2697\\uFE0F" to "蒸餾器",
                "\\uD83D\\uDECF\\uFE0F" to "床",
                "\\uD83D\\uDECB\\uFE0F" to "沙發和立燈",
                "\\u26B0\\uFE0F" to "棺木",
                "\\u26B1\\uFE0F" to "骨灰罈",
                "\\u26A0\\uFE0F" to "警告",
                "\\u2622\\uFE0F" to "放射性",
                "\\u2623\\uFE0F" to "危害生物",
                "\\u2B06\\uFE0F" to "向上箭頭",
                "\\u2197\\uFE0F" to "右上箭頭",
                "\\u27A1\\uFE0F" to "向右箭頭",
                "\\u2198\\uFE0F" to "右下箭頭",
                "\\u2B07\\uFE0F" to "向下箭頭",
                "\\u2199\\uFE0F" to "左下箭頭",
                "\\u2B05\\uFE0F" to "向左箭頭",
                "\\u2196\\uFE0F" to "左上箭頭",
                "\\u2195\\uFE0F" to "上下箭頭",
                "\\u2194\\uFE0F" to "左右箭頭",
                "\\u21A9\\uFE0F" to "向左彎的右箭頭",
                "\\u21AA\\uFE0F" to "向右彎的左箭頭",
                "\\u2934\\uFE0F" to "右上旋轉箭頭",
                "\\u2935\\uFE0F" to "右下旋轉箭頭",
                "\\u269B\\uFE0F" to "原子",
                "\\uD83D\\uDD49\\uFE0F" to "唵",
                "\\u2721\\uFE0F" to "六芒星",
                "\\u2638\\uFE0F" to "法輪",
                "\\u262F\\uFE0F" to "陰陽",
                "\\u271D\\uFE0F" to "拉丁十字架",
                "\\u2626\\uFE0F" to "東正教十字架",
                "\\u262A\\uFE0F" to "伊斯蘭教星月",
                "\\u262E\\uFE0F" to "和平",
                "\\u25B6\\uFE0F" to "播放",
                "\\u23ED\\uFE0F" to "下一首",
                "\\u23EF\\uFE0F" to "播放或暫停",
                "\\u25C0\\uFE0F" to "倒轉",
)
