package com.xw.vvtts.utils

internal val EMOJI_06: Map<String, String> = mapOf(
                "\\uD83D\\uDC69\\u200D\\u2695" to "woman health worker",
                "\\uD83E\\uDDD1\\u200D\\uD83C\\uDF93" to "student",
                "\\uD83D\\uDC68\\u200D\\uD83C\\uDF93" to "man student",
                "\\uD83D\\uDC69\\u200D\\uD83C\\uDF93" to "woman student",
                "\\uD83E\\uDDD1\\u200D\\uD83C\\uDFEB" to "teacher",
                "\\uD83D\\uDC68\\u200D\\uD83C\\uDFEB" to "man teacher",
                "\\uD83D\\uDC69\\u200D\\uD83C\\uDFEB" to "woman teacher",
                "\\uD83E\\uDDD1\\u200D\\u2696" to "judge",
                "\\uD83D\\uDC68\\u200D\\u2696" to "man judge",
                "\\uD83D\\uDC69\\u200D\\u2696" to "woman judge",
                "\\uD83E\\uDDD1\\u200D\\uD83C\\uDF3E" to "farmer",
                "\\uD83D\\uDC68\\u200D\\uD83C\\uDF3E" to "man farmer",
                "\\uD83D\\uDC69\\u200D\\uD83C\\uDF3E" to "woman farmer",
                "\\uD83E\\uDDD1\\u200D\\uD83C\\uDF73" to "cook",
                "\\uD83D\\uDC68\\u200D\\uD83C\\uDF73" to "man cook",
                "\\uD83D\\uDC69\\u200D\\uD83C\\uDF73" to "woman cook",
                "\\uD83E\\uDDD1\\u200D\\uD83D\\uDD27" to "mechanic",
                "\\uD83D\\uDC68\\u200D\\uD83D\\uDD27" to "man mechanic",
                "\\uD83D\\uDC69\\u200D\\uD83D\\uDD27" to "woman mechanic",
                "\\uD83E\\uDDD1\\u200D\\uD83C\\uDFED" to "factory worker",
                "\\uD83D\\uDC68\\u200D\\uD83C\\uDFED" to "man factory worker",
                "\\uD83D\\uDC69\\u200D\\uD83C\\uDFED" to "woman factory worker",
                "\\uD83E\\uDDD1\\u200D\\uD83D\\uDCBC" to "office worker",
                "\\uD83D\\uDC68\\u200D\\uD83D\\uDCBC" to "man office worker",
                "\\uD83D\\uDC69\\u200D\\uD83D\\uDCBC" to "woman office worker",
                "\\uD83E\\uDDD1\\u200D\\uD83D\\uDD2C" to "scientist",
                "\\uD83D\\uDC68\\u200D\\uD83D\\uDD2C" to "man scientist",
                "\\uD83D\\uDC69\\u200D\\uD83D\\uDD2C" to "woman scientist",
                "\\uD83E\\uDDD1\\u200D\\uD83D\\uDCBB" to "technologist",
                "\\uD83D\\uDC68\\u200D\\uD83D\\uDCBB" to "man technologist",
                "\\uD83D\\uDC69\\u200D\\uD83D\\uDCBB" to "woman technologist",
                "\\uD83E\\uDDD1\\u200D\\uD83C\\uDFA4" to "singer",
                "\\uD83D\\uDC68\\u200D\\uD83C\\uDFA4" to "man singer",
                "\\uD83D\\uDC69\\u200D\\uD83C\\uDFA4" to "woman singer",
                "\\uD83E\\uDDD1\\u200D\\uD83C\\uDFA8" to "artist",
                "\\uD83D\\uDC68\\u200D\\uD83C\\uDFA8" to "man artist",
                "\\uD83D\\uDC69\\u200D\\uD83C\\uDFA8" to "woman artist",
                "\\uD83E\\uDDD1\\u200D\\u2708" to "pilot",
                "\\uD83D\\uDC68\\u200D\\u2708" to "man pilot",
                "\\uD83D\\uDC69\\u200D\\u2708" to "woman pilot",
                "\\uD83E\\uDDD1\\u200D\\uD83D\\uDE80" to "astronaut",
                "\\uD83D\\uDC68\\u200D\\uD83D\\uDE80" to "man astronaut",
                "\\uD83D\\uDC69\\u200D\\uD83D\\uDE80" to "woman astronaut",
                "\\uD83E\\uDDD1\\u200D\\uD83D\\uDE92" to "firefighter",
                "\\uD83D\\uDC68\\u200D\\uD83D\\uDE92" to "man firefighter",
                "\\uD83D\\uDC69\\u200D\\uD83D\\uDE92" to "woman firefighter",
                "\\uD83D\\uDC6E\\u200D\\u2642" to "man police officer",
                "\\uD83D\\uDC6E\\u200D\\u2640" to "woman police officer",
                "\\uD83D\\uDC82\\u200D\\u2642" to "man guard",
                "\\uD83D\\uDC82\\u200D\\u2640" to "woman guard",
                "\\uD83D\\uDC77\\u200D\\u2642" to "man construction worker",
                "\\uD83D\\uDC77\\u200D\\u2640" to "woman construction worker",
                "\\uD83D\\uDC73\\u200D\\u2642" to "man wearing turban",
                "\\uD83D\\uDC73\\u200D\\u2640" to "woman wearing turban",
                "\\uD83E\\uDD35\\u200D\\u2642" to "man in tuxedo",
                "\\uD83E\\uDD35\\u200D\\u2640" to "woman in tuxedo",
                "\\uD83D\\uDC70\\u200D\\u2642" to "man with veil",
                "\\uD83D\\uDC70\\u200D\\u2640" to "woman with veil",
                "\\uD83D\\uDC69\\u200D\\uD83C\\uDF7C" to "woman feeding baby",
                "\\uD83D\\uDC68\\u200D\\uD83C\\uDF7C" to "man feeding baby",
                "\\uD83E\\uDDD1\\u200D\\uD83C\\uDF7C" to "person feeding baby",
                "\\uD83E\\uDDD1\\u200D\\uD83C\\uDF84" to "Mx Claus",
                "\\uD83E\\uDDB8\\u200D\\u2642" to "man superhero",
                "\\uD83E\\uDDB8\\u200D\\u2640" to "woman superhero",
                "\\uD83E\\uDDB9\\u200D\\u2642" to "man supervillain",
                "\\uD83E\\uDDB9\\u200D\\u2640" to "woman supervillain",
                "\\uD83E\\uDDD9\\u200D\\u2642" to "man mage",
                "\\uD83E\\uDDD9\\u200D\\u2640" to "woman mage",
                "\\uD83E\\uDDDA\\u200D\\u2642" to "man fairy",
                "\\uD83E\\uDDDA\\u200D\\u2640" to "woman fairy",
                "\\uD83E\\uDDDB\\u200D\\u2642" to "man vampire",
                "\\uD83E\\uDDDB\\u200D\\u2640" to "woman vampire",
                "\\uD83E\\uDDDC\\u200D\\u2642" to "merman",
                "\\uD83E\\uDDDC\\u200D\\u2640" to "mermaid",
                "\\uD83E\\uDDDD\\u200D\\u2642" to "man elf",
                "\\uD83E\\uDDDD\\u200D\\u2640" to "woman elf",
                "\\uD83E\\uDDDE\\u200D\\u2642" to "man genie",
                "\\uD83E\\uDDDE\\u200D\\u2640" to "woman genie",
                "\\uD83E\\uDDDF\\u200D\\u2642" to "man zombie",
                "\\uD83E\\uDDDF\\u200D\\u2640" to "woman zombie",
                "\\uD83D\\uDC86\\u200D\\u2642" to "man getting massage",
                "\\uD83D\\uDC86\\u200D\\u2640" to "woman getting massage",
                "\\uD83D\\uDC87\\u200D\\u2642" to "man getting haircut",
                "\\uD83D\\uDC87\\u200D\\u2640" to "woman getting haircut",
                "\\uD83D\\uDEB6\\u200D\\u2642" to "man walking",
                "\\uD83D\\uDEB6\\u200D\\u2640" to "woman walking",
                "\\uD83D\\uDEB6\\u200D\\u27A1" to "person walking, right arrow",
                "\\uD83E\\uDDCD\\u200D\\u2642" to "man standing",
                "\\uD83E\\uDDCD\\u200D\\u2640" to "woman standing",
                "\\uD83E\\uDDCE\\u200D\\u2642" to "man kneeling",
                "\\uD83E\\uDDCE\\u200D\\u2640" to "woman kneeling",
                "\\uD83E\\uDDCE\\u200D\\u27A1" to "person kneeling, right arrow",
                "\\uD83E\\uDDD1\\u200D\\uD83E\\uDDAF" to "person with white cane",
                "\\uD83D\\uDC68\\u200D\\uD83E\\uDDAF" to "man with white cane",
                "\\uD83D\\uDC69\\u200D\\uD83E\\uDDAF" to "woman with white cane",
                "\\uD83E\\uDDD1\\u200D\\uD83E\\uDDBC" to "person in motorized wheelchair",
                "\\uD83D\\uDC68\\u200D\\uD83E\\uDDBC" to "man in motorized wheelchair",
                "\\uD83D\\uDC69\\u200D\\uD83E\\uDDBC" to "woman in motorized wheelchair",
                "\\uD83E\\uDDD1\\u200D\\uD83E\\uDDBD" to "person in manual wheelchair",
                "\\uD83D\\uDC68\\u200D\\uD83E\\uDDBD" to "man in manual wheelchair",
                "\\uD83D\\uDC69\\u200D\\uD83E\\uDDBD" to "woman in manual wheelchair",
                "\\uD83C\\uDFC3\\u200D\\u2642" to "man running",
                "\\uD83C\\uDFC3\\u200D\\u2640" to "woman running",
                "\\uD83C\\uDFC3\\u200D\\u27A1" to "person running, right arrow",
                "\\uD83E\\uDDD1\\u200D\\uD83E\\uDE70" to "ballet dancer",
                "\\uD83D\\uDC6F\\u200D\\u2642" to "men with bunny ears",
                "\\uD83D\\uDC6F\\u200D\\u2640" to "women with bunny ears",
                "\\uD83E\\uDDD6\\u200D\\u2642" to "man in steamy room",
                "\\uD83E\\uDDD6\\u200D\\u2640" to "woman in steamy room",
                "\\uD83E\\uDDD7\\u200D\\u2642" to "man climbing",
                "\\uD83E\\uDDD7\\u200D\\u2640" to "woman climbing",
                "\\uD83C\\uDFC4\\u200D\\u2642" to "man surfing",
                "\\uD83C\\uDFC4\\u200D\\u2640" to "woman surfing",
                "\\uD83D\\uDEA3\\u200D\\u2642" to "man rowing boat",
                "\\uD83D\\uDEA3\\u200D\\u2640" to "woman rowing boat",
                "\\uD83C\\uDFCA\\u200D\\u2642" to "man swimming",
                "\\uD83C\\uDFCA\\u200D\\u2640" to "woman swimming",
                "\\uD83D\\uDEB4\\u200D\\u2642" to "man biking",
                "\\uD83D\\uDEB4\\u200D\\u2640" to "woman biking",
                "\\uD83D\\uDEB5\\u200D\\u2642" to "man mountain biking",
                "\\uD83D\\uDEB5\\u200D\\u2640" to "woman mountain biking",
                "\\uD83E\\uDD38\\u200D\\u2642" to "man cartwheeling",
                "\\uD83E\\uDD38\\u200D\\u2640" to "woman cartwheeling",
                "\\uD83E\\uDD3C\\u200D\\u2642" to "men wrestling",
                "\\uD83E\\uDD3C\\u200D\\u2640" to "women wrestling",
                "\\uD83E\\uDD3D\\u200D\\u2642" to "man playing water polo",
                "\\uD83E\\uDD3D\\u200D\\u2640" to "woman playing water polo",
                "\\uD83E\\uDD3E\\u200D\\u2642" to "man playing handball",
                "\\uD83E\\uDD3E\\u200D\\u2640" to "woman playing handball",
                "\\uD83E\\uDD39\\u200D\\u2642" to "man juggling",
                "\\uD83E\\uDD39\\u200D\\u2640" to "woman juggling",
                "\\uD83E\\uDDD8\\u200D\\u2642" to "man in lotus position",
                "\\uD83E\\uDDD8\\u200D\\u2640" to "woman in lotus position",
                "\\uD83D\\uDC68\\u200D\\uD83D\\uDC66" to "man, boy",
                "\\uD83D\\uDC68\\u200D\\uD83D\\uDC67" to "man, girl",
                "\\uD83D\\uDC69\\u200D\\uD83D\\uDC66" to "woman, boy",
                "\\uD83D\\uDC69\\u200D\\uD83D\\uDC67" to "woman, girl",
                "\\uD83E\\uDDD1\\u200D\\uD83E\\uDDD2" to "family: adult, child",
                "\\uD83D\\uDC15\\u200D\\uD83E\\uDDBA" to "service dog",
                "\\uD83D\\uDC08\\u200D\\u2B1B" to "black cat",
                "\\uD83D\\uDC3B\\u200D\\u2744" to "polar bear",
                "\\uD83D\\uDC26\\u200D\\u2B1B" to "black bird",
                "\\uD83D\\uDC26\\u200D\\uD83D\\uDD25" to "phoenix",
                "\\uD83C\\uDF4B\\u200D\\uD83D\\uDFE9" to "lime",
                "\\uD83C\\uDF44\\u200D\\uD83D\\uDFEB" to "brown mushroom",
                "\\u0023\\uFE0F\\u20E3" to "hash sign",
                "\\u002A\\uFE0F\\u20E3" to "asterisk",
                "\\u0030\\uFE0F\\u20E3" to "keycap: 0",
                "\\u0031\\uFE0F\\u20E3" to "keycap: 1",
                "\\u0032\\uFE0F\\u20E3" to "keycap: 2",
                "\\u0033\\uFE0F\\u20E3" to "keycap: 3",
                "\\u0034\\uFE0F\\u20E3" to "keycap: 4",
                "\\u0035\\uFE0F\\u20E3" to "keycap: 5",
                "\\u0036\\uFE0F\\u20E3" to "keycap: 6",
                "\\u0037\\uFE0F\\u20E3" to "keycap: 7",
                "\\u0038\\uFE0F\\u20E3" to "keycap: 8",
                "\\u0039\\uFE0F\\u20E3" to "keycap: 9",
                "\\uD83C\\uDFF4\\u200D\\u2620" to "pirate flag",
                "\\u263A\\uFE0F" to "smiling face",
                "\\u2639\\uFE0F" to "frowning face",
                "\\u2620\\uFE0F" to "skull and crossbones",
                "\\u2763\\uFE0F" to "heart exclamation",
                "\\u2764\\uFE0F" to "red heart",
                "\\uD83D\\uDD73\\uFE0F" to "hole",
                "\\uD83D\\uDDE8\\uFE0F" to "left speech bubble",
                "\\uD83D\\uDDEF\\uFE0F" to "right anger bubble",
                "\\uD83D\\uDC4B\\uD83C\\uDFFB" to "waving hand, light skin tone",
                "\\uD83D\\uDC4B\\uD83C\\uDFFC" to "waving hand, medium-light skin tone",
                "\\uD83D\\uDC4B\\uD83C\\uDFFD" to "waving hand, medium skin tone",
                "\\uD83D\\uDC4B\\uD83C\\uDFFE" to "waving hand, medium-dark skin tone",
                "\\uD83D\\uDC4B\\uD83C\\uDFFF" to "waving hand, dark skin tone",
                "\\uD83E\\uDD1A\\uD83C\\uDFFB" to "raised back of hand, light skin tone",
                "\\uD83E\\uDD1A\\uD83C\\uDFFC" to "raised back of hand, medium-light skin tone",
                "\\uD83E\\uDD1A\\uD83C\\uDFFD" to "raised back of hand, medium skin tone",
                "\\uD83E\\uDD1A\\uD83C\\uDFFE" to "raised back of hand, medium-dark skin tone",
                "\\uD83E\\uDD1A\\uD83C\\uDFFF" to "raised back of hand, dark skin tone",
                "\\uD83D\\uDD90\\uFE0F" to "hand with fingers splayed",
                "\\uD83D\\uDD90\\uD83C\\uDFFB" to "hand with fingers splayed, light skin tone",
                "\\uD83D\\uDD90\\uD83C\\uDFFC" to "hand with fingers splayed, medium-light skin tone",
                "\\uD83D\\uDD90\\uD83C\\uDFFD" to "hand with fingers splayed, medium skin tone",
                "\\uD83D\\uDD90\\uD83C\\uDFFE" to "hand with fingers splayed, medium-dark skin tone",
                "\\uD83D\\uDD90\\uD83C\\uDFFF" to "hand with fingers splayed, dark skin tone",
                "\\u270B\\uD83C\\uDFFB" to "raised hand, light skin tone",
                "\\u270B\\uD83C\\uDFFC" to "raised hand, medium-light skin tone",
                "\\u270B\\uD83C\\uDFFD" to "raised hand, medium skin tone",
                "\\u270B\\uD83C\\uDFFE" to "raised hand, medium-dark skin tone",
                "\\u270B\\uD83C\\uDFFF" to "raised hand, dark skin tone",
                "\\uD83D\\uDD96\\uD83C\\uDFFB" to "vulcan salute, light skin tone",
                "\\uD83D\\uDD96\\uD83C\\uDFFC" to "vulcan salute, medium-light skin tone",
                "\\uD83D\\uDD96\\uD83C\\uDFFD" to "vulcan salute, medium skin tone",
                "\\uD83D\\uDD96\\uD83C\\uDFFE" to "vulcan salute, medium-dark skin tone",
                "\\uD83D\\uDD96\\uD83C\\uDFFF" to "vulcan salute, dark skin tone",
                "\\uD83E\\uDEF1\\uD83C\\uDFFB" to "rightwards hand, light skin tone",
                "\\uD83E\\uDEF1\\uD83C\\uDFFC" to "rightwards hand, medium-light skin tone",
                "\\uD83E\\uDEF1\\uD83C\\uDFFD" to "rightwards hand, medium skin tone",
                "\\uD83E\\uDEF1\\uD83C\\uDFFE" to "rightwards hand, medium-dark skin tone",
                "\\uD83E\\uDEF1\\uD83C\\uDFFF" to "rightwards hand, dark skin tone",
                "\\uD83E\\uDEF2\\uD83C\\uDFFB" to "leftwards hand, light skin tone",
                "\\uD83E\\uDEF2\\uD83C\\uDFFC" to "leftwards hand, medium-light skin tone",
                "\\uD83E\\uDEF2\\uD83C\\uDFFD" to "leftwards hand, medium skin tone",
                "\\uD83E\\uDEF2\\uD83C\\uDFFE" to "leftwards hand, medium-dark skin tone",
                "\\uD83E\\uDEF2\\uD83C\\uDFFF" to "leftwards hand, dark skin tone",
                "\\uD83E\\uDEF3\\uD83C\\uDFFB" to "palm down hand, light skin tone",
                "\\uD83E\\uDEF3\\uD83C\\uDFFC" to "palm down hand, medium-light skin tone",
                "\\uD83E\\uDEF3\\uD83C\\uDFFD" to "palm down hand, medium skin tone",
                "\\uD83E\\uDEF3\\uD83C\\uDFFE" to "palm down hand, medium-dark skin tone",
                "\\uD83E\\uDEF3\\uD83C\\uDFFF" to "palm down hand, dark skin tone",
                "\\uD83E\\uDEF4\\uD83C\\uDFFB" to "palm up hand, light skin tone",
                "\\uD83E\\uDEF4\\uD83C\\uDFFC" to "palm up hand, medium-light skin tone",
                "\\uD83E\\uDEF4\\uD83C\\uDFFD" to "palm up hand, medium skin tone",
                "\\uD83E\\uDEF4\\uD83C\\uDFFE" to "palm up hand, medium-dark skin tone",
                "\\uD83E\\uDEF4\\uD83C\\uDFFF" to "palm up hand, dark skin tone",
                "\\uD83E\\uDEF7\\uD83C\\uDFFB" to "leftwards pushing hand, light skin tone",
                "\\uD83E\\uDEF7\\uD83C\\uDFFC" to "leftwards pushing hand, medium-light skin tone",
                "\\uD83E\\uDEF7\\uD83C\\uDFFD" to "leftwards pushing hand, medium skin tone",
                "\\uD83E\\uDEF7\\uD83C\\uDFFE" to "leftwards pushing hand, medium-dark skin tone",
                "\\uD83E\\uDEF7\\uD83C\\uDFFF" to "leftwards pushing hand, dark skin tone",
                "\\uD83E\\uDEF8\\uD83C\\uDFFB" to "rightwards pushing hand, light skin tone",
                "\\uD83E\\uDEF8\\uD83C\\uDFFC" to "rightwards pushing hand, medium-light skin tone",
                "\\uD83E\\uDEF8\\uD83C\\uDFFD" to "rightwards pushing hand, medium skin tone",
                "\\uD83E\\uDEF8\\uD83C\\uDFFE" to "rightwards pushing hand, medium-dark skin tone",
                "\\uD83E\\uDEF8\\uD83C\\uDFFF" to "rightwards pushing hand, dark skin tone",
                "\\uD83D\\uDC4C\\uD83C\\uDFFB" to "OK hand, light skin tone",
                "\\uD83D\\uDC4C\\uD83C\\uDFFC" to "OK hand, medium-light skin tone",
                "\\uD83D\\uDC4C\\uD83C\\uDFFD" to "OK hand, medium skin tone",
                "\\uD83D\\uDC4C\\uD83C\\uDFFE" to "OK hand, medium-dark skin tone",
                "\\uD83D\\uDC4C\\uD83C\\uDFFF" to "OK hand, dark skin tone",
                "\\uD83E\\uDD0C\\uD83C\\uDFFB" to "pinched fingers, light skin tone",
                "\\uD83E\\uDD0C\\uD83C\\uDFFC" to "pinched fingers, medium-light skin tone",
                "\\uD83E\\uDD0C\\uD83C\\uDFFD" to "pinched fingers, medium skin tone",
                "\\uD83E\\uDD0C\\uD83C\\uDFFE" to "pinched fingers, medium-dark skin tone",
                "\\uD83E\\uDD0C\\uD83C\\uDFFF" to "pinched fingers, dark skin tone",
                "\\uD83E\\uDD0F\\uD83C\\uDFFB" to "pinching hand, light skin tone",
                "\\uD83E\\uDD0F\\uD83C\\uDFFC" to "pinching hand, medium-light skin tone",
                "\\uD83E\\uDD0F\\uD83C\\uDFFD" to "pinching hand, medium skin tone",
                "\\uD83E\\uDD0F\\uD83C\\uDFFE" to "pinching hand, medium-dark skin tone",
                "\\uD83E\\uDD0F\\uD83C\\uDFFF" to "pinching hand, dark skin tone",
                "\\u270C\\uFE0F" to "victory hand",
                "\\u270C\\uD83C\\uDFFB" to "victory hand, light skin tone",
                "\\u270C\\uD83C\\uDFFC" to "victory hand, medium-light skin tone",
                "\\u270C\\uD83C\\uDFFD" to "victory hand, medium skin tone",
                "\\u270C\\uD83C\\uDFFE" to "victory hand, medium-dark skin tone",
                "\\u270C\\uD83C\\uDFFF" to "victory hand, dark skin tone",
                "\\uD83E\\uDD1E\\uD83C\\uDFFB" to "crossed fingers, light skin tone",
                "\\uD83E\\uDD1E\\uD83C\\uDFFC" to "crossed fingers, medium-light skin tone",
                "\\uD83E\\uDD1E\\uD83C\\uDFFD" to "crossed fingers, medium skin tone",
                "\\uD83E\\uDD1E\\uD83C\\uDFFE" to "crossed fingers, medium-dark skin tone",
                "\\uD83E\\uDD1E\\uD83C\\uDFFF" to "crossed fingers, dark skin tone",
                "\\uD83E\\uDEF0\\uD83C\\uDFFB" to "hand with index finger and thumb crossed, light skin tone",
                "\\uD83E\\uDEF0\\uD83C\\uDFFC" to "hand with index finger and thumb crossed, medium-light skin tone",
                "\\uD83E\\uDEF0\\uD83C\\uDFFD" to "hand with index finger and thumb crossed, medium skin tone",
                "\\uD83E\\uDEF0\\uD83C\\uDFFE" to "hand with index finger and thumb crossed, medium-dark skin tone",
                "\\uD83E\\uDEF0\\uD83C\\uDFFF" to "hand with index finger and thumb crossed, dark skin tone",
                "\\uD83E\\uDD1F\\uD83C\\uDFFB" to "love-you gesture, light skin tone",
                "\\uD83E\\uDD1F\\uD83C\\uDFFC" to "love-you gesture, medium-light skin tone",
                "\\uD83E\\uDD1F\\uD83C\\uDFFD" to "love-you gesture, medium skin tone",
                "\\uD83E\\uDD1F\\uD83C\\uDFFE" to "love-you gesture, medium-dark skin tone",
                "\\uD83E\\uDD1F\\uD83C\\uDFFF" to "love-you gesture, dark skin tone",
                "\\uD83E\\uDD18\\uD83C\\uDFFB" to "sign of the horns, light skin tone",
                "\\uD83E\\uDD18\\uD83C\\uDFFC" to "sign of the horns, medium-light skin tone",
                "\\uD83E\\uDD18\\uD83C\\uDFFD" to "sign of the horns, medium skin tone",
                "\\uD83E\\uDD18\\uD83C\\uDFFE" to "sign of the horns, medium-dark skin tone",
                "\\uD83E\\uDD18\\uD83C\\uDFFF" to "sign of the horns, dark skin tone",
                "\\uD83E\\uDD19\\uD83C\\uDFFB" to "call me hand, light skin tone",
                "\\uD83E\\uDD19\\uD83C\\uDFFC" to "call me hand, medium-light skin tone",
                "\\uD83E\\uDD19\\uD83C\\uDFFD" to "call me hand, medium skin tone",
                "\\uD83E\\uDD19\\uD83C\\uDFFE" to "call me hand, medium-dark skin tone",
                "\\uD83E\\uDD19\\uD83C\\uDFFF" to "call me hand, dark skin tone",
                "\\uD83D\\uDC48\\uD83C\\uDFFB" to "backhand index pointing left, light skin tone",
                "\\uD83D\\uDC48\\uD83C\\uDFFC" to "backhand index pointing left, medium-light skin tone",
                "\\uD83D\\uDC48\\uD83C\\uDFFD" to "backhand index pointing left, medium skin tone",
                "\\uD83D\\uDC48\\uD83C\\uDFFE" to "backhand index pointing left, medium-dark skin tone",
                "\\uD83D\\uDC48\\uD83C\\uDFFF" to "backhand index pointing left, dark skin tone",
                "\\uD83D\\uDC49\\uD83C\\uDFFB" to "backhand index pointing right, light skin tone",
                "\\uD83D\\uDC49\\uD83C\\uDFFC" to "backhand index pointing right, medium-light skin tone",
                "\\uD83D\\uDC49\\uD83C\\uDFFD" to "backhand index pointing right, medium skin tone",
                "\\uD83D\\uDC49\\uD83C\\uDFFE" to "backhand index pointing right, medium-dark skin tone",
                "\\uD83D\\uDC49\\uD83C\\uDFFF" to "backhand index pointing right, dark skin tone",
                "\\uD83D\\uDC46\\uD83C\\uDFFB" to "backhand index pointing up, light skin tone",
                "\\uD83D\\uDC46\\uD83C\\uDFFC" to "backhand index pointing up, medium-light skin tone",
                "\\uD83D\\uDC46\\uD83C\\uDFFD" to "backhand index pointing up, medium skin tone",
                "\\uD83D\\uDC46\\uD83C\\uDFFE" to "backhand index pointing up, medium-dark skin tone",
                "\\uD83D\\uDC46\\uD83C\\uDFFF" to "backhand index pointing up, dark skin tone",
                "\\uD83D\\uDD95\\uD83C\\uDFFB" to "middle finger, light skin tone",
                "\\uD83D\\uDD95\\uD83C\\uDFFC" to "middle finger, medium-light skin tone",
                "\\uD83D\\uDD95\\uD83C\\uDFFD" to "middle finger, medium skin tone",
                "\\uD83D\\uDD95\\uD83C\\uDFFE" to "middle finger, medium-dark skin tone",
                "\\uD83D\\uDD95\\uD83C\\uDFFF" to "middle finger, dark skin tone",
                "\\uD83D\\uDC47\\uD83C\\uDFFB" to "backhand index pointing down, light skin tone",
                "\\uD83D\\uDC47\\uD83C\\uDFFC" to "backhand index pointing down, medium-light skin tone",
                "\\uD83D\\uDC47\\uD83C\\uDFFD" to "backhand index pointing down, medium skin tone",
                "\\uD83D\\uDC47\\uD83C\\uDFFE" to "backhand index pointing down, medium-dark skin tone",
                "\\uD83D\\uDC47\\uD83C\\uDFFF" to "backhand index pointing down, dark skin tone",
                "\\u261D\\uFE0F" to "index pointing up",
                "\\u261D\\uD83C\\uDFFB" to "index pointing up, light skin tone",
                "\\u261D\\uD83C\\uDFFC" to "index pointing up, medium-light skin tone",
                "\\u261D\\uD83C\\uDFFD" to "index pointing up, medium skin tone",
                "\\u261D\\uD83C\\uDFFE" to "index pointing up, medium-dark skin tone",
                "\\u261D\\uD83C\\uDFFF" to "index pointing up, dark skin tone",
                "\\uD83E\\uDEF5\\uD83C\\uDFFB" to "index pointing at the viewer, light skin tone",
                "\\uD83E\\uDEF5\\uD83C\\uDFFC" to "index pointing at the viewer, medium-light skin tone",
                "\\uD83E\\uDEF5\\uD83C\\uDFFD" to "index pointing at the viewer, medium skin tone",
                "\\uD83E\\uDEF5\\uD83C\\uDFFE" to "index pointing at the viewer, medium-dark skin tone",
                "\\uD83E\\uDEF5\\uD83C\\uDFFF" to "index pointing at the viewer, dark skin tone",
                "\\uD83D\\uDC4D\\uD83C\\uDFFB" to "thumbs up, light skin tone",
                "\\uD83D\\uDC4D\\uD83C\\uDFFC" to "thumbs up, medium-light skin tone",
                "\\uD83D\\uDC4D\\uD83C\\uDFFD" to "thumbs up, medium skin tone",
                "\\uD83D\\uDC4D\\uD83C\\uDFFE" to "thumbs up, medium-dark skin tone",
                "\\uD83D\\uDC4D\\uD83C\\uDFFF" to "thumbs up, dark skin tone",
                "\\uD83D\\uDC4E\\uD83C\\uDFFB" to "thumbs down, light skin tone",
                "\\uD83D\\uDC4E\\uD83C\\uDFFC" to "thumbs down, medium-light skin tone",
                "\\uD83D\\uDC4E\\uD83C\\uDFFD" to "thumbs down, medium skin tone",
                "\\uD83D\\uDC4E\\uD83C\\uDFFE" to "thumbs down, medium-dark skin tone",
                "\\uD83D\\uDC4E\\uD83C\\uDFFF" to "thumbs down, dark skin tone",
                "\\uD83E\\uDEF9\\uD83C\\uDFFB" to "leftwards thumb sign, light skin tone",
                "\\uD83E\\uDEF9\\uD83C\\uDFFC" to "leftwards thumb sign, medium-light skin tone",
                "\\uD83E\\uDEF9\\uD83C\\uDFFD" to "leftwards thumb sign, medium skin tone",
                "\\uD83E\\uDEF9\\uD83C\\uDFFE" to "leftwards thumb sign, medium-dark skin tone",
                "\\uD83E\\uDEF9\\uD83C\\uDFFF" to "leftwards thumb sign, dark skin tone",
                "\\uD83E\\uDEFA\\uD83C\\uDFFB" to "rightwards thumb sign, light skin tone",
                "\\uD83E\\uDEFA\\uD83C\\uDFFC" to "rightwards thumb sign, medium-light skin tone",
                "\\uD83E\\uDEFA\\uD83C\\uDFFD" to "rightwards thumb sign, medium skin tone",
                "\\uD83E\\uDEFA\\uD83C\\uDFFE" to "rightwards thumb sign, medium-dark skin tone",
                "\\uD83E\\uDEFA\\uD83C\\uDFFF" to "rightwards thumb sign, dark skin tone",
                "\\u270A\\uD83C\\uDFFB" to "raised fist, light skin tone",
                "\\u270A\\uD83C\\uDFFC" to "raised fist, medium-light skin tone",
                "\\u270A\\uD83C\\uDFFD" to "raised fist, medium skin tone",
                "\\u270A\\uD83C\\uDFFE" to "raised fist, medium-dark skin tone",
                "\\u270A\\uD83C\\uDFFF" to "raised fist, dark skin tone",
                "\\uD83D\\uDC4A\\uD83C\\uDFFB" to "oncoming fist, light skin tone",
                "\\uD83D\\uDC4A\\uD83C\\uDFFC" to "oncoming fist, medium-light skin tone",
                "\\uD83D\\uDC4A\\uD83C\\uDFFD" to "oncoming fist, medium skin tone",
                "\\uD83D\\uDC4A\\uD83C\\uDFFE" to "oncoming fist, medium-dark skin tone",
                "\\uD83D\\uDC4A\\uD83C\\uDFFF" to "oncoming fist, dark skin tone",
                "\\uD83E\\uDD1B\\uD83C\\uDFFB" to "left-facing fist, light skin tone",
                "\\uD83E\\uDD1B\\uD83C\\uDFFC" to "left-facing fist, medium-light skin tone",
                "\\uD83E\\uDD1B\\uD83C\\uDFFD" to "left-facing fist, medium skin tone",
                "\\uD83E\\uDD1B\\uD83C\\uDFFE" to "left-facing fist, medium-dark skin tone",
                "\\uD83E\\uDD1B\\uD83C\\uDFFF" to "left-facing fist, dark skin tone",
                "\\uD83E\\uDD1C\\uD83C\\uDFFB" to "right-facing fist, light skin tone",
                "\\uD83E\\uDD1C\\uD83C\\uDFFC" to "right-facing fist, medium-light skin tone",
                "\\uD83E\\uDD1C\\uD83C\\uDFFD" to "right-facing fist, medium skin tone",
                "\\uD83E\\uDD1C\\uD83C\\uDFFE" to "right-facing fist, medium-dark skin tone",
                "\\uD83E\\uDD1C\\uD83C\\uDFFF" to "right-facing fist, dark skin tone",
                "\\uD83D\\uDC4F\\uD83C\\uDFFB" to "clapping hands, light skin tone",
                "\\uD83D\\uDC4F\\uD83C\\uDFFC" to "clapping hands, medium-light skin tone",
                "\\uD83D\\uDC4F\\uD83C\\uDFFD" to "clapping hands, medium skin tone",
                "\\uD83D\\uDC4F\\uD83C\\uDFFE" to "clapping hands, medium-dark skin tone",
                "\\uD83D\\uDC4F\\uD83C\\uDFFF" to "clapping hands, dark skin tone",
                "\\uD83D\\uDE4C\\uD83C\\uDFFB" to "raising hands, light skin tone",
                "\\uD83D\\uDE4C\\uD83C\\uDFFC" to "raising hands, medium-light skin tone",
                "\\uD83D\\uDE4C\\uD83C\\uDFFD" to "raising hands, medium skin tone",
                "\\uD83D\\uDE4C\\uD83C\\uDFFE" to "raising hands, medium-dark skin tone",
                "\\uD83D\\uDE4C\\uD83C\\uDFFF" to "raising hands, dark skin tone",
                "\\uD83E\\uDEF6\\uD83C\\uDFFB" to "heart hands, light skin tone",
                "\\uD83E\\uDEF6\\uD83C\\uDFFC" to "heart hands, medium-light skin tone",
                "\\uD83E\\uDEF6\\uD83C\\uDFFD" to "heart hands, medium skin tone",
                "\\uD83E\\uDEF6\\uD83C\\uDFFE" to "heart hands, medium-dark skin tone",
                "\\uD83E\\uDEF6\\uD83C\\uDFFF" to "heart hands, dark skin tone",
                "\\uD83D\\uDC50\\uD83C\\uDFFB" to "open hands, light skin tone",
                "\\uD83D\\uDC50\\uD83C\\uDFFC" to "open hands, medium-light skin tone",
                "\\uD83D\\uDC50\\uD83C\\uDFFD" to "open hands, medium skin tone",
                "\\uD83D\\uDC50\\uD83C\\uDFFE" to "open hands, medium-dark skin tone",
                "\\uD83D\\uDC50\\uD83C\\uDFFF" to "open hands, dark skin tone",
                "\\uD83E\\uDD32\\uD83C\\uDFFB" to "palms up together, light skin tone",
                "\\uD83E\\uDD32\\uD83C\\uDFFC" to "palms up together, medium-light skin tone",
                "\\uD83E\\uDD32\\uD83C\\uDFFD" to "palms up together, medium skin tone",
                "\\uD83E\\uDD32\\uD83C\\uDFFE" to "palms up together, medium-dark skin tone",
                "\\uD83E\\uDD32\\uD83C\\uDFFF" to "palms up together, dark skin tone",
                "\\uD83E\\uDD1D\\uD83C\\uDFFB" to "handshake, light skin tone",
                "\\uD83E\\uDD1D\\uD83C\\uDFFC" to "handshake, medium-light skin tone",
                "\\uD83E\\uDD1D\\uD83C\\uDFFD" to "handshake, medium skin tone",
                "\\uD83E\\uDD1D\\uD83C\\uDFFE" to "handshake, medium-dark skin tone",
                "\\uD83E\\uDD1D\\uD83C\\uDFFF" to "handshake, dark skin tone",
                "\\uD83D\\uDE4F\\uD83C\\uDFFB" to "folded hands, light skin tone",
                "\\uD83D\\uDE4F\\uD83C\\uDFFC" to "folded hands, medium-light skin tone",
                "\\uD83D\\uDE4F\\uD83C\\uDFFD" to "folded hands, medium skin tone",
                "\\uD83D\\uDE4F\\uD83C\\uDFFE" to "folded hands, medium-dark skin tone",
                "\\uD83D\\uDE4F\\uD83C\\uDFFF" to "folded hands, dark skin tone",
                "\\u270D\\uFE0F" to "writing hand",
                "\\u270D\\uD83C\\uDFFB" to "writing hand, light skin tone",
                "\\u270D\\uD83C\\uDFFC" to "writing hand, medium-light skin tone",
                "\\u270D\\uD83C\\uDFFD" to "writing hand, medium skin tone",
                "\\u270D\\uD83C\\uDFFE" to "writing hand, medium-dark skin tone",
                "\\u270D\\uD83C\\uDFFF" to "writing hand, dark skin tone",
                "\\uD83D\\uDC85\\uD83C\\uDFFB" to "nail polish, light skin tone",
                "\\uD83D\\uDC85\\uD83C\\uDFFC" to "nail polish, medium-light skin tone",
                "\\uD83D\\uDC85\\uD83C\\uDFFD" to "nail polish, medium skin tone",
                "\\uD83D\\uDC85\\uD83C\\uDFFE" to "nail polish, medium-dark skin tone",
                "\\uD83D\\uDC85\\uD83C\\uDFFF" to "nail polish, dark skin tone",
                "\\uD83E\\uDD33\\uD83C\\uDFFB" to "selfie, light skin tone",
                "\\uD83E\\uDD33\\uD83C\\uDFFC" to "selfie, medium-light skin tone",
                "\\uD83E\\uDD33\\uD83C\\uDFFD" to "selfie, medium skin tone",
                "\\uD83E\\uDD33\\uD83C\\uDFFE" to "selfie, medium-dark skin tone",
                "\\uD83E\\uDD33\\uD83C\\uDFFF" to "selfie, dark skin tone",
                "\\uD83D\\uDCAA\\uD83C\\uDFFB" to "flexed biceps, light skin tone",
                "\\uD83D\\uDCAA\\uD83C\\uDFFC" to "flexed biceps, medium-light skin tone",
                "\\uD83D\\uDCAA\\uD83C\\uDFFD" to "flexed biceps, medium skin tone",
                "\\uD83D\\uDCAA\\uD83C\\uDFFE" to "flexed biceps, medium-dark skin tone",
                "\\uD83D\\uDCAA\\uD83C\\uDFFF" to "flexed biceps, dark skin tone",
                "\\uD83E\\uDDB5\\uD83C\\uDFFB" to "leg, light skin tone",
                "\\uD83E\\uDDB5\\uD83C\\uDFFC" to "leg, medium-light skin tone",
                "\\uD83E\\uDDB5\\uD83C\\uDFFD" to "leg, medium skin tone",
                "\\uD83E\\uDDB5\\uD83C\\uDFFE" to "leg, medium-dark skin tone",
                "\\uD83E\\uDDB5\\uD83C\\uDFFF" to "leg, dark skin tone",
                "\\uD83E\\uDDB6\\uD83C\\uDFFB" to "foot, light skin tone",
                "\\uD83E\\uDDB6\\uD83C\\uDFFC" to "foot, medium-light skin tone",
                "\\uD83E\\uDDB6\\uD83C\\uDFFD" to "foot, medium skin tone",
                "\\uD83E\\uDDB6\\uD83C\\uDFFE" to "foot, medium-dark skin tone",
                "\\uD83E\\uDDB6\\uD83C\\uDFFF" to "foot, dark skin tone",
                "\\uD83D\\uDC42\\uD83C\\uDFFB" to "ear, light skin tone",
                "\\uD83D\\uDC42\\uD83C\\uDFFC" to "ear, medium-light skin tone",
                "\\uD83D\\uDC42\\uD83C\\uDFFD" to "ear, medium skin tone",
                "\\uD83D\\uDC42\\uD83C\\uDFFE" to "ear, medium-dark skin tone",
                "\\uD83D\\uDC42\\uD83C\\uDFFF" to "ear, dark skin tone",
                "\\uD83E\\uDDBB\\uD83C\\uDFFB" to "ear with hearing aid, light skin tone",
                "\\uD83E\\uDDBB\\uD83C\\uDFFC" to "ear with hearing aid, medium-light skin tone",
                "\\uD83E\\uDDBB\\uD83C\\uDFFD" to "ear with hearing aid, medium skin tone",
                "\\uD83E\\uDDBB\\uD83C\\uDFFE" to "ear with hearing aid, medium-dark skin tone",
                "\\uD83E\\uDDBB\\uD83C\\uDFFF" to "ear with hearing aid, dark skin tone",
                "\\uD83D\\uDC43\\uD83C\\uDFFB" to "nose, light skin tone",
                "\\uD83D\\uDC43\\uD83C\\uDFFC" to "nose, medium-light skin tone",
                "\\uD83D\\uDC43\\uD83C\\uDFFD" to "nose, medium skin tone",
                "\\uD83D\\uDC43\\uD83C\\uDFFE" to "nose, medium-dark skin tone",
                "\\uD83D\\uDC43\\uD83C\\uDFFF" to "nose, dark skin tone",
                "\\uD83D\\uDC41\\uFE0F" to "eye",
                "\\uD83D\\uDC76\\uD83C\\uDFFB" to "baby, light skin tone",
                "\\uD83D\\uDC76\\uD83C\\uDFFC" to "baby, medium-light skin tone",
                "\\uD83D\\uDC76\\uD83C\\uDFFD" to "baby, medium skin tone",
                "\\uD83D\\uDC76\\uD83C\\uDFFE" to "baby, medium-dark skin tone",
                "\\uD83D\\uDC76\\uD83C\\uDFFF" to "baby, dark skin tone",
                "\\uD83E\\uDDD2\\uD83C\\uDFFB" to "child, light skin tone",
                "\\uD83E\\uDDD2\\uD83C\\uDFFC" to "child, medium-light skin tone",
                "\\uD83E\\uDDD2\\uD83C\\uDFFD" to "child, medium skin tone",
                "\\uD83E\\uDDD2\\uD83C\\uDFFE" to "child, medium-dark skin tone",
                "\\uD83E\\uDDD2\\uD83C\\uDFFF" to "child, dark skin tone",
                "\\uD83D\\uDC66\\uD83C\\uDFFB" to "boy, light skin tone",
                "\\uD83D\\uDC66\\uD83C\\uDFFC" to "boy, medium-light skin tone",
                "\\uD83D\\uDC66\\uD83C\\uDFFD" to "boy, medium skin tone",
                "\\uD83D\\uDC66\\uD83C\\uDFFE" to "boy, medium-dark skin tone",
                "\\uD83D\\uDC66\\uD83C\\uDFFF" to "boy, dark skin tone",
                "\\uD83D\\uDC67\\uD83C\\uDFFB" to "girl, light skin tone",
                "\\uD83D\\uDC67\\uD83C\\uDFFC" to "girl, medium-light skin tone",
                "\\uD83D\\uDC67\\uD83C\\uDFFD" to "girl, medium skin tone",
                "\\uD83D\\uDC67\\uD83C\\uDFFE" to "girl, medium-dark skin tone",
                "\\uD83D\\uDC67\\uD83C\\uDFFF" to "girl, dark skin tone",
                "\\uD83E\\uDDD1\\uD83C\\uDFFB" to "person, light skin tone",
                "\\uD83E\\uDDD1\\uD83C\\uDFFC" to "person, medium-light skin tone",
                "\\uD83E\\uDDD1\\uD83C\\uDFFD" to "person, medium skin tone",
                "\\uD83E\\uDDD1\\uD83C\\uDFFE" to "person, medium-dark skin tone",
                "\\uD83E\\uDDD1\\uD83C\\uDFFF" to "person, dark skin tone",
                "\\uD83D\\uDC71\\uD83C\\uDFFB" to "person: blond hair, light skin tone",
                "\\uD83D\\uDC71\\uD83C\\uDFFC" to "person: blond hair, medium-light skin tone",
                "\\uD83D\\uDC71\\uD83C\\uDFFD" to "person: blond hair, medium skin tone",
                "\\uD83D\\uDC71\\uD83C\\uDFFE" to "person: blond hair, medium-dark skin tone",
                "\\uD83D\\uDC71\\uD83C\\uDFFF" to "person: blond hair, dark skin tone",
                "\\uD83D\\uDC68\\uD83C\\uDFFB" to "man, light skin tone",
                "\\uD83D\\uDC68\\uD83C\\uDFFC" to "man, medium-light skin tone",
                "\\uD83D\\uDC68\\uD83C\\uDFFD" to "man, medium skin tone",
                "\\uD83D\\uDC68\\uD83C\\uDFFE" to "man, medium-dark skin tone",
                "\\uD83D\\uDC68\\uD83C\\uDFFF" to "man, dark skin tone",
                "\\uD83E\\uDDD4\\uD83C\\uDFFB" to "person: beard, light skin tone",
                "\\uD83E\\uDDD4\\uD83C\\uDFFC" to "person: beard, medium-light skin tone",
                "\\uD83E\\uDDD4\\uD83C\\uDFFD" to "person: beard, medium skin tone",
                "\\uD83E\\uDDD4\\uD83C\\uDFFE" to "person: beard, medium-dark skin tone",
                "\\uD83E\\uDDD4\\uD83C\\uDFFF" to "person: beard, dark skin tone",
                "\\uD83D\\uDC69\\uD83C\\uDFFB" to "woman, light skin tone",
                "\\uD83D\\uDC69\\uD83C\\uDFFC" to "woman, medium-light skin tone",
                "\\uD83D\\uDC69\\uD83C\\uDFFD" to "woman, medium skin tone",
                "\\uD83D\\uDC69\\uD83C\\uDFFE" to "woman, medium-dark skin tone",
                "\\uD83D\\uDC69\\uD83C\\uDFFF" to "woman, dark skin tone",
                "\\uD83E\\uDDD3\\uD83C\\uDFFB" to "older person, light skin tone",
                "\\uD83E\\uDDD3\\uD83C\\uDFFC" to "older person, medium-light skin tone",
                "\\uD83E\\uDDD3\\uD83C\\uDFFD" to "older person, medium skin tone",
                "\\uD83E\\uDDD3\\uD83C\\uDFFE" to "older person, medium-dark skin tone",
                "\\uD83E\\uDDD3\\uD83C\\uDFFF" to "older person, dark skin tone",
                "\\uD83D\\uDC74\\uD83C\\uDFFB" to "old man, light skin tone",
                "\\uD83D\\uDC74\\uD83C\\uDFFC" to "old man, medium-light skin tone",
                "\\uD83D\\uDC74\\uD83C\\uDFFD" to "old man, medium skin tone",
                "\\uD83D\\uDC74\\uD83C\\uDFFE" to "old man, medium-dark skin tone",
                "\\uD83D\\uDC74\\uD83C\\uDFFF" to "old man, dark skin tone",
                "\\uD83D\\uDC75\\uD83C\\uDFFB" to "old woman, light skin tone",
                "\\uD83D\\uDC75\\uD83C\\uDFFC" to "old woman, medium-light skin tone",
                "\\uD83D\\uDC75\\uD83C\\uDFFD" to "old woman, medium skin tone",
                "\\uD83D\\uDC75\\uD83C\\uDFFE" to "old woman, medium-dark skin tone",
                "\\uD83D\\uDC75\\uD83C\\uDFFF" to "old woman, dark skin tone",
                "\\uD83D\\uDE4D\\uD83C\\uDFFB" to "person frowning, light skin tone",
                "\\uD83D\\uDE4D\\uD83C\\uDFFC" to "person frowning, medium-light skin tone",
                "\\uD83D\\uDE4D\\uD83C\\uDFFD" to "person frowning, medium skin tone",
                "\\uD83D\\uDE4D\\uD83C\\uDFFE" to "person frowning, medium-dark skin tone",
                "\\uD83D\\uDE4D\\uD83C\\uDFFF" to "person frowning, dark skin tone",
                "\\uD83D\\uDE4E\\uD83C\\uDFFB" to "person pouting, light skin tone",
                "\\uD83D\\uDE4E\\uD83C\\uDFFC" to "person pouting, medium-light skin tone",
                "\\uD83D\\uDE4E\\uD83C\\uDFFD" to "person pouting, medium skin tone",
                "\\uD83D\\uDE4E\\uD83C\\uDFFE" to "person pouting, medium-dark skin tone",
                "\\uD83D\\uDE4E\\uD83C\\uDFFF" to "person pouting, dark skin tone",
                "\\uD83D\\uDE45\\uD83C\\uDFFB" to "person gesturing NO, light skin tone",
                "\\uD83D\\uDE45\\uD83C\\uDFFC" to "person gesturing NO, medium-light skin tone",
                "\\uD83D\\uDE45\\uD83C\\uDFFD" to "person gesturing NO, medium skin tone",
                "\\uD83D\\uDE45\\uD83C\\uDFFE" to "person gesturing NO, medium-dark skin tone",
)
