package com.xw.vvtts.utils

internal val EMOJI_10: Map<String, String> = mapOf(
                "\\uD83D\\uDD67" to "twelve-thirty",
                "\\uD83D\\uDD50" to "one o’clock",
                "\\uD83D\\uDD5C" to "one-thirty",
                "\\uD83D\\uDD51" to "two o’clock",
                "\\uD83D\\uDD5D" to "two-thirty",
                "\\uD83D\\uDD52" to "three o’clock",
                "\\uD83D\\uDD5E" to "three-thirty",
                "\\uD83D\\uDD53" to "four o’clock",
                "\\uD83D\\uDD5F" to "four-thirty",
                "\\uD83D\\uDD54" to "five o’clock",
                "\\uD83D\\uDD60" to "five-thirty",
                "\\uD83D\\uDD55" to "six o’clock",
                "\\uD83D\\uDD61" to "six-thirty",
                "\\uD83D\\uDD56" to "seven o’clock",
                "\\uD83D\\uDD62" to "seven-thirty",
                "\\uD83D\\uDD57" to "eight o’clock",
                "\\uD83D\\uDD63" to "eight-thirty",
                "\\uD83D\\uDD58" to "nine o’clock",
                "\\uD83D\\uDD64" to "nine-thirty",
                "\\uD83D\\uDD59" to "ten o’clock",
                "\\uD83D\\uDD65" to "ten-thirty",
                "\\uD83D\\uDD5A" to "eleven o’clock",
                "\\uD83D\\uDD66" to "eleven-thirty",
                "\\uD83C\\uDF11" to "new moon",
                "\\uD83C\\uDF12" to "waxing crescent moon",
                "\\uD83C\\uDF13" to "first quarter moon",
                "\\uD83C\\uDF14" to "waxing gibbous moon",
                "\\uD83C\\uDF15" to "full moon",
                "\\uD83C\\uDF16" to "waning gibbous moon",
                "\\uD83C\\uDF17" to "last quarter moon",
                "\\uD83C\\uDF18" to "waning crescent moon",
                "\\uD83C\\uDF19" to "crescent moon",
                "\\uD83C\\uDF1A" to "new moon face",
                "\\uD83C\\uDF1B" to "first quarter moon face",
                "\\uD83C\\uDF1C" to "last quarter moon face",
                "\\uD83C\\uDF1D" to "full moon face",
                "\\uD83C\\uDF1E" to "sun with face",
                "\\uD83E\\uDE90" to "ringed planet",
                "\\u2B50" to "star",
                "\\uD83C\\uDF1F" to "glowing star",
                "\\uD83C\\uDF20" to "shooting star",
                "\\uD83C\\uDF0C" to "milky way",
                "\\u26C5" to "sun behind cloud",
                "\\uD83C\\uDF00" to "cyclone",
                "\\uD83C\\uDF08" to "rainbow",
                "\\uD83C\\uDF02" to "closed umbrella",
                "\\u2614" to "umbrella with rain drops",
                "\\u26A1" to "high voltage",
                "\\u26C4" to "snowman without snow",
                "\\uD83E\\uDE8B" to "meteor",
                "\\uD83D\\uDD25" to "fire",
                "\\uD83D\\uDCA7" to "droplet",
                "\\uD83C\\uDF0A" to "water wave",
                "\\uD83C\\uDF83" to "jack-o-lantern",
                "\\uD83C\\uDF84" to "Christmas tree",
                "\\uD83C\\uDF86" to "fireworks",
                "\\uD83C\\uDF87" to "sparkler",
                "\\uD83E\\uDDE8" to "firecracker",
                "\\u2728" to "sparkles",
                "\\uD83C\\uDF88" to "balloon",
                "\\uD83C\\uDF89" to "party popper",
                "\\uD83C\\uDF8A" to "confetti ball",
                "\\uD83C\\uDF8B" to "tanabata tree",
                "\\uD83C\\uDF8D" to "pine decoration",
                "\\uD83C\\uDF8E" to "Japanese dolls",
                "\\uD83C\\uDF8F" to "carp streamer",
                "\\uD83C\\uDF90" to "wind chime",
                "\\uD83C\\uDF91" to "moon viewing ceremony",
                "\\uD83E\\uDDE7" to "red envelope",
                "\\uD83C\\uDF80" to "ribbon",
                "\\uD83C\\uDF81" to "wrapped gift",
                "\\uD83C\\uDFAB" to "ticket",
                "\\uD83C\\uDFC6" to "trophy",
                "\\uD83C\\uDFC5" to "sports medal",
                "\\uD83E\\uDD47" to "1st place medal",
                "\\uD83E\\uDD48" to "2nd place medal",
                "\\uD83E\\uDD49" to "3rd place medal",
                "\\u26BD" to "soccer ball",
                "\\u26BE" to "baseball",
                "\\uD83E\\uDD4E" to "softball",
                "\\uD83C\\uDFC0" to "basketball",
                "\\uD83C\\uDFD0" to "volleyball",
                "\\uD83C\\uDFC8" to "american football",
                "\\uD83C\\uDFC9" to "rugby football",
                "\\uD83C\\uDFBE" to "tennis",
                "\\uD83E\\uDD4F" to "flying disc",
                "\\uD83C\\uDFB3" to "bowling",
                "\\uD83C\\uDFCF" to "cricket game",
                "\\uD83C\\uDFD1" to "field hockey",
                "\\uD83C\\uDFD2" to "ice hockey",
                "\\uD83E\\uDD4D" to "lacrosse",
                "\\uD83C\\uDFD3" to "ping pong",
                "\\uD83C\\uDFF8" to "badminton",
                "\\uD83E\\uDD4A" to "boxing glove",
                "\\uD83E\\uDD4B" to "martial arts uniform",
                "\\uD83E\\uDD45" to "goal net",
                "\\u26F3" to "flag in hole",
                "\\uD83C\\uDFA3" to "fishing pole",
                "\\uD83E\\uDD3F" to "diving mask",
                "\\uD83C\\uDFBD" to "running shirt",
                "\\uD83C\\uDFBF" to "skis",
                "\\uD83D\\uDEF7" to "sled",
                "\\uD83E\\uDD4C" to "curling stone",
                "\\uD83C\\uDFAF" to "bullseye",
                "\\uD83E\\uDE80" to "yo-yo",
                "\\uD83E\\uDE81" to "kite",
                "\\uD83D\\uDD2B" to "water pistol",
                "\\uD83C\\uDFB1" to "pool 8 ball",
                "\\uD83D\\uDD2E" to "crystal ball",
                "\\uD83E\\uDE84" to "magic wand",
                "\\uD83C\\uDFAE" to "video game",
                "\\uD83C\\uDFB0" to "slot machine",
                "\\uD83C\\uDFB2" to "game die",
                "\\uD83E\\uDDE9" to "puzzle piece",
                "\\uD83E\\uDDF8" to "teddy bear",
                "\\uD83E\\uDE85" to "piñata",
                "\\uD83E\\uDEA9" to "mirror ball",
                "\\uD83E\\uDE86" to "nesting dolls",
                "\\uD83C\\uDCCF" to "joker",
                "\\uD83C\\uDC04" to "mahjong red dragon",
                "\\uD83C\\uDFB4" to "flower playing cards",
                "\\uD83C\\uDFAD" to "performing arts",
                "\\uD83C\\uDFA8" to "artist palette",
                "\\uD83E\\uDDF5" to "thread",
                "\\uD83E\\uDEA1" to "sewing needle",
                "\\uD83E\\uDDF6" to "yarn",
                "\\uD83E\\uDEA2" to "knot",
                "\\uD83D\\uDC53" to "glasses",
                "\\uD83E\\uDD7D" to "goggles",
                "\\uD83E\\uDD7C" to "lab coat",
                "\\uD83E\\uDDBA" to "safety vest",
                "\\uD83D\\uDC54" to "necktie",
                "\\uD83D\\uDC55" to "t-shirt",
                "\\uD83D\\uDC56" to "jeans",
                "\\uD83E\\uDDE3" to "scarf",
                "\\uD83E\\uDDE4" to "gloves",
                "\\uD83E\\uDDE5" to "coat",
                "\\uD83E\\uDDE6" to "socks",
                "\\uD83D\\uDC57" to "dress",
                "\\uD83D\\uDC58" to "kimono",
                "\\uD83E\\uDD7B" to "sari",
                "\\uD83E\\uDE71" to "one-piece swimsuit",
                "\\uD83E\\uDE72" to "briefs",
                "\\uD83E\\uDE73" to "shorts",
                "\\uD83D\\uDC59" to "bikini",
                "\\uD83D\\uDC5A" to "woman’s clothes",
                "\\uD83E\\uDEAD" to "folding hand fan",
                "\\uD83D\\uDC5B" to "purse",
                "\\uD83D\\uDC5C" to "handbag",
                "\\uD83D\\uDC5D" to "clutch bag",
                "\\uD83C\\uDF92" to "backpack",
                "\\uD83E\\uDE74" to "thong sandal",
                "\\uD83D\\uDC5E" to "man’s shoe",
                "\\uD83D\\uDC5F" to "running shoe",
                "\\uD83E\\uDD7E" to "hiking boot",
                "\\uD83E\\uDD7F" to "flat shoe",
                "\\uD83D\\uDC60" to "high-heeled shoe",
                "\\uD83D\\uDC61" to "woman’s sandal",
                "\\uD83E\\uDE70" to "ballet shoes",
                "\\uD83D\\uDC62" to "woman’s boot",
                "\\uD83E\\uDEAE" to "hair pick",
                "\\uD83D\\uDC51" to "crown",
                "\\uD83D\\uDC52" to "woman’s hat",
                "\\uD83C\\uDFA9" to "top hat",
                "\\uD83C\\uDF93" to "graduation cap",
                "\\uD83E\\uDDE2" to "billed cap",
                "\\uD83E\\uDE96" to "military helmet",
                "\\uD83D\\uDCFF" to "prayer beads",
                "\\uD83D\\uDC84" to "lipstick",
                "\\uD83D\\uDC8D" to "ring",
                "\\uD83D\\uDC8E" to "gem stone",
                "\\uD83D\\uDD07" to "muted speaker",
                "\\uD83D\\uDD08" to "speaker low volume",
                "\\uD83D\\uDD09" to "speaker medium volume",
                "\\uD83D\\uDD0A" to "speaker high volume",
                "\\uD83D\\uDCE2" to "loudspeaker",
                "\\uD83D\\uDCE3" to "megaphone",
                "\\uD83D\\uDCEF" to "postal horn",
                "\\uD83D\\uDD14" to "bell",
                "\\uD83D\\uDD15" to "bell with slash",
                "\\uD83C\\uDFBC" to "musical score",
                "\\uD83C\\uDFB5" to "musical note",
                "\\uD83C\\uDFB6" to "musical notes",
                "\\uD83C\\uDFA4" to "microphone",
                "\\uD83C\\uDFA7" to "headphone",
                "\\uD83D\\uDCFB" to "radio",
                "\\uD83C\\uDFB7" to "saxophone",
                "\\uD83C\\uDFBA" to "trumpet",
                "\\uD83E\\uDE8A" to "trombone",
                "\\uD83E\\uDE97" to "accordion",
                "\\uD83C\\uDFB8" to "guitar",
                "\\uD83C\\uDFB9" to "musical keyboard",
                "\\uD83C\\uDFBB" to "violin",
                "\\uD83E\\uDE95" to "banjo",
                "\\uD83E\\uDD41" to "drum",
                "\\uD83E\\uDE98" to "long drum",
                "\\uD83E\\uDE87" to "maracas",
                "\\uD83E\\uDE88" to "flute",
                "\\uD83E\\uDE89" to "harp",
                "\\uD83D\\uDCF1" to "mobile phone",
                "\\uD83D\\uDCF2" to "mobile phone with arrow",
                "\\uD83D\\uDCDE" to "telephone receiver",
                "\\uD83D\\uDCDF" to "pager",
                "\\uD83D\\uDCE0" to "fax machine",
                "\\uD83D\\uDD0B" to "battery",
                "\\uD83E\\uDEAB" to "low battery",
                "\\uD83D\\uDD0C" to "electric plug",
                "\\uD83D\\uDCBB" to "laptop",
                "\\uD83D\\uDCBD" to "computer disk",
                "\\uD83D\\uDCBE" to "floppy disk",
                "\\uD83D\\uDCBF" to "optical disk",
                "\\uD83D\\uDCC0" to "dvd",
                "\\uD83E\\uDDEE" to "abacus",
                "\\uD83C\\uDFA5" to "movie camera",
                "\\uD83C\\uDFAC" to "clapper board",
                "\\uD83D\\uDCFA" to "television",
                "\\uD83D\\uDCF7" to "camera",
                "\\uD83D\\uDCF8" to "camera with flash",
                "\\uD83D\\uDCF9" to "video camera",
                "\\uD83D\\uDCFC" to "videocassette",
                "\\uD83D\\uDD0D" to "magnifying glass tilted left",
                "\\uD83D\\uDD0E" to "magnifying glass tilted right",
                "\\uD83D\\uDCA1" to "light bulb",
                "\\uD83D\\uDD26" to "flashlight",
                "\\uD83C\\uDFEE" to "red paper lantern",
                "\\uD83E\\uDE94" to "diya lamp",
                "\\uD83D\\uDCD4" to "notebook with decorative cover",
                "\\uD83D\\uDCD5" to "closed book",
                "\\uD83D\\uDCD6" to "open book",
                "\\uD83D\\uDCD7" to "green book",
                "\\uD83D\\uDCD8" to "blue book",
                "\\uD83D\\uDCD9" to "orange book",
                "\\uD83D\\uDCDA" to "books",
                "\\uD83D\\uDCD3" to "notebook",
                "\\uD83D\\uDCD2" to "ledger",
                "\\uD83D\\uDCC3" to "page with curl",
                "\\uD83D\\uDCDC" to "scroll",
                "\\uD83D\\uDCC4" to "page facing up",
                "\\uD83D\\uDCF0" to "newspaper",
                "\\uD83D\\uDCD1" to "bookmark tabs",
                "\\uD83D\\uDD16" to "bookmark",
                "\\uD83E\\uDE99" to "coin",
                "\\uD83D\\uDCB0" to "money bag",
                "\\uD83E\\uDE8E" to "treasure chest",
                "\\uD83D\\uDCB4" to "yen banknote",
                "\\uD83D\\uDCB5" to "dollar banknote",
                "\\uD83D\\uDCB6" to "euro banknote",
                "\\uD83D\\uDCB7" to "pound banknote",
                "\\uD83D\\uDCB8" to "money with wings",
                "\\uD83D\\uDCB3" to "credit card",
                "\\uD83E\\uDDFE" to "receipt",
                "\\uD83D\\uDCB9" to "chart increasing with yen",
                "\\uD83D\\uDCE7" to "e-mail",
                "\\uD83D\\uDCE8" to "incoming envelope",
                "\\uD83D\\uDCE9" to "envelope with arrow",
                "\\uD83D\\uDCE4" to "outbox tray",
                "\\uD83D\\uDCE5" to "inbox tray",
                "\\uD83D\\uDCE6" to "package",
                "\\uD83D\\uDCEB" to "closed mailbox with raised flag",
                "\\uD83D\\uDCEA" to "closed mailbox with lowered flag",
                "\\uD83D\\uDCEC" to "open mailbox with raised flag",
                "\\uD83D\\uDCED" to "open mailbox with lowered flag",
                "\\uD83D\\uDCEE" to "postbox",
                "\\uD83D\\uDCDD" to "memo",
                "\\uD83E\\uDE8C" to "eraser",
                "\\uD83D\\uDCBC" to "briefcase",
                "\\uD83D\\uDCC1" to "file folder",
                "\\uD83D\\uDCC2" to "open file folder",
                "\\uD83D\\uDCC5" to "calendar",
                "\\uD83D\\uDCC6" to "tear-off calendar",
                "\\uD83D\\uDCC7" to "card index",
                "\\uD83D\\uDCC8" to "chart increasing",
                "\\uD83D\\uDCC9" to "chart decreasing",
                "\\uD83D\\uDCCA" to "bar chart",
                "\\uD83D\\uDCCB" to "clipboard",
                "\\uD83D\\uDCCC" to "pushpin",
                "\\uD83D\\uDCCD" to "round pushpin",
                "\\uD83D\\uDCCE" to "paperclip",
                "\\uD83D\\uDCCF" to "straight ruler",
                "\\uD83D\\uDCD0" to "triangular ruler",
                "\\uD83D\\uDD12" to "locked",
                "\\uD83D\\uDD13" to "unlocked",
                "\\uD83D\\uDD0F" to "locked with pen",
                "\\uD83D\\uDD10" to "locked with key",
                "\\uD83D\\uDD11" to "key",
                "\\uD83E\\uDE8D" to "net with handle",
                "\\uD83D\\uDD28" to "hammer",
                "\\uD83E\\uDE93" to "axe",
                "\\uD83D\\uDCA3" to "bomb",
                "\\uD83E\\uDE83" to "boomerang",
                "\\uD83C\\uDFF9" to "bow and arrow",
                "\\uD83E\\uDE9A" to "carpentry saw",
                "\\uD83D\\uDD27" to "wrench",
                "\\uD83E\\uDE9B" to "screwdriver",
                "\\uD83D\\uDD29" to "nut and bolt",
                "\\uD83E\\uDDAF" to "white cane",
                "\\uD83D\\uDD17" to "link",
                "\\uD83E\\uDE9D" to "hook",
                "\\uD83E\\uDDF0" to "toolbox",
                "\\uD83E\\uDDF2" to "magnet",
                "\\uD83E\\uDE9C" to "ladder",
                "\\uD83E\\uDE8F" to "shovel",
                "\\uD83E\\uDDEA" to "test tube",
                "\\uD83E\\uDDEB" to "petri dish",
                "\\uD83E\\uDDEC" to "dna",
                "\\uD83D\\uDD2C" to "microscope",
                "\\uD83D\\uDD2D" to "telescope",
                "\\uD83D\\uDCE1" to "satellite antenna",
                "\\uD83D\\uDC89" to "syringe",
                "\\uD83E\\uDE78" to "drop of blood",
                "\\uD83D\\uDC8A" to "pill",
                "\\uD83E\\uDE79" to "adhesive bandage",
                "\\uD83E\\uDE7C" to "crutch",
                "\\uD83E\\uDE7A" to "stethoscope",
                "\\uD83E\\uDE7B" to "x-ray",
                "\\uD83D\\uDEAA" to "door",
                "\\uD83D\\uDED7" to "elevator",
                "\\uD83E\\uDE9E" to "mirror",
                "\\uD83E\\uDE9F" to "window",
                "\\uD83E\\uDE91" to "chair",
                "\\uD83D\\uDEBD" to "toilet",
                "\\uD83E\\uDEA0" to "plunger",
                "\\uD83D\\uDEBF" to "shower",
                "\\uD83D\\uDEC1" to "bathtub",
                "\\uD83E\\uDEA4" to "mouse trap",
                "\\uD83E\\uDE92" to "razor",
                "\\uD83E\\uDDF4" to "lotion bottle",
                "\\uD83E\\uDDF7" to "safety pin",
                "\\uD83E\\uDDF9" to "broom",
                "\\uD83E\\uDDFA" to "basket",
                "\\uD83E\\uDDFB" to "roll of paper",
                "\\uD83E\\uDEA3" to "bucket",
                "\\uD83E\\uDDFC" to "soap",
                "\\uD83E\\uDEE7" to "bubbles",
                "\\uD83E\\uDEA5" to "toothbrush",
                "\\uD83E\\uDDFD" to "sponge",
                "\\uD83E\\uDDEF" to "fire extinguisher",
                "\\uD83D\\uDED2" to "shopping cart",
                "\\uD83D\\uDEAC" to "cigarette",
                "\\uD83E\\uDEA6" to "headstone",
                "\\uD83E\\uDDFF" to "nazar amulet",
                "\\uD83E\\uDEAC" to "hamsa",
                "\\uD83D\\uDDFF" to "moai",
                "\\uD83E\\uDEA7" to "placard",
                "\\uD83E\\uDEAA" to "identification card",
                "\\uD83C\\uDFE7" to "ATM sign",
                "\\uD83D\\uDEAE" to "litter in bin sign",
                "\\uD83D\\uDEB0" to "potable water",
                "\\u267F" to "wheelchair symbol",
                "\\uD83D\\uDEB9" to "men’s room",
                "\\uD83D\\uDEBA" to "women’s room",
                "\\uD83D\\uDEBB" to "restroom",
                "\\uD83D\\uDEBC" to "baby symbol",
                "\\uD83D\\uDEBE" to "water closet",
                "\\uD83D\\uDEC2" to "passport control",
                "\\uD83D\\uDEC3" to "customs",
                "\\uD83D\\uDEC4" to "baggage claim",
                "\\uD83D\\uDEC5" to "left luggage",
                "\\uD83D\\uDEB8" to "children crossing",
                "\\u26D4" to "no entry",
                "\\uD83D\\uDEAB" to "prohibited",
                "\\uD83D\\uDEB3" to "no bicycles",
                "\\uD83D\\uDEAD" to "no smoking",
                "\\uD83D\\uDEAF" to "no littering",
                "\\uD83D\\uDEB1" to "non-potable water",
                "\\uD83D\\uDEB7" to "no pedestrians",
                "\\uD83D\\uDCF5" to "no mobile phones",
                "\\uD83D\\uDD1E" to "no one under eighteen",
                "\\uD83D\\uDD03" to "clockwise vertical arrows",
                "\\uD83D\\uDD04" to "counterclockwise arrows button",
                "\\uD83D\\uDD19" to "BACK arrow",
                "\\uD83D\\uDD1A" to "END arrow",
                "\\uD83D\\uDD1B" to "ON! arrow",
                "\\uD83D\\uDD1C" to "SOON arrow",
                "\\uD83D\\uDD1D" to "TOP arrow",
                "\\uD83D\\uDED0" to "place of worship",
                "\\uD83D\\uDD4E" to "menorah",
                "\\uD83D\\uDD2F" to "dotted six-pointed star",
                "\\uD83E\\uDEAF" to "khanda",
                "\\u2648" to "Aries",
                "\\u2649" to "Taurus",
                "\\u264A" to "Gemini",
                "\\u264B" to "Cancer",
                "\\u264C" to "Leo",
                "\\u264D" to "Virgo",
                "\\u264E" to "Libra",
                "\\u264F" to "Scorpio",
                "\\u2650" to "Sagittarius",
                "\\u2651" to "Capricorn",
                "\\u2652" to "Aquarius",
                "\\u2653" to "Pisces",
                "\\u26CE" to "Ophiuchus",
                "\\uD83D\\uDD00" to "shuffle tracks button",
                "\\uD83D\\uDD01" to "repeat button",
                "\\uD83D\\uDD02" to "repeat single button",
                "\\u23E9" to "fast-forward button",
                "\\u23EA" to "fast reverse button",
                "\\uD83D\\uDD3C" to "upwards button",
                "\\u23EB" to "fast up button",
                "\\uD83D\\uDD3D" to "downwards button",
                "\\u23EC" to "fast down button",
                "\\uD83C\\uDFA6" to "cinema",
                "\\uD83D\\uDD05" to "dim button",
                "\\uD83D\\uDD06" to "bright button",
                "\\uD83D\\uDCF6" to "antenna bars",
                "\\uD83D\\uDEDC" to "wireless",
                "\\uD83D\\uDCF3" to "vibration mode",
                "\\uD83D\\uDCF4" to "mobile phone off",
                "\\u2795" to "plus",
                "\\u2796" to "minus",
                "\\u2797" to "divide",
                "\\uD83D\\uDFF0" to "heavy equals sign",
                "\\u2753" to "red question mark",
                "\\u2754" to "white question mark",
                "\\u2755" to "white exclamation mark",
                "\\u2757" to "red exclamation mark",
                "\\uD83D\\uDCB1" to "currency exchange",
                "\\uD83D\\uDCB2" to "heavy dollar sign",
                "\\uD83D\\uDD31" to "trident emblem",
                "\\uD83D\\uDCDB" to "name badge",
                "\\uD83D\\uDD30" to "Japanese symbol for beginner",
                "\\u2B55" to "hollow red circle",
                "\\u2705" to "check mark button",
                "\\u274C" to "cross mark",
                "\\u274E" to "cross mark button",
                "\\u27B0" to "curly loop",
                "\\u27BF" to "double curly loop",
                "\\uD83E\\uDEDF" to "splatter",
                "\\uD83D\\uDD1F" to "emoji",
                "\\uD83D\\uDD20" to "input latin uppercase",
                "\\uD83D\\uDD21" to "input latin lowercase",
                "\\uD83D\\uDD22" to "input numbers",
                "\\uD83D\\uDD23" to "input symbols",
                "\\uD83D\\uDD24" to "input latin letters",
                "\\uD83C\\uDD8E" to "AB button (blood type)",
                "\\uD83C\\uDD91" to "CL button",
                "\\uD83C\\uDD92" to "COOL button",
                "\\uD83C\\uDD93" to "FREE button",
                "\\uD83C\\uDD94" to "ID button",
                "\\uD83C\\uDD95" to "NEW button",
                "\\uD83C\\uDD96" to "NG button",
                "\\uD83C\\uDD97" to "OK button",
                "\\uD83C\\uDD98" to "SOS button",
                "\\uD83C\\uDD99" to "UP! button",
                "\\uD83C\\uDD9A" to "VS button",
                "\\uD83C\\uDE01" to "Japanese “here” button",
                "\\uD83C\\uDE36" to "Japanese “not free of charge” button",
                "\\uD83C\\uDE2F" to "Japanese “reserved” button",
                "\\uD83C\\uDE50" to "Japanese “bargain” button",
                "\\uD83C\\uDE39" to "Japanese “discount” button",
                "\\uD83C\\uDE1A" to "Japanese “free of charge” button",
                "\\uD83C\\uDE32" to "Japanese “prohibited” button",
                "\\uD83C\\uDE51" to "Japanese “acceptable” button",
                "\\uD83C\\uDE38" to "Japanese “application” button",
                "\\uD83C\\uDE34" to "Japanese “passing grade” button",
                "\\uD83C\\uDE33" to "Japanese “vacancy” button",
                "\\uD83C\\uDE3A" to "Japanese “open for business” button",
                "\\uD83C\\uDE35" to "Japanese “no vacancy” button",
                "\\uD83D\\uDD34" to "red circle",
                "\\uD83D\\uDFE0" to "orange circle",
                "\\uD83D\\uDFE1" to "yellow circle",
                "\\uD83D\\uDFE2" to "green circle",
                "\\uD83D\\uDD35" to "blue circle",
                "\\uD83D\\uDFE3" to "purple circle",
                "\\uD83D\\uDFE4" to "brown circle",
                "\\u26AB" to "black circle",
                "\\u26AA" to "white circle",
                "\\uD83D\\uDFE5" to "red square",
                "\\uD83D\\uDFE7" to "orange square",
                "\\uD83D\\uDFE8" to "yellow square",
                "\\uD83D\\uDFE9" to "green square",
                "\\uD83D\\uDFE6" to "blue square",
                "\\uD83D\\uDFEA" to "purple square",
                "\\uD83D\\uDFEB" to "brown square",
                "\\u2B1B" to "black large square",
                "\\u2B1C" to "white large square",
                "\\u25FE" to "black medium-small square",
                "\\u25FD" to "white medium-small square",
                "\\uD83D\\uDD36" to "large orange diamond",
                "\\uD83D\\uDD37" to "large blue diamond",
                "\\uD83D\\uDD38" to "small orange diamond",
                "\\uD83D\\uDD39" to "small blue diamond",
                "\\uD83D\\uDD3A" to "red triangle pointed up",
                "\\uD83D\\uDD3B" to "red triangle pointed down",
                "\\uD83D\\uDCA0" to "diamond with a dot",
                "\\uD83D\\uDD18" to "radio button",
                "\\uD83D\\uDD33" to "white square button",
                "\\uD83D\\uDD32" to "black square button",
                "\\uD83C\\uDFC1" to "chequered flag",
                "\\uD83D\\uDEA9" to "triangular flag",
                "\\uD83C\\uDF8C" to "crossed flags",
                "\\uD83C\\uDFF4" to "black flag",
)
