package com.xw.vvtts.utils

internal val EMOJI_09: Map<String, String> = mapOf(
                "\\uD83E\\uDDB6" to "foot",
                "\\uD83D\\uDC42" to "ear",
                "\\uD83E\\uDDBB" to "ear with hearing aid",
                "\\uD83D\\uDC43" to "nose",
                "\\uD83E\\uDDE0" to "brain",
                "\\uD83E\\uDEC0" to "anatomical heart",
                "\\uD83E\\uDEC1" to "lungs",
                "\\uD83E\\uDDB7" to "tooth",
                "\\uD83E\\uDDB4" to "bone",
                "\\uD83D\\uDC40" to "eyes",
                "\\uD83D\\uDC45" to "tongue",
                "\\uD83D\\uDC44" to "mouth",
                "\\uD83E\\uDEE6" to "biting lip",
                "\\uD83D\\uDC76" to "baby",
                "\\uD83E\\uDDD2" to "child",
                "\\uD83D\\uDC66" to "boy",
                "\\uD83D\\uDC67" to "girl",
                "\\uD83E\\uDDD1" to "person",
                "\\uD83D\\uDC71" to "person: blond hair",
                "\\uD83D\\uDC68" to "man",
                "\\uD83E\\uDDD4" to "person: beard",
                "\\uD83D\\uDC69" to "woman",
                "\\uD83E\\uDDD3" to "older person",
                "\\uD83D\\uDC74" to "old man",
                "\\uD83D\\uDC75" to "old woman",
                "\\uD83D\\uDE4D" to "person frowning",
                "\\uD83D\\uDE4E" to "person pouting",
                "\\uD83D\\uDE45" to "person gesturing NO",
                "\\uD83D\\uDE46" to "person gesturing OK",
                "\\uD83D\\uDC81" to "person tipping hand",
                "\\uD83D\\uDE4B" to "person raising hand",
                "\\uD83E\\uDDCF" to "deaf person",
                "\\uD83D\\uDE47" to "person bowing",
                "\\uD83E\\uDD26" to "person facepalming",
                "\\uD83E\\uDD37" to "person shrugging",
                "\\uD83D\\uDC6E" to "police officer",
                "\\uD83D\\uDC82" to "guard",
                "\\uD83E\\uDD77" to "ninja",
                "\\uD83D\\uDC77" to "construction worker",
                "\\uD83E\\uDEC5" to "person with crown",
                "\\uD83E\\uDD34" to "prince",
                "\\uD83D\\uDC78" to "princess",
                "\\uD83D\\uDC73" to "person wearing turban",
                "\\uD83D\\uDC72" to "person with skullcap",
                "\\uD83E\\uDDD5" to "woman with headscarf",
                "\\uD83E\\uDD35" to "person in tuxedo",
                "\\uD83D\\uDC70" to "person with veil",
                "\\uD83E\\uDD30" to "pregnant woman",
                "\\uD83E\\uDEC3" to "pregnant man",
                "\\uD83E\\uDEC4" to "pregnant person",
                "\\uD83E\\uDD31" to "breast-feeding",
                "\\uD83D\\uDC7C" to "baby angel",
                "\\uD83C\\uDF85" to "Santa Claus",
                "\\uD83E\\uDD36" to "Mrs. Claus",
                "\\uD83E\\uDDB8" to "superhero",
                "\\uD83E\\uDDB9" to "supervillain",
                "\\uD83E\\uDDD9" to "mage",
                "\\uD83E\\uDDDA" to "fairy",
                "\\uD83E\\uDDDB" to "vampire",
                "\\uD83E\\uDDDC" to "merperson",
                "\\uD83E\\uDDDD" to "elf",
                "\\uD83E\\uDDDE" to "genie",
                "\\uD83E\\uDDDF" to "zombie",
                "\\uD83E\\uDDCC" to "troll",
                "\\uD83E\\uDEC8" to "hairy creature",
                "\\uD83D\\uDC86" to "person getting massage",
                "\\uD83D\\uDC87" to "person getting haircut",
                "\\uD83D\\uDEB6" to "person walking",
                "\\uD83E\\uDDCD" to "person standing",
                "\\uD83E\\uDDCE" to "person kneeling",
                "\\uD83C\\uDFC3" to "person running",
                "\\uD83D\\uDC83" to "woman dancing",
                "\\uD83D\\uDD7A" to "man dancing",
                "\\uD83D\\uDC6F" to "people with bunny ears",
                "\\uD83E\\uDDD6" to "person in steamy room",
                "\\uD83E\\uDDD7" to "person climbing",
                "\\uD83E\\uDD3A" to "person fencing",
                "\\uD83C\\uDFC7" to "horse racing",
                "\\uD83C\\uDFC2" to "snowboarder",
                "\\uD83C\\uDFC4" to "person surfing",
                "\\uD83D\\uDEA3" to "person rowing boat",
                "\\uD83C\\uDFCA" to "person swimming",
                "\\uD83D\\uDEB4" to "person biking",
                "\\uD83D\\uDEB5" to "person mountain biking",
                "\\uD83E\\uDD38" to "person cartwheeling",
                "\\uD83E\\uDD3C" to "people wrestling",
                "\\uD83E\\uDD3D" to "person playing water polo",
                "\\uD83E\\uDD3E" to "person playing handball",
                "\\uD83E\\uDD39" to "person juggling",
                "\\uD83E\\uDDD8" to "person in lotus position",
                "\\uD83D\\uDEC0" to "person taking bath",
                "\\uD83D\\uDECC" to "person in bed",
                "\\uD83D\\uDC6D" to "women holding hands",
                "\\uD83D\\uDC6B" to "woman and man holding hands",
                "\\uD83D\\uDC6C" to "men holding hands",
                "\\uD83D\\uDC8F" to "kiss",
                "\\uD83D\\uDC91" to "couple with heart",
                "\\uD83D\\uDC64" to "bust in silhouette",
                "\\uD83D\\uDC65" to "busts in silhouette",
                "\\uD83E\\uDEC2" to "people hugging",
                "\\uD83D\\uDC6A" to "family",
                "\\uD83D\\uDC63" to "footprints",
                "\\uD83E\\uDEC6" to "fingerprint",
                "\\uD83D\\uDC35" to "monkey face",
                "\\uD83D\\uDC12" to "monkey",
                "\\uD83E\\uDD8D" to "gorilla",
                "\\uD83E\\uDDA7" to "orangutan",
                "\\uD83D\\uDC36" to "dog face",
                "\\uD83D\\uDC15" to "dog",
                "\\uD83E\\uDDAE" to "guide dog",
                "\\uD83D\\uDC29" to "poodle",
                "\\uD83D\\uDC3A" to "wolf",
                "\\uD83E\\uDD8A" to "fox",
                "\\uD83E\\uDD9D" to "raccoon",
                "\\uD83D\\uDC31" to "cat face",
                "\\uD83D\\uDC08" to "cat",
                "\\uD83E\\uDD81" to "lion",
                "\\uD83D\\uDC2F" to "tiger face",
                "\\uD83D\\uDC05" to "tiger",
                "\\uD83D\\uDC06" to "leopard",
                "\\uD83D\\uDC34" to "horse face",
                "\\uD83E\\uDECE" to "moose",
                "\\uD83E\\uDECF" to "donkey",
                "\\uD83D\\uDC0E" to "horse",
                "\\uD83E\\uDD84" to "unicorn",
                "\\uD83E\\uDD93" to "zebra",
                "\\uD83E\\uDD8C" to "deer",
                "\\uD83E\\uDDAC" to "bison",
                "\\uD83D\\uDC2E" to "cow face",
                "\\uD83D\\uDC02" to "ox",
                "\\uD83D\\uDC03" to "water buffalo",
                "\\uD83D\\uDC04" to "cow",
                "\\uD83D\\uDC37" to "pig face",
                "\\uD83D\\uDC16" to "pig",
                "\\uD83D\\uDC17" to "boar",
                "\\uD83D\\uDC3D" to "pig nose",
                "\\uD83D\\uDC0F" to "ram",
                "\\uD83D\\uDC11" to "ewe",
                "\\uD83D\\uDC10" to "goat",
                "\\uD83D\\uDC2A" to "camel",
                "\\uD83D\\uDC2B" to "two-hump camel",
                "\\uD83E\\uDD99" to "llama",
                "\\uD83E\\uDD92" to "giraffe",
                "\\uD83D\\uDC18" to "elephant",
                "\\uD83E\\uDDA3" to "mammoth",
                "\\uD83E\\uDD8F" to "rhinoceros",
                "\\uD83E\\uDD9B" to "hippopotamus",
                "\\uD83D\\uDC2D" to "mouse face",
                "\\uD83D\\uDC01" to "mouse",
                "\\uD83D\\uDC00" to "rat",
                "\\uD83D\\uDC39" to "hamster",
                "\\uD83D\\uDC30" to "rabbit face",
                "\\uD83D\\uDC07" to "rabbit",
                "\\uD83E\\uDDAB" to "beaver",
                "\\uD83E\\uDD94" to "hedgehog",
                "\\uD83E\\uDD87" to "bat",
                "\\uD83D\\uDC3B" to "bear",
                "\\uD83D\\uDC28" to "koala",
                "\\uD83D\\uDC3C" to "panda",
                "\\uD83E\\uDDA5" to "sloth",
                "\\uD83E\\uDDA6" to "otter",
                "\\uD83E\\uDDA8" to "skunk",
                "\\uD83E\\uDD98" to "kangaroo",
                "\\uD83E\\uDDA1" to "badger",
                "\\uD83D\\uDC3E" to "paw prints",
                "\\uD83E\\uDD83" to "turkey",
                "\\uD83D\\uDC14" to "chicken",
                "\\uD83D\\uDC13" to "rooster",
                "\\uD83D\\uDC23" to "hatching chick",
                "\\uD83D\\uDC24" to "baby chick",
                "\\uD83D\\uDC25" to "front-facing baby chick",
                "\\uD83D\\uDC26" to "bird",
                "\\uD83D\\uDC27" to "penguin",
                "\\uD83E\\uDD85" to "eagle",
                "\\uD83E\\uDD86" to "duck",
                "\\uD83E\\uDDA2" to "swan",
                "\\uD83E\\uDD89" to "owl",
                "\\uD83E\\uDDA4" to "dodo",
                "\\uD83E\\uDEB6" to "feather",
                "\\uD83E\\uDDA9" to "flamingo",
                "\\uD83E\\uDD9A" to "peacock",
                "\\uD83E\\uDD9C" to "parrot",
                "\\uD83E\\uDEBD" to "wing",
                "\\uD83E\\uDEBF" to "goose",
                "\\uD83D\\uDC38" to "frog",
                "\\uD83D\\uDC0A" to "crocodile",
                "\\uD83D\\uDC22" to "turtle",
                "\\uD83E\\uDD8E" to "lizard",
                "\\uD83D\\uDC0D" to "snake",
                "\\uD83D\\uDC32" to "dragon face",
                "\\uD83D\\uDC09" to "dragon",
                "\\uD83E\\uDD95" to "sauropod",
                "\\uD83E\\uDD96" to "T-Rex",
                "\\uD83D\\uDC33" to "spouting whale",
                "\\uD83D\\uDC0B" to "whale",
                "\\uD83D\\uDC2C" to "dolphin",
                "\\uD83E\\uDECD" to "orca",
                "\\uD83E\\uDDAD" to "seal",
                "\\uD83D\\uDC1F" to "fish",
                "\\uD83D\\uDC20" to "tropical fish",
                "\\uD83D\\uDC21" to "blowfish",
                "\\uD83E\\uDD88" to "shark",
                "\\uD83D\\uDC19" to "octopus",
                "\\uD83D\\uDC1A" to "spiral shell",
                "\\uD83E\\uDEB8" to "coral",
                "\\uD83E\\uDEBC" to "jellyfish",
                "\\uD83E\\uDD80" to "crab",
                "\\uD83E\\uDD9E" to "lobster",
                "\\uD83E\\uDD90" to "shrimp",
                "\\uD83E\\uDD91" to "squid",
                "\\uD83E\\uDDAA" to "oyster",
                "\\uD83D\\uDC0C" to "snail",
                "\\uD83E\\uDD8B" to "butterfly",
                "\\uD83E\\uDECC" to "monarch butterfly",
                "\\uD83D\\uDC1B" to "bug",
                "\\uD83D\\uDC1C" to "ant",
                "\\uD83D\\uDC1D" to "honeybee",
                "\\uD83E\\uDEB2" to "beetle",
                "\\uD83D\\uDC1E" to "lady beetle",
                "\\uD83E\\uDD97" to "cricket",
                "\\uD83E\\uDEB3" to "cockroach",
                "\\uD83E\\uDD82" to "scorpion",
                "\\uD83E\\uDD9F" to "mosquito",
                "\\uD83E\\uDEB0" to "fly",
                "\\uD83E\\uDEB1" to "worm",
                "\\uD83E\\uDDA0" to "microbe",
                "\\uD83D\\uDC90" to "bouquet",
                "\\uD83C\\uDF38" to "cherry blossom",
                "\\uD83D\\uDCAE" to "white flower",
                "\\uD83E\\uDEB7" to "lotus",
                "\\uD83C\\uDF39" to "rose",
                "\\uD83E\\uDD40" to "wilted flower",
                "\\uD83C\\uDF3A" to "hibiscus",
                "\\uD83C\\uDF3B" to "sunflower",
                "\\uD83C\\uDF3C" to "blossom",
                "\\uD83C\\uDF37" to "tulip",
                "\\uD83E\\uDEBB" to "hyacinth",
                "\\uD83C\\uDF31" to "seedling",
                "\\uD83E\\uDEB4" to "potted plant",
                "\\uD83C\\uDF32" to "evergreen tree",
                "\\uD83C\\uDF33" to "deciduous tree",
                "\\uD83C\\uDF34" to "palm tree",
                "\\uD83C\\uDF35" to "cactus",
                "\\uD83C\\uDF3E" to "sheaf of rice",
                "\\uD83C\\uDF3F" to "herb",
                "\\uD83C\\uDF40" to "four leaf clover",
                "\\uD83C\\uDF41" to "maple leaf",
                "\\uD83C\\uDF42" to "fallen leaf",
                "\\uD83C\\uDF43" to "leaf fluttering in wind",
                "\\uD83E\\uDEB9" to "empty nest",
                "\\uD83E\\uDEBA" to "nest with eggs",
                "\\uD83C\\uDF44" to "mushroom",
                "\\uD83E\\uDEBE" to "leafless tree",
                "\\uD83C\\uDF47" to "grapes",
                "\\uD83C\\uDF48" to "melon",
                "\\uD83C\\uDF49" to "watermelon",
                "\\uD83C\\uDF4A" to "tangerine",
                "\\uD83C\\uDF4B" to "lemon",
                "\\uD83C\\uDF4C" to "banana",
                "\\uD83C\\uDF4D" to "pineapple",
                "\\uD83E\\uDD6D" to "mango",
                "\\uD83C\\uDF4E" to "red apple",
                "\\uD83C\\uDF4F" to "green apple",
                "\\uD83C\\uDF50" to "pear",
                "\\uD83C\\uDF51" to "peach",
                "\\uD83C\\uDF52" to "cherries",
                "\\uD83C\\uDF53" to "strawberry",
                "\\uD83E\\uDED0" to "blueberries",
                "\\uD83E\\uDD5D" to "kiwi fruit",
                "\\uD83C\\uDF45" to "tomato",
                "\\uD83E\\uDED2" to "olive",
                "\\uD83E\\uDD65" to "coconut",
                "\\uD83E\\uDD51" to "avocado",
                "\\uD83C\\uDF46" to "eggplant",
                "\\uD83E\\uDD54" to "potato",
                "\\uD83E\\uDD55" to "carrot",
                "\\uD83C\\uDF3D" to "ear of corn",
                "\\uD83E\\uDED1" to "bell pepper",
                "\\uD83E\\uDD52" to "cucumber",
                "\\uD83E\\uDEDD" to "pickle",
                "\\uD83E\\uDD6C" to "leafy green",
                "\\uD83E\\uDD66" to "broccoli",
                "\\uD83E\\uDDC4" to "garlic",
                "\\uD83E\\uDDC5" to "onion",
                "\\uD83E\\uDD5C" to "peanuts",
                "\\uD83E\\uDED8" to "beans",
                "\\uD83C\\uDF30" to "chestnut",
                "\\uD83E\\uDEDA" to "ginger root",
                "\\uD83E\\uDEDB" to "pea pod",
                "\\uD83E\\uDEDC" to "root vegetable",
                "\\uD83C\\uDF5E" to "bread",
                "\\uD83E\\uDD50" to "croissant",
                "\\uD83E\\uDD56" to "baguette bread",
                "\\uD83E\\uDED3" to "flatbread",
                "\\uD83E\\uDD68" to "pretzel",
                "\\uD83E\\uDD6F" to "bagel",
                "\\uD83E\\uDD5E" to "pancakes",
                "\\uD83E\\uDDC7" to "waffle",
                "\\uD83E\\uDDC0" to "cheese wedge",
                "\\uD83C\\uDF56" to "meat on bone",
                "\\uD83C\\uDF57" to "poultry leg",
                "\\uD83E\\uDD69" to "cut of meat",
                "\\uD83E\\uDD53" to "bacon",
                "\\uD83C\\uDF54" to "hamburger",
                "\\uD83C\\uDF5F" to "french fries",
                "\\uD83C\\uDF55" to "pizza",
                "\\uD83C\\uDF2D" to "hot dog",
                "\\uD83E\\uDD6A" to "sandwich",
                "\\uD83C\\uDF2E" to "taco",
                "\\uD83C\\uDF2F" to "burrito",
                "\\uD83E\\uDED4" to "tamale",
                "\\uD83E\\uDD59" to "stuffed flatbread",
                "\\uD83E\\uDDC6" to "falafel",
                "\\uD83E\\uDD5A" to "egg",
                "\\uD83C\\uDF73" to "cooking",
                "\\uD83E\\uDD58" to "shallow pan of food",
                "\\uD83C\\uDF72" to "pot of food",
                "\\uD83E\\uDED5" to "fondue",
                "\\uD83E\\uDD63" to "bowl with spoon",
                "\\uD83E\\uDD57" to "green salad",
                "\\uD83C\\uDF7F" to "popcorn",
                "\\uD83E\\uDDC8" to "butter",
                "\\uD83E\\uDDC2" to "salt",
                "\\uD83E\\uDD6B" to "canned food",
                "\\uD83C\\uDF71" to "bento box",
                "\\uD83C\\uDF58" to "rice cracker",
                "\\uD83C\\uDF59" to "rice ball",
                "\\uD83C\\uDF5A" to "cooked rice",
                "\\uD83C\\uDF5B" to "curry rice",
                "\\uD83C\\uDF5C" to "steaming bowl",
                "\\uD83C\\uDF5D" to "spaghetti",
                "\\uD83C\\uDF60" to "roasted sweet potato",
                "\\uD83C\\uDF62" to "oden",
                "\\uD83C\\uDF63" to "sushi",
                "\\uD83C\\uDF64" to "fried shrimp",
                "\\uD83C\\uDF65" to "fish cake with swirl",
                "\\uD83E\\uDD6E" to "moon cake",
                "\\uD83C\\uDF61" to "dango",
                "\\uD83E\\uDD5F" to "dumpling",
                "\\uD83E\\uDD60" to "fortune cookie",
                "\\uD83E\\uDD61" to "takeout box",
                "\\uD83C\\uDF66" to "soft ice cream",
                "\\uD83C\\uDF67" to "shaved ice",
                "\\uD83C\\uDF68" to "ice cream",
                "\\uD83C\\uDF69" to "doughnut",
                "\\uD83C\\uDF6A" to "cookie",
                "\\uD83C\\uDF82" to "birthday cake",
                "\\uD83C\\uDF70" to "shortcake",
                "\\uD83E\\uDDC1" to "cupcake",
                "\\uD83E\\uDD67" to "pie",
                "\\uD83C\\uDF6B" to "chocolate bar",
                "\\uD83C\\uDF6C" to "candy",
                "\\uD83C\\uDF6D" to "lollipop",
                "\\uD83C\\uDF6E" to "custard",
                "\\uD83C\\uDF6F" to "honey pot",
                "\\uD83C\\uDF7C" to "baby bottle",
                "\\uD83E\\uDD5B" to "glass of milk",
                "\\u2615" to "hot beverage",
                "\\uD83E\\uDED6" to "teapot",
                "\\uD83C\\uDF75" to "teacup without handle",
                "\\uD83C\\uDF76" to "sake",
                "\\uD83C\\uDF7E" to "bottle with popping cork",
                "\\uD83C\\uDF77" to "wine glass",
                "\\uD83C\\uDF78" to "cocktail glass",
                "\\uD83C\\uDF79" to "tropical drink",
                "\\uD83C\\uDF7A" to "beer mug",
                "\\uD83C\\uDF7B" to "clinking beer mugs",
                "\\uD83E\\uDD42" to "clinking glasses",
                "\\uD83E\\uDD43" to "tumbler glass",
                "\\uD83E\\uDED7" to "pouring liquid",
                "\\uD83E\\uDD64" to "cup with straw",
                "\\uD83E\\uDDCB" to "bubble tea",
                "\\uD83E\\uDDC3" to "beverage box",
                "\\uD83E\\uDDC9" to "mate",
                "\\uD83E\\uDDCA" to "ice",
                "\\uD83E\\uDD62" to "chopsticks",
                "\\uD83C\\uDF74" to "fork and knife",
                "\\uD83E\\uDD44" to "spoon",
                "\\uD83D\\uDD2A" to "kitchen knife",
                "\\uD83E\\uDED9" to "jar",
                "\\uD83C\\uDFFA" to "amphora",
                "\\uD83C\\uDF0D" to "globe showing Europe-Africa",
                "\\uD83C\\uDF0E" to "globe showing Americas",
                "\\uD83C\\uDF0F" to "globe showing Asia-Australia",
                "\\uD83C\\uDF10" to "globe with meridians",
                "\\uD83D\\uDDFE" to "map of Japan",
                "\\uD83E\\uDDED" to "compass",
                "\\uD83D\\uDED8" to "landslide",
                "\\uD83C\\uDF0B" to "volcano",
                "\\uD83D\\uDDFB" to "mount fuji",
                "\\uD83E\\uDDF1" to "brick",
                "\\uD83E\\uDEA8" to "rock",
                "\\uD83E\\uDEB5" to "wood",
                "\\uD83D\\uDED6" to "hut",
                "\\uD83C\\uDFE0" to "house",
                "\\uD83C\\uDFE1" to "house with garden",
                "\\uD83C\\uDFE2" to "office building",
                "\\uD83C\\uDFE3" to "Japanese post office",
                "\\uD83C\\uDFE4" to "post office",
                "\\uD83C\\uDFE5" to "hospital",
                "\\uD83C\\uDFE6" to "bank",
                "\\uD83C\\uDFE8" to "hotel",
                "\\uD83C\\uDFE9" to "love hotel",
                "\\uD83C\\uDFEA" to "convenience store",
                "\\uD83C\\uDFEB" to "school",
                "\\uD83C\\uDFEC" to "department store",
                "\\uD83C\\uDFED" to "factory",
                "\\uD83C\\uDFEF" to "Japanese castle",
                "\\uD83C\\uDFF0" to "castle",
                "\\uD83D\\uDC92" to "wedding",
                "\\uD83D\\uDDFC" to "Tokyo tower",
                "\\uD83D\\uDDFD" to "Statue of Liberty",
                "\\u26EA" to "church",
                "\\uD83D\\uDD4C" to "mosque",
                "\\uD83D\\uDED5" to "hindu temple",
                "\\uD83D\\uDD4D" to "synagogue",
                "\\uD83D\\uDD4B" to "kaaba",
                "\\u26F2" to "fountain",
                "\\u26FA" to "tent",
                "\\uD83C\\uDF01" to "foggy",
                "\\uD83C\\uDF03" to "night with stars",
                "\\uD83C\\uDF04" to "sunrise over mountains",
                "\\uD83C\\uDF05" to "sunrise",
                "\\uD83C\\uDF06" to "cityscape at dusk",
                "\\uD83C\\uDF07" to "sunset",
                "\\uD83C\\uDF09" to "bridge at night",
                "\\uD83C\\uDFA0" to "carousel horse",
                "\\uD83D\\uDEDD" to "playground slide",
                "\\uD83C\\uDFA1" to "ferris wheel",
                "\\uD83C\\uDFA2" to "roller coaster",
                "\\uD83D\\uDC88" to "barber pole",
                "\\uD83C\\uDFAA" to "circus tent",
                "\\uD83D\\uDE82" to "locomotive",
                "\\uD83D\\uDE83" to "railway car",
                "\\uD83D\\uDE84" to "high-speed train",
                "\\uD83D\\uDE85" to "bullet train",
                "\\uD83D\\uDE86" to "train",
                "\\uD83D\\uDE87" to "metro",
                "\\uD83D\\uDE88" to "light rail",
                "\\uD83D\\uDE89" to "station",
                "\\uD83D\\uDE8A" to "tram",
                "\\uD83D\\uDE9D" to "monorail",
                "\\uD83D\\uDE9E" to "mountain railway",
                "\\uD83D\\uDE8B" to "tram car",
                "\\uD83D\\uDE8C" to "bus",
                "\\uD83D\\uDE8D" to "oncoming bus",
                "\\uD83D\\uDE8E" to "trolleybus",
                "\\uD83D\\uDE90" to "minibus",
                "\\uD83D\\uDE91" to "ambulance",
                "\\uD83D\\uDE92" to "fire engine",
                "\\uD83D\\uDE93" to "police car",
                "\\uD83D\\uDE94" to "oncoming police car",
                "\\uD83D\\uDE95" to "taxi",
                "\\uD83D\\uDE96" to "oncoming taxi",
                "\\uD83D\\uDE97" to "automobile",
                "\\uD83D\\uDE98" to "oncoming automobile",
                "\\uD83D\\uDE99" to "sport utility vehicle",
                "\\uD83D\\uDEFB" to "pickup truck",
                "\\uD83D\\uDE9A" to "delivery truck",
                "\\uD83D\\uDE9B" to "articulated lorry",
                "\\uD83D\\uDE9C" to "tractor",
                "\\uD83D\\uDEF5" to "motor scooter",
                "\\uD83E\\uDDBD" to "manual wheelchair",
                "\\uD83E\\uDDBC" to "motorized wheelchair",
                "\\uD83D\\uDEFA" to "auto rickshaw",
                "\\uD83D\\uDEB2" to "bicycle",
                "\\uD83D\\uDEF4" to "kick scooter",
                "\\uD83D\\uDEF9" to "skateboard",
                "\\uD83D\\uDEFC" to "roller skate",
                "\\uD83D\\uDE8F" to "bus stop",
                "\\u26FD" to "fuel pump",
                "\\uD83D\\uDEDE" to "wheel",
                "\\uD83D\\uDEA8" to "police car light",
                "\\uD83D\\uDEA5" to "horizontal traffic light",
                "\\uD83D\\uDEA6" to "vertical traffic light",
                "\\uD83D\\uDED1" to "stop sign",
                "\\uD83D\\uDEA7" to "construction",
                "\\uD83D\\uDED9" to "lighthouse",
                "\\u2693" to "anchor",
                "\\uD83D\\uDEDF" to "ring buoy",
                "\\u26F5" to "sailboat",
                "\\uD83D\\uDEF6" to "canoe",
                "\\uD83D\\uDEA4" to "speedboat",
                "\\uD83D\\uDEA2" to "ship",
                "\\uD83D\\uDEEB" to "airplane departure",
                "\\uD83D\\uDEEC" to "airplane arrival",
                "\\uD83E\\uDE82" to "parachute",
                "\\uD83D\\uDCBA" to "seat",
                "\\uD83D\\uDE81" to "helicopter",
                "\\uD83D\\uDE9F" to "suspension railway",
                "\\uD83D\\uDEA0" to "mountain cableway",
                "\\uD83D\\uDEA1" to "aerial tramway",
                "\\uD83D\\uDE80" to "rocket",
                "\\uD83D\\uDEF8" to "flying saucer",
                "\\uD83E\\uDDF3" to "luggage",
                "\\u231B" to "hourglass done",
                "\\u23F3" to "hourglass not done",
                "\\u231A" to "watch",
                "\\u23F0" to "alarm clock",
                "\\uD83D\\uDD5B" to "twelve o’clock",
)
