#!/usr/bin/env python3
"""oracle/fitter.py: turn consolidated per-hanzi oracle tables into the
lang/chs runtime table the standalone chs engine plays back.

Input contract (oracle/make_table.py output):
    hanzi<TAB>pcm_count<TAB>phbuf_hex<TAB>genphon_hex<TAB>phidx_seq

Output: native/openevv/lang/chs/oracle_chs.c: static packed tables,
sorted by codepoint, searched with a binary search. pcm==0 rows
with empty phbuf/genphon are dropped ( nothing to play.

Usage: python3 oracle/fitter.py [table-dir] [output-c]"""

import glob
import os
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "oracle/table"
DST = sys.argv[2] if len(sys.argv) > 2 else "native/openevv/lang/chs/oracle_chs.c"


def cp(s):
    return ord(s.split("\t", 1)[0])


def emit_lines(out, b, indent="    "):
    for i in range(0, len(b), 12):
        out.append(indent + ", ".join("0x%02x" % c for c in b[i:i+12]) + ",")


def emit_offblob(out, ty, name, data_name, offs, hexes):
    """Offset table + packed byte blob.  Empty payloads are length 0; the
    offset simply repeats so a lookup with length 0 reads nothing. """
    out.append("static const %s %s[] = {" % (ty, name))
    out.append("    " + ", ".join(offs) + ",")
    out.append("};")
    out.append("")
    out.append("static const uint8_t %s[] = {" % data_name)
    for h in hexes:
        if h:
            emit_lines(out, bytes.fromhex(h))
    out.append("};")
    out.append("")


def main():
    rows = []
    for path in sorted(glob.glob(os.path.join(SRC, "*.consolidated.tsv"))):
        with open(path, encoding="utf-8") as fh:
            for ln in fh:
                ln = ln.rstrip("\n")
                if not ln or "\t" not in ln:
                    continue
                f = ln.split("\t")
                if len(f) < 4:
                    continue
                hanzi, pcm_s, phb, gph, pxs = (f + [""] * 5)[:5]
                try:
                    pcm = int(pcm_s or "0")
                except ValueError:
                    pcm = 0
                phb_b = bytes.fromhex(phb) if phb else b""
                gph_b = bytes.fromhex(gph) if gph else b""
                if not phb_b and not gph_b and pcm ==  0:
                    continue  # hole: nothing to play
                rows.append([cp(hanzi), pcm, phb_b, gph_b, pxs])
    if not rows:
        print("no rows"); return  1
    rows.sort(key=lambda r:r[0])
    dedup = {}
    for r in rows:
        dedup[r[0]] = r
    rows = sorted(dedup.values(), key=lambda r:r[0])

    out = []
    out.append("/* Generated by oracle/fitter.py. Do not edit. */")
    out.append("/* Standalone chs oracle tables: per-hanzi phoneme frames. */")
    out.append("/* Keyed by codepoint, sorted, bsearch-able. Columns: */")
    out.append("/* pcm = emitted sample count; phbuf/genphon/phidx = phoneme */")
    out.append("/* frame payloads, raw bytes the probe wrote back.           */")
    out.append("#include <stdint.h>")
    out.append("#include <stddef.h>")
    out.append("")
    out.append("#define CHS_ORACLE_CODEPOINTS (sizeof chs_oracle / sizeof chs_oracle[0])")
    out.append("")

    keys, pcms, phoff, phlen, gpoff, gplen, pxoff, pxlen = [], [], [], [], [], [], [], []
    phdata, gpdata, pxdata = [], [], []
    base_ph = base_gp = base_px = 0
    for cp_, pcm, phb, gph, pxs in rows:

        keys.append("0x%x" % cp_)
        pcms.append(str(pcm))
        phoff.append(str(base_ph))
        phlen.append(str(len(phb)))

        base_ph += len(phb)
        gpoff.append(str(base_gp))
        gplen.append(str(len(gph)))

        base_gp += len(gph)
        pxb = pxs.encode("ascii", errors="replace") + b"\0"
        pxoff.append(str(base_px))
        pxlen.append(str(len(pxb)))
        base_px += len(pxb)
        phdata.append(phb.hex())
        gpdata.append(gph.hex())
        pxdata.append(pxb.hex())

    out.append("static const uint32_t chs_oracle_keys[] = {")
    out.append("    " + ", ".join(keys) + ",")
    out.append("};")
    out.append("")
    out.append("static const uint32_t chs_oracle_pcm[] = {")
    out.append("    " + ", ".join(pcms) + ",")
    out.append("};")
    out.append("")

    emit_offblob(out, "uint32_t", "chs_oracle_phbuf_off", "chs_oracle_phbuf_data", phoff, phdata)
    emit_offblob(out, "uint32_t", "chs_oracle_genphon_off", "chs_oracle_genphon_data", gpoff, gpdata)
    emit_offblob(out, "uint32_t", "chs_oracle_phidx_off", "chs_oracle_phidx_data", pxoff, pxdata)

    out.append("typedef struct {")
    out.append("    uint32_t key, pcm, phoff, phlen, gpoff, gplen, pxoff, pxlen;")
    out.append("} chs_oracle_row;")
    out.append("")
    out.append("static const chs_oracle_row chs_oracle[] = {")
    for i in range(len(rows)):
        out.append("    {0x%x, %s, %s, %s, %s, %s, %s, %s}," % (
            rows[i][0], pcms[i], phoff[i], phlen[i], gpoff[i], gplen[i], pxoff[i], pxlen[i]))
    out.append("};")
    out.append("")
    out.append("static const chs_oracle_row *chs_oracle_find(uint32_t cp) {")
    out.append("    size_t lo = 0, hi = CHS_ORACLE_CODEPOINTS;")
    out.append("    while (lo < hi) {")
    out.append("        size_t mid = lo + (hi - lo) / 2;")
    out.append("        if (chs_oracle_keys[mid] < cp) lo = mid + 1;")
    out.append("        else hi = mid;")
    out.append("    }")
    out.append("    if (lo < CHS_ORACLE_CODEPOINTS && chs_oracle_keys[lo] == cp)")
    out.append("        return &chs_oracle[lo];")
    out.append("    return 0;")
    out.append("}")
    out.append("")
    out.append("/* Exported for the JNI bridge: raw-GB18030 lookup.  Rows with")
    out.append("   audio only; keys are the GB18030 bytes of the hanzi -- 2-byte")
    out.append("   GBK pairs (uint32 as-is, < 0x10000) or 4-byte GB18030")
    out.append("   extensions (packed, >= 0x81000000) -- so the two ranges never")
    out.append("   collide and one sorted array serves both.  Row slots hold the")
    out.append("   index into chs_oracle[]; *len is the PCM byte length. */")
    gbk_idx = []
    for i, (cp_, pcm, phb, gph, pxs) in enumerate(rows):
        if pcm <= 0:
            continue
        b = chr(cp_).encode("gb18030")
        if len(b) == 2:
            k = (b[0] << 8) | b[1]
        elif len(b) == 4:
            k = (b[0] << 24) | (b[1] << 16) | (b[2] << 8) | b[3]
        else:
            continue
        gbk_idx.append((k, i))
    gbk_idx.sort()
    if gbk_idx:
        out.append("#define CHS_ORACLE_GBK_ENTRIES (sizeof chs_oracle_gbk_keys / sizeof chs_oracle_gbk_keys[0])")
        out.append("")
        out.append("static const uint32_t chs_oracle_gbk_keys[] = {")
        out.append("    " + ", ".join("0x%x" % k for k, _ in gbk_idx) + ",")
        out.append("};")
        out.append("")
        out.append("static const uint16_t chs_oracle_gbk_rows[] = {")
        out.append("    " + ", ".join(str(i) for _, i in gbk_idx) + ",")
        out.append("};")
        out.append("")
        out.append("int chs_oracle_pcm_for_gbk(uint32_t gbk, const uint8_t **data, uint32_t *len) {")
        out.append("    size_t lo = 0, hi = CHS_ORACLE_GBK_ENTRIES;")
        out.append("    while (lo < hi) {")
        out.append("        size_t mid = lo + (hi - lo) / 2;")
        out.append("        if (chs_oracle_gbk_keys[mid] < gbk) lo = mid + 1;")
        out.append("        else hi = mid;")
        out.append("    }")
        out.append("    if (lo < CHS_ORACLE_GBK_ENTRIES && chs_oracle_gbk_keys[lo] == gbk) {")
        out.append("        const chs_oracle_row *r = &chs_oracle[chs_oracle_gbk_rows[lo]];")
        out.append("        *data = chs_oracle_genphon_data + r->gpoff;")
        out.append("        *len = r->gplen;")
        out.append("        return 1;")
        out.append("    }")
        out.append("    return 0;")
        out.append("}")
        out.append("")

    with open(DST, "w", encoding="ascii") as fh:
        fh.write("\n".join(out) + "\n")

    n_audio = sum(1 for p in pcms if int(p) > 0)
    print("fitter: %d rows -> %s (audio: %d, gbk-index: %d, phbuf bytes: %d, genphon bytes: %d)"
          % (len(rows), DST, n_audio, len(gbk_idx), sum(map(int, phlen)), sum(map(int, gplen))))
    return  0


if __name__ == "__main__":
    sys.exit(main())