#!/usr/bin/env python3
"""Merge old compiled oracle rows into fresh consolidated rows, emit full oracle_chs.c.

Sources:
  A) oracle/table/*.consolidated.tsv   (fresh sweep; has 最新咪群合有... audio)
  B) old native/openevv/lang/chs/oracle_chs.c ( legacy sweep; has ~8k rows A lacks)
Output: fresh oracle_chs.c with both, plus chs_oracle_pcm_for_gbk ( jni needs it).
"""
import glob
import os
import re
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "/root/eloquence-re/eloquence-android/oracle/table"
OLD = sys.argv[2] if len(sys.argv) > 2 else "/root/eloquence-re/eloquence-android/native/openevv/lang/chs/oracle_chs.c"
DST = sys.argv[3] if len(sys.argv) > 3 else "/root/.hermes/cache/scratch/pa/oracle_merged.c"

def cp(s):
    return ord(s.split("\t", 1)[0])

def read_consolidated(src_dir):
    rows = {}
    for path in sorted(glob.glob(os.path.join(src_dir,"*.consolidated.tsv"))):
        with open(path, encoding="utf-8") as fh:
            for ln in fh:
                ln = ln.rstrip("\n")
                if not ln or "\t" not in ln:
                    continue
                f = ln.split("\t")
                if len(f) < 4:
                    continue
                hanzi, pcm_s, phb, gph, pxs = (f + [""] * 5)[:5]
                try:
                    pcm = int(pcm_s or "0")
                except ValueError:
                    pcm = 0
                phb_b = bytes.fromhex(phb) if phb else b""
                gph_b = bytes.fromhex(gph) if gph else b""
                if not phb_b and not gph_b and pcm == 0:
                    continue
                cpv = cp(hanzi)
                rows.setdefault(cpv, []).append((pcm, phb_b, gph_b, pxs))
    merged = {}
    for k,v in rows.items():
        best = max(v, key=lambda t: (len(t[1]) + len(t[2]), t[0]))
        merged[k] = best
    return merged

def read_old_c(path):
    txt = open(path, encoding="utf-8", errors="replace").read()
    keys = []
    rows_in = []
    for m in re.finditer(r"\{0x([0-9a-fA-F]+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+)\}", txt):
        key = int(m.group(1), 16)
        pcm = int(m.group(2))
        phoff = int(m.group(3))
        phlen = int(m.group(4))
        gpoff = int(m.group(5))
        gplen = int(m.group(6))
        pxoff = int(m.group(7))
        pxlen = int(m.group(8))
        keys.append((key, pcm, phoff, phlen, gpoff, gplen, pxoff, pxlen))
    if not keys:

        return {}
    def blob(name):
        i = txt.index(name)
        j = txt.index("};", i)
        body = txt[i:j]
        k = body.index("{")
        tail = body[k+1:]
        out = bytearray()
        for tok in re.findall(r"0x([0-9a-fA-F]+)", tail):
            out.append(int(tok,16))
        return bytes(out)
    phdata = blob("chs_oracle_phbuf_data")
    gpdata = blob("chs_oracle_genphon_data")
    pxdata = blob("chs_oracle_phidx_data")
    rows = {}
    for key, pcm, phoff, phlen, gpoff, gplen, pxoff, pxlen in keys:
        phb = phdata[phoff:phoff+phlen] if phlen else b""
        gph = gpdata[gpoff:gpoff+gplen] if gplen else b""
        pxs = pxdata[pxoff:pxoff+pxlen].decode("ascii", errors="replace") if pxlen else ""
        rows[key] = (pcm, phb, gph, pxs)
    return rows

def merge_sources(fresh, legacy):
    out = {}
    for cpv, val in fresh.items():
        out[cpv] = val
    for cpv, val in legacy.items():
        if cpv not in out:
            out[cpv] = val
            continue
        cur = out[cpv]
        if len(cur[2]) == 0 and len(val[2]) > 0:
            out[cpv] = val
        elif len(cur[1]) == 0 and len(cur[2]) == 0 and len(val[1]) > 0:
            out[cpv] = val
    return out

def emit(out, rows):
    items = sorted(rows.items())
    L = []
    L.append("/* Generated by oracle/merge_build.py. Do not edit. */")
    L.append("/* Standalone chs oracle tables: per-hanzi phoneme frames. */")
    L.append("/* Keyed by codepoint, sorted, bsearch-able. Columns: */")
    L.append("/* pcm = emitted sample count; phbuf/genphon/phidx = phoneme */")
    L.append("/* frame payloads, raw bytes the probe wrote back.           */")
    L.append("#include <stdint.h>")
    L.append("#include <stddef.h>")
    L.append("")
    L.append("#define CHS_ORACLE_CODEPOINTS (sizeof chs_oracle / sizeof chs_oracle[0])")
    L.append("")
    keys = []
    pcms = []
    phoff = []
    phlen = []
    gpoff = []
    gplen = []
    pxoff = []
    pxlen = []
    phdata = bytearray()
    gpdata = bytearray()
    pxdata = bytearray()
    for cpv, (pcm, phb, gph, pxs) in items:
        keys.append("%d" % cpv)
        pcms.append(str(pcm))
        phoff.append(str(len(phdata)))
        phlen.append(str(len(phb)))
        phdata += phb
        gpoff.append(str(len(gpdata)))
        gplen.append(str(len(gph)))
        gpdata += gph
        pxb = pxs.encode("ascii", errors="replace") + b"\0" if pxs else b""
        pxoff.append(str(len(pxdata)))
        pxlen.append(str(len(pxb)))
        pxdata += pxb
    L.append("static const uint32_t chs_oracle_keys[] = {")
    L.append("    " + ", ".join(keys) + ",")
    L.append("};")
    L.append("")
    L.append("static const uint32_t chs_oracle_pcm[] = {")
    L.append("    " + ", ".join(pcms) + ",")
    L.append("};")
    L.append("")
    for name, offs, data in (("chs_oracle_phbuf_off", phoff, phdata),
                              ("chs_oracle_genphon_off", gpoff, gpdata),
                              ("chs_oracle_phidx_off", pxoff, pxdata)):
        L.append("static const uint32_t %s[] = {" % name)
        L.append("    " + ", ".join(offs) + ",")
        L.append("};")
        L.append("")
        L.append("static const uint8_t %s_data[] = {" % name.replace("_off",""))
        for i in range(0, len(data), 12):
            chunk = data[i:i+12]
            L.append("    " + ", ".join("0x%02x" % c for c in chunk) + ",")
        L.append("};")
        L.append("")
    L.append("typedef struct {")
    L.append("    uint32_t key, pcm, phoff, phlen, gpoff, gplen, pxoff, pxlen;")
    L.append("} chs_oracle_row;")
    L.append("")
    L.append("static const chs_oracle_row chs_oracle[] = {")
    for i in range(len(items)):
        L.append("    {0x%x, %s, %s, %s, %s, %s, %s, %s}," % (
            items[i][0], pcms[i], phoff[i], phlen[i], gpoff[i], gplen[i], pxoff[i], pxlen[i]))
    L.append("};")
    L.append("")
    L.append("static const chs_oracle_row *chs_oracle_find(uint32_t cp) {")
    L.append("    size_t lo = 0, hi = CHS_ORACLE_CODEPOINTS;")
    L.append("    while (lo < hi) {")
    L.append("        size_t mid = lo + (hi - lo) / 2;")
    L.append("        if (chs_oracle_keys[mid] < cp) lo = mid + 1;")
    L.append("        else hi = mid;")
    L.append("    }")
    L.append("    if (lo < CHS_ORACLE_CODEPOINTS && chs_oracle_keys[lo] == cp)")
    L.append("        return &chs_oracle[lo];")
    L.append("    return 0;")
    L.append("}")
    L.append("")
    L.append("/* Exported for the JNI bridge: raw-GB18030 lookup. */")
    gbk_idx = []
    for i in range(len(items)):
        cpv = items[i][0]
        pcm = items[i][1][0]
        gph = items[i][1][2]
        if len(gph) <=  0 and pcm <= 0:
            continue
        try:
            b = chr(cpv).encode("gb18030")
        except Exception:
            continue
        if len(b) == 2:
            k = (b[0] << 8) | b[1]
        elif len(b) == 4:
            k = (b[0] << 24) | (b[1] << 16) |(b[2] << 8) | b[3]
        else:
            continue
        gbk_idx.append((k, i, pcm))
    gbk_idx.sort(key=lambda t: t[0])
    L.append("/* Rows with audio only; keys are the GB18030 bytes of the hanzi. */")
    L.append("#define CHS_ORACLE_GBK_ENTRIES (sizeof chs_oracle_gbk_keys / sizeof chs_oracle_gbk_keys[0])")
    L.append("")
    L.append("static const uint32_t chs_oracle_gbk_keys[] = {")
    L.append("    " + ", ".join("0x%x" % t[0] for t in gbk_idx) + ",")
    L.append("};")
    L.append("")
    L.append("static const uint16_t chs_oracle_gbk_rows[] = {")
    L.append("    " + ", ".join(str(t[1]) for t in gbk_idx) + ",")
    L.append("};")
    L.append("")
    L.append("int chs_oracle_pcm_for_gbk(uint32_t gbk, const uint8_t **data, uint32_t *len) {")
    L.append("    size_t lo = 0, hi = CHS_ORACLE_GBK_ENTRIES;")
    L.append("    while (lo < hi) {")
    L.append("        size_t mid = lo + (hi - lo) / 2;")
    L.append("        if (chs_oracle_gbk_keys[mid] < gbk) lo = mid + 1;")
    L.append("        else hi = mid;")
    L.append("    }")
    L.append("    if (lo < CHS_ORACLE_GBK_ENTRIES && chs_oracle_gbk_keys[lo] == gbk) {")
    L.append("        const chs_oracle_row *r = &chs_oracle[chs_oracle_gbk_rows[lo]];")
    L.append("        *data = chs_oracle_genphon_data + r->gpoff;")
    L.append("        *len = r->gplen;")
    L.append("        return 1;")
    L.append("    }")
    L.append("    return 0;")
    L.append("}")
    L.append("")
    with open(DST, "w", encoding="ascii") as fh:
        fh.write("\n".join(L) + "\n")
    print("emitted %d rows -> %s (pcm>0: %d, gbk entries: %d, phbuf bytes: %d, genphon bytes: %d)"
          % (len(items), DST, sum(1 for t in items if t[1][0] > 0), len(gbk_idx),
             sum(len(t[1][1]) for t in items), sum(len(t[1][2]) for t in items)))
    return items

def coverage(items, strings):
    keys = set(t[0] for t in items)
    for s in strings:
        miss = []
        seen2 = set()
        for ch in s:
            if ord(ch) not in keys:
                if ch not in seen2:
                    seen2.add(ch)
                    miss.append(ch)
        tot = len(set(s))
        print("cover %2d/%d  misses: %s" % (tot - len(miss), tot, "".join(miss) if miss else ""))

def main():
    fresh = read_consolidated(SRC)
    legacy = read_old_c(OLD)
    print("fresh rows: %d, legacy rows: %d" % (len(fresh), len(legacy)))
    rows = merge_sources(fresh, legacy)
    items = emit(None, rows)
    tests = ["最新悄咪咪收集的一百个群合集，附全网最有趣好用的机器人",
              "最新悄悄咪咪收集的",
              "一零零零零",
              "零一二三四五六七八九",
              "10000个群合集"]
    coverage(items, tests)
    return 0

if __name__ == "__main__":
    sys.exit(main())
