#!/usr/bin/env python3
"""Generate lang/<tag>/rom_tables_<tag>.{c,h} from the lifted dylib tables.

The C holds every lifted table byte-for-byte, one aligned blob per run of
contiguous lifted bytes in a section, with a named pointer and length per
table into its blob - the same contract tools/rom/tables.py produces for
jajp (blob + pointers, so a packed read running past a table's end finds
what the original found). Mangled symbols shorten to their last component.
"""

import json
import os
import re

LIFT = '/root/eloquence-re/eloquence-android/oracle/rom_lift'
MODS = {'chsrom': 'chs', 'chtrom': 'cht', 'korrom': 'kor'}
OUT = '/root/eloquence-re/eloquence-android/lang'


def short_name(sym):
    s = sym.lstrip('_')
    if '::' in s:
        s = s.split('::')[-1]
    s = re.sub(r'\..*$', '', s)          # cut .cpp/.c/line suffixes
    s = re.sub(r'(?<=[0-9])[ASET]$', '', s)  # trailing mangled-type marker
    return s


def build_runs(entries):
    """Group entries into contiguous runs: [(sec, first_addr, blob_bytes)]."""
    runs = []
    for e in sorted(entries, key=lambda e: e['addr']):
        data = open(os.path.join(LIFT, e['mod'], e['file']), 'rb').read()
        addr = int(e['addr'], 16)
        if runs and runs[-1]['sec'] == e['sec'] and addr == runs[-1]['next']:
            runs[-1]['bytes'] += data
            runs[-1]['next'] += len(data)
        else:
            runs.append({'sec': e['sec'], 'first': addr,
                         'next': addr + len(data), 'bytes': data})
    return runs


def emit(tag, mod):
    man = json.load(open(os.path.join(LIFT, 'manifest.json')))
    entries = [dict(e, mod=mod) for e in man[mod]]
    runs = build_runs(entries)
    run_ids = {}
    for r in runs:
        run_ids[(r['sec'], r['first'])] = r

    h = (f"/* What lang/{tag}/rom_tables_{tag}.c defines.\n"
         f" * Generated by oracle/ghidra/rom_tables_gen.py from {mod}.dylib's\n"
         " * named tables (StaticDict/korData), lifted byte for byte (x86_64\n"
         " * slice, VA==fileoff). One blob per contiguous run, a pointer per\n"
         " * table. */\n\n")
    h += f"#ifndef ROM_TABLES_{tag.upper()}_H\n#define ROM_TABLES_{tag.upper()}_H\n\n"
    h += '#include <stdint.h>\n\n'
    c = (f"/* lang/{tag}/rom_tables_{tag}.c - generated, see rom_tables_{tag}.h */\n\n"
         f'#include "rom_tables_{tag}.h"\n\n')

    for r in runs:
        name = f"{tag}_blob_{runs.index(r)}"
        size = len(r['bytes'])
        c += f"static const uint8_t {name}[{size}] __attribute__((aligned(8))) = {{\n"
        for i in range(0, size, 24):
            c += '    ' + ','.join(f'{b:#04x}' for b in r['bytes'][i:i + 24]) + ',\n'
        c += '};\n\n'
        r['blob'] = name

    for e in sorted(entries, key=lambda e: e['addr']):
        addr = int(e['addr'], 16)
        r = next(r2 for r2 in runs
                 if r2['sec'] == e['sec'] and r2['first'] <= addr < r2['next'])
        ptr = f"{tag}_s_{short_name(e['sym'])}"
        off = addr - r['first']
        c += (f"const uint8_t *const {ptr} = "
              f"&{r['blob']}[{off}];  /* {e['size']}B, {e['sec']} */\n")
        h += (f'extern const uint8_t *const {ptr};\n')
        c += f"const int32_t {ptr}_n = {e['size']};\n"
        h += f'extern const int32_t {ptr}_n;\n'
    h += '\n#endif\n'
    d = os.path.join(OUT, tag)
    os.makedirs(d, exist_ok=True)
    open(os.path.join(d, f'rom_tables_{tag}.c'), 'w').write(c)
    open(os.path.join(d, f'rom_tables_{tag}.h'), 'w').write(h)
    print(f'{tag}: {len(runs)} runs, {len(entries)} tables, '
          f'{sum(len(r["bytes"]) for r in runs)} bytes, '
          f'c={len(c)}B h={len(h)}B')


if __name__ == '__main__':
    for mod, tag in MODS.items():
        emit(tag, mod)