/* Generated by tools/rules/emit.py. Do not edit.

   The language's rules as bytecode, with the constants,
   the string addresses and the runtime entry points they
   name pulled out beside them.

   A pronunciation changed in lang/chs/chs.dict is written
   back here by tools/module/dict.py: the pools grow, and
   the edited action gets a block of its own at the end of
   its rule with the switch pointed at it. Running this
   lifter again puts IBM's own back and loses those
   edits. */

#include "delta_rules_chs.h"

const uint8_t chs_delta_rule_code[] = {
    6,0,4,136,255,0,17,1,0,0,17,4,136,255,0,0,
    0,2,2,3,0,7,0,7,0,6,0,5,0,0,6,20,
    1,20,1,2,1,246,0,6,0,4,136,255,0,17,4,136,
    255,6,0,4,200,255,0,17,4,200,255,6,0,4,224,255,
    0,17,4,224,255,6,0,4,212,255,0,17,4,212,255,6,
    0,4,44,255,0,17,4,44,255,17,5,0,0,0,1,0,
    6,6,19,6,3,0,7,0,7,0,2,1,246,0,6,0,
    3,16,0,7,17,7,7,6,0,4,244,255,0,17,4,244,
    255,17,3,12,0,6,0,4,236,255,0,17,4,236,255,17,
    5,0,0,0,2,0,5,5,17,5,0,0,0,3,0,1,
    6,6,0,4,244,255,0,17,4,244,255,6,0,4,236,255,
    0,17,4,236,255,17,5,0,0,0,4,0,3,9,17,2,
    0,0,17,1,1,0,17,1,2,0,17,5,0,0,0,5,
    0,4,13,19,13,3,0,7,0,7,0,2,0,15,1,6,
    0,4,252,255,0,17,4,252,255,17,5,0,0,0,6,0,
    2,2,20,1,20,1,17,1,3,0,17,7,6,0,7,0,
    2,2,20,1,20,1,6,0,1,3,0,0,1,46,1,17,
    7,6,0,8,0,1,1,6,0,3,248,255,0,7,0,7,
    0,8,7,7,4,0,20,1,6,0,1,0,0,0,10,7,
    0,
};

const int32_t chs_delta_rule_imm[] = {
    0,1,2,94,
};

const uint8_t chs_delta_rule_map[] = { 0 };

/* The runtime the rules call. Declared without argument
   lists because every arity from none to twenty-five
   appears among them, and each call site says how many it
   is passing. */
extern void ventproc();
extern void get_parm();
extern void fence();
extern void lpta_rpta_loadp();
extern void insert_2pt_s();
extern void backtrack_function();
extern void vretproc();
extern void succeed();

const delta_rule_fn chs_delta_rule_entry[] = {
    0,  /* planted by the interpreter itself */
    (delta_rule_fn)ventproc,
    (delta_rule_fn)get_parm,
    (delta_rule_fn)fence,
    (delta_rule_fn)lpta_rpta_loadp,
    (delta_rule_fn)insert_2pt_s,
    (delta_rule_fn)backtrack_function,
    (delta_rule_fn)vretproc,
    (delta_rule_fn)succeed,
};

/* Which of each entry's arguments are pointers, a bit
   each, and bit thirty-one for one that answers with one.
   A rule pushes references, and where a reference is a
   distance into the region rather than an address, an
   argument an entry declares as a pointer has to have the
   base put back before the call. Nought for this module's
   own rules: they take references and keep them.

   Read from the entries' own C declarations by
   tools/rules/entrysig.py, so no signature is written down
   twice and none can go stale. */
const uint32_t chs_delta_rule_argmask[] = {
    0,
    0x0000003fu,
    0x00000007u,
    0x00000005u,
    0x00000007u,
    0x00000009u,
    0x00000003u,
    0x00000001u,
    0x00000001u,
};

/* Their names, for saying what a run did. */
const char *const chs_delta_rule_entry_name[] = {
    "setjmp3",
    "ventproc",
    "get_parm",
    "fence",
    "lpta_rpta_loadp",
    "insert_2pt_s",
    "backtrack_function",
    "vretproc",
    "succeed",
};

/* The language's string constants, and whatever else a
   rule names by address. */
extern uint8_t chs_evv_data[];
extern uint8_t chs_evv_bss[];

const void *const chs_delta_rule_sym[] = {
    chs_evv_data + 27,
};

const int chs_delta_rule_sym_count = 1;

const delta_rule chs_delta_rules[] = {
    { "apply_chi_h_rules", "chs.obj", 0, 305, 448, 8, 2 },
};

const int chs_delta_rule_count = 1;

/* The landing place a rule plants for a backtrack is not
   a call the interpreter can make on its behalf. */
const int chs_delta_rule_setjmp = 0;
