/* Generated by tools/rules/emit.py. Do not edit.

   Each of the language's rules under its own name, run by
   the interpreter rather than by the code its compiler
   generated. The first argument is always the machine.

   The names carry the language in front of them, because
   two languages share most of these and a program may have
   both in it. What a run reports is the name without it,
   which is what the rule table holds. */

#include "evv_arena.h"
#include "delta_rules_chs.h"

int32_t chs_apply_chi_a_rules(int32_t a0, int32_t a1, int32_t a2)
{
    int32_t a[3];

    a[0] = a0;
    a[1] = a1;
    a[2] = a2;
    return delta_run_rule(EVV_AT(void *, a0),
                          &chs_delta_rules[0], a, 3);
}

int32_t chs_apply_chi_c_rules(int32_t a0, int32_t a1)
{
    int32_t a[2];

    a[0] = a0;
    a[1] = a1;
    return delta_run_rule(EVV_AT(void *, a0),
                          &chs_delta_rules[1], a, 2);
}

int32_t chs_apply_chi_h_rules(int32_t a0, int32_t a1)
{
    int32_t a[2];

    a[0] = a0;
    a[1] = a1;
    return delta_run_rule(EVV_AT(void *, a0),
                          &chs_delta_rules[2], a, 2);
}

int32_t chs_apply_chi_j_rules(int32_t a0, int32_t a1)
{
    int32_t a[2];

    a[0] = a0;
    a[1] = a1;
    return delta_run_rule(EVV_AT(void *, a0),
                          &chs_delta_rules[3], a, 2);
}

int32_t chs_apply_chi_q_rules(int32_t a0, int32_t a1)
{
    int32_t a[2];

    a[0] = a0;
    a[1] = a1;
    return delta_run_rule(EVV_AT(void *, a0),
                          &chs_delta_rules[4], a, 2);
}

int32_t chs_apply_chi_s_rules(int32_t a0, int32_t a1)
{
    int32_t a[2];

    a[0] = a0;
    a[1] = a1;
    return delta_run_rule(EVV_AT(void *, a0),
                          &chs_delta_rules[5], a, 2);
}

int32_t chs_apply_chi_w_rules(int32_t a0, int32_t a1)
{
    int32_t a[2];

    a[0] = a0;
    a[1] = a1;
    return delta_run_rule(EVV_AT(void *, a0),
                          &chs_delta_rules[6], a, 2);
}

int32_t chs_apply_chi_y_rules(int32_t a0, int32_t a1)
{
    int32_t a[2];

    a[0] = a0;
    a[1] = a1;
    return delta_run_rule(EVV_AT(void *, a0),
                          &chs_delta_rules[7], a, 2);
}

int32_t chs_apply_chi_z_rules(int32_t a0, int32_t a1)
{
    int32_t a[2];

    a[0] = a0;
    a[1] = a1;
    return delta_run_rule(EVV_AT(void *, a0),
                          &chs_delta_rules[8], a, 2);
}

