/* Generated by tools/rules/emit.py. Do not edit.

   What this language calls its own tables. Every one of
   them carries the language, because a program may have
   several language modules in it and IBM gave the tables
   the same names in every one; src/delta/delta_lang.h says how
   the engine reaches whichever is in force, and
   delta_lang_chs.c is where these are gathered. */

#ifndef DELTA_RULES_CHS_H
#define DELTA_RULES_CHS_H

#include <stdint.h>

#include "delta_lang.h"

extern const delta_store  chs_delta_const_store[];
extern const uint8_t      chs_delta_rule_code[];
extern const int32_t      chs_delta_rule_imm[];
extern const uint8_t      chs_delta_rule_map[];
extern const delta_rule_fn chs_delta_rule_entry[];
extern const uint32_t     chs_delta_rule_argmask[];
extern const char *const  chs_delta_rule_entry_name[];
extern const void *const  chs_delta_rule_sym[];
extern const int          chs_delta_rule_sym_count;
extern const delta_rule   chs_delta_rules[];
extern const int          chs_delta_rule_count;
extern const int          chs_delta_rule_setjmp;

/* And the same under the plain names, for the generated C
   beside this, which says what the rules said. Safe as
   macros because only this language's own files include
   this header, and each of them includes just the one. */
#define delta_const_store      chs_delta_const_store
#define delta_rule_code        chs_delta_rule_code
#define delta_rule_imm         chs_delta_rule_imm
#define delta_rule_map         chs_delta_rule_map
#define delta_rule_entry       chs_delta_rule_entry
#define delta_rule_argmask     chs_delta_rule_argmask
#define delta_rule_entry_name  chs_delta_rule_entry_name
#define delta_rule_sym         chs_delta_rule_sym
#define delta_rule_sym_count   chs_delta_rule_sym_count
#define delta_rules            chs_delta_rules
#define delta_rule_count       chs_delta_rule_count
#define delta_rule_setjmp      chs_delta_rule_setjmp

/* Every entry a rule can call. A call in the decompiled C
   names the entry it was written against rather than the
   index this table happens to give it. Plain names, not
   the language's: only this language's own files read
   them, and each of those includes only this header. */
enum {
    DELTA_ENTRY_setjmp3 = 0,
    DELTA_ENTRY_ventproc = 1,
    DELTA_ENTRY_get_parm = 2,
    DELTA_ENTRY_fence = 3,
    DELTA_ENTRY_starttest = 4,
    DELTA_ENTRY_setscan_r = 5,
    DELTA_ENTRY_test_string_s = 6,
    DELTA_ENTRY_insert_2pt_s = 7,
    DELTA_ENTRY_vback = 8,
    DELTA_ENTRY_vretproc = 9,
    DELTA_ENTRY_succeed = 10,
    DELTA_ENTRY_setscan_nof_r = 11,
    DELTA_ENTRY_backtrack_function = 12,
    DELTA_ENTRY_test_synch = 13,
    DELTA_ENTRY_lpta_rpta_loadp = 14,
    DELTA_ENTRY_bspush_ca_scan = 15,
    DELTA_ENTRY_advance_tok = 16,
    DELTA_ENTRY_savescptr = 17,
    DELTA_ENTRY_setscan_l = 18,
};

/* The largest frame any rule asks for, base and arguments
   included, so one buffer serves them all. */
#define DELTA_RULE_FRAME_MAX 500

#endif
